<?php

namespace CommonBundle\Repository\User\Person;

use CommonBundle\Entity\General\AcademicYear;

/**
 * Academic
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Academic extends \CommonBundle\Repository\User\Person
{
    /**
     * @param  integer $id
     * @return \CommonBundle\Entity\User\Person\Academic|null
     */
    public function findOneById($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('CommonBundle\Entity\User\Person\Academic', 'p')
            ->where(
                $query->expr()->eq('p.id', ':id')
            )
            ->setParameter('id', $id)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param  string $username
     * @return \Doctrine\ORM\Query
     */
    public function findAllByUsernameQuery($username)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('CommonBundle\Entity\User\Person\Academic', 'p')
            ->where(
                $query->expr()->like($query->expr()->lower('p.username'), ':username')
            )
            ->setParameter('username', '%' . strtolower($username) . '%')
            ->getQuery();
    }

    /**
     * @param  string $name
     * @return \Doctrine\ORM\Query
     */
    public function findAllByNameQuery($name)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('CommonBundle\Entity\User\Person\Academic', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->orX(
                        $query->expr()->like(
                            $query->expr()->concat(
                                $query->expr()->lower($query->expr()->concat('p.firstName', "' '")),
                                $query->expr()->lower('p.lastName')
                            ),
                            ':name'
                        ),
                        $query->expr()->like(
                            $query->expr()->concat(
                                $query->expr()->lower($query->expr()->concat('p.lastName', "' '")),
                                $query->expr()->lower('p.firstName')
                            ),
                            ':name'
                        ),
                        $query->expr()->like('p.universityIdentification', ':name')
                    ),
                    $query->expr()->eq('p.canLogin', 'true')
                )
            )
            ->setParameter('name', '%' . strtolower($name) . '%')
            ->getQuery();
    }

    /**
     * @param  string $universityIdentification
     * @return \Doctrine\ORM\Query
     */
    public function findAllByUniversityIdentificationQuery($universityIdentification)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('CommonBundle\Entity\User\Person\Academic', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->like('p.universityIdentification', ':universityIdentification'),
                    $query->expr()->eq('p.canLogin', 'true')
                )
            )
            ->setParameter('universityIdentification', '%' . strtolower($universityIdentification) . '%')
            ->getQuery();
    }

    /**
     * @param  string $username
     * @return \CommonBundle\Entity\User\Person|null
     */
    public function findOneByUsername($username)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        $resultSet = $query->select('p')
            ->from('CommonBundle\Entity\User\Person\Academic', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->orX(
                        $query->expr()->eq($query->expr()->lower('p.username'), ':username'),
                        $query->expr()->eq('p.universityIdentification', ':username')
                    ),
                    $query->expr()->eq('p.canLogin', 'true')
                )
            )
            ->setParameter('username', strtolower($username))
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        if ($resultSet) {
            return $resultSet;
        }

        $barcode = $this->getEntityManager()
            ->getRepository('CommonBundle\Entity\User\Barcode')
            ->findOneByBarcode($username);

        if ($barcode) {
            return $barcode->getPerson();
        }

        return null;
    }

    /**
     * @param  AcademicYear $academicYear
     * @return array
     */
    public function findAllMembers(AcademicYear $academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        $resultSet = $query->select('s')
            ->from('CommonBundle\Entity\User\Status\Organization', 's')
            ->innerJoin('s.person', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->neq('s.status', '\'non_member\''),
                    $query->expr()->eq('s.academicYear', ':academicYear'),
                    $query->expr()->eq('p.canLogin', 'true')
                )
            )
            ->setParameter('academicYear', $academicYear->getId())
            ->getQuery()
            ->getResult();

        $persons = array();
        foreach ($resultSet as $result) {
            $persons[] = $result->getPerson();
        }

        return $persons;
    }
}
