<?php

namespace CommonBundle\Repository\General;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * Address
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Address extends EntityRepository
{
}
