<?php

namespace CommonBundle\Repository\Users;

use Doctrine\ORM\EntityRepository;

/**
 * Code
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Code extends EntityRepository
{
}