<?php

namespace CommonBundle\Repository\Users;

use Doctrine\ORM\EntityRepository;

/**
 * Session
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Session extends EntityRepository
{
    public function findAllExpired()
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('s')
            ->from('CommonBundle\Entity\Users\Session', 's')
            ->where(
                $query->expr()->lt('s.expirationTime', ':expirationTime')
            )
            ->setParameter('expirationTime', new \DateTime('now'));
            
        return $query->getQuery()->getResult();
    }
}
