<?php

namespace ProfBundle\Repository\Action\Article;

use CommonBundle\Entity\Users\Person,
    Doctrine\ORM\EntityRepository;

/**
 * Add
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Add extends EntityRepository
{
    public function findAllByPerson(Person $person)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('a')
        	->from('ProfBundle\Entity\Action\Article\Add', 'a')
        	->where(
        	    $query->expr()->eq('a.person', ':person')
            )
        	->setParameter('person', $person->getId())
        	->orderBy('a.createTime', 'DESC')
        	->getQuery()
        	->getResult();
        
        return $resultSet;
    }
}