<?php

namespace FormBundle\Repository\Field;

use Doctrine\ORM\EntityRepository;

/**
 * Checkbox
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Checkbox extends EntityRepository
{
}
