<?php

namespace FormBundle\Repository\Field;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * OptionSelector
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionSelector extends EntityRepository
{
}
