<script language=javascript>
var pollstring = "";

function pollUpdate() {
	$.get('<?= $this->url(array( 'controller' => 'queue', 'action' => 'poll' )); ?>', function (data) {
		// compare poll string
		if( data != pollstring ) {
			pollstring = data;
			$('#dumplist_signed_in').load( '<?= $this->url( array( 	'action' => 'dump',
									'session' => $sessionId ) ); ?>/status/signed_in' );
			$('#dumplist_collecting').load( '<?= $this->url( array( 	'action' => 'dump',
									'session' => $sessionId ) ); ?>/status/collecting' );
			$('#dumplist_collected').load( '<?= $this->url( array( 	'action' => 'dump',
									'session' => $sessionId ) ); ?>/status/collected' );
			$('#dumplist_selling').load( '<?= $this->url( array( 	'action' => 'dump',
									'session' => $sessionId ) ); ?>/status/selling' );
		}
	});

	window.setTimeout( "pollUpdate()", 2000 );
}

$(document).ready( pollUpdate() );
</script>

<div class=content>
<div class=container>
<div class=row>
<div class="span4">
<div class="queue_item queue_item_header">
<strong>Signed In</strong>
</div>
<div id="dumplist_signed_in">
</div>
</div>
<div class="span4">
<div class="queue_item queue_item_header">
<strong>Collecting</strong>
</div>
<div id="dumplist_collecting">
</div>
</div>
<div class="span4">
<div class="queue_item queue_item_header">
<strong>Collected</strong>
</div>
<div id="dumplist_collected">
</div>
</div>
<div class="span4">
<div class="queue_item queue_item_header">
<strong>Selling</strong>
</div>
<div id="dumplist_selling">
</div>
</div>
</div>
</div>
</div>

