<header id="controller_header">
    <div class="title"><span class="companies">24h-Run</span></div>

    <nav id="controller_nav">
        <ul>
            <? if ($this->hasAccess('admin', 'run', 'queue')): ?>
                <li><a <? if('queue' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->url(array('action' => 'queue')); ?>">Queue</a></li>
            <? endif; ?>
            <? if ($this->hasAccess('admin', 'run', 'groups')): ?>
                <li><a <? if('groups' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->url(array('action' => 'groups')); ?>">Groups</a></li>
            <? endif; ?>
        </ul>
    </nav>
</header>