<header id="controller_header">
    <div class="title"><span class="users">Users</span></div>

    <nav id="controller_nav">
        <ul>
            <? if ($this->plugin('hasaccess')->direct('admin', 'user', 'add')): ?>
                <li><a <? if('add' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->plugin('url')->direct(array('action' => 'add')); ?>">Add</a></li>
            <? endif; ?>
            <? if ($this->plugin('hasaccess')->direct('admin', 'user', 'manage')): ?>
                <li><a <? if('manage' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->plugin('url')->direct(array('action' => 'manage')); ?>">Manage</a></li>
            <? endif; ?>
        </ul>
    </nav>
</header>