<?php

namespace CudiBundle\Repository\Sale;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * PayDesk
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayDesk extends EntityRepository
{
}
