<?php

namespace CudiBundle\Repository\Sale;

use CommonBundle\Component\Util\AcademicYear as AcademicYearUtil;
use CommonBundle\Entity\General\AcademicYear;
use CommonBundle\Entity\General\Bank\CashRegister;
use CommonBundle\Entity\General\Organization;
use CudiBundle\Entity\Sale\Session as SessionEntity;
use DateTime;

/**
 * Session
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Session extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @param  CashRegister $cashRegister
     * @return \CudiBundle\Entity\Sale\Session|null
     */
    public function findOneByCashRegister(CashRegister $cashRegister)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s')
            ->from('CudiBundle\Entity\Sale\Session', 's')
            ->where(
                $query->expr()->orX(
                    $query->expr()->eq('s.openRegister', ':register'),
                    $query->expr()->eq('s.closeRegister', ':register')
                )
            )
            ->setParameter('register', $cashRegister->getId())
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param  AcademicYear      $academicYear
     * @param  Organization|null $organization
     * @return array
     */
    private function personsByAcademicYearAndOrganization(AcademicYear $academicYear, Organization $organization = null)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        $resultSet = $query->select('p.id')
            ->from('CommonBundle\Entity\User\Person\Organization\AcademicYearMap', 'm')
            ->innerJoin('m.academic', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('m.organization', ':organization'),
                    $query->expr()->eq('m.academicYear', ':academicYear')
                )
            )
            ->setParameter('organization', $organization)
            ->setParameter('academicYear', $academicYear)
            ->getQuery()
            ->getResult();

        $ids = array(0);
        foreach ($resultSet as $item) {
            $ids[] = $item['id'];
        }

        return $ids;
    }

    /**
     * @param  SessionEntity     $session
     * @param  Organization|null $organization
     * @return integer
     */
    public function getTheoreticalRevenue(SessionEntity $session, Organization $organization = null)
    {
        if ($organization !== null) {
            $session->setEntityManager($this->getEntityManager());

            $ids = $this->personsByAcademicYearAndOrganization($session->getAcademicYear(), $organization);

            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet = $query->select('SUM(s.price)')
                ->from('CudiBundle\Entity\Sale\SaleItem', 's')
                ->innerJoin('s.queueItem', 'q')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->in('q.person', $ids),
                        $query->expr()->eq('s.session', ':session')
                    )
                )
                ->setParameter('session', $session->getId())
                ->getQuery()
                ->getSingleScalarResult();

            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet -= $query->select('SUM(s.price)')
                ->from('CudiBundle\Entity\Sale\ReturnItem', 's')
                ->innerJoin('s.queueItem', 'q')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->in('q.person', $ids),
                        $query->expr()->eq('s.session', ':session')
                    )
                )
                ->setParameter('session', $session->getId())
                ->getQuery()
                ->getSingleScalarResult();
        } else {
            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet = $query->select('SUM(s.price)')
                ->from('CudiBundle\Entity\Sale\SaleItem', 's')
                ->where(
                    $query->expr()->eq('s.session', ':session')
                )
                ->setParameter('session', $session->getId())
                ->getQuery()
                ->getSingleScalarResult();

            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet -= $query->select('SUM(s.price)')
                ->from('CudiBundle\Entity\Sale\ReturnItem', 's')
                ->where(
                    $query->expr()->eq('s.session', ':session')
                )
                ->setParameter('session', $session->getId())
                ->getQuery()
                ->getSingleScalarResult();
        }

        if ($resultSet === null) {
            $resultSet = 0;
        }

        return (int) $resultSet;
    }

    /**
     * @param  AcademicYear      $academicYear
     * @param  Organization|null $organization
     * @return integer
     */
    public function getTheoreticalRevenueByAcademicYear(AcademicYear $academicYear, Organization $organization = null)
    {
        return $this->getTheoreticalRevenueBetween($academicYear->getUniversityStartDate(), $academicYear->getUniversityEndDate(), $organization);
    }

    /**
     * @param  DateTime          $startDate
     * @param  DateTime          $endDate
     * @param  Organization|null $organization
     * @return integer
     */
    public function getTheoreticalRevenueBetween(DateTime $startDate, DateTime $endDate, Organization $organization = null)
    {
        if ($organization !== null) {
            $academicYear = AcademicYearUtil::getUniversityYear($this->getEntityManager(), $startDate);

            $ids = $this->personsByAcademicYearAndOrganization($academicYear, $organization);

            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet = $query->select('SUM(s.price)')
                ->from('CudiBundle\Entity\Sale\SaleItem', 's')
                ->innerJoin('s.session', 'e')
                ->innerJoin('s.queueItem', 'q')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->in('q.person', $ids),
                        $query->expr()->gt('e.openDate', ':start'),
                        $query->expr()->lt('e.openDate', ':end')
                    )
                )
                ->setParameter('start', $startDate)
                ->setParameter('end', $endDate)
                ->getQuery()
                ->getSingleScalarResult();

            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet -= $query->select('SUM(s.price)')
                ->from('CudiBundle\Entity\Sale\ReturnItem', 's')
                ->innerJoin('s.session', 'e')
                ->innerJoin('s.queueItem', 'q')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->in('q.person', $ids),
                        $query->expr()->gt('e.openDate', ':start'),
                        $query->expr()->lt('e.openDate', ':end')
                    )
                )
                ->setParameter('start', $startDate)
                ->setParameter('end', $endDate)
                ->getQuery()
                ->getSingleScalarResult();
        } else {
            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet = $query->select('SUM(s.price)')
                ->from('CudiBundle\Entity\Sale\SaleItem', 's')
                ->innerJoin('s.session', 'e')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->gt('e.openDate', ':start'),
                        $query->expr()->lt('e.openDate', ':end')
                    )
                )
                ->setParameter('start', $startDate)
                ->setParameter('end', $endDate)
                ->getQuery()
                ->getSingleScalarResult();

            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet -= $query->select('SUM(s.price)')
                ->from('CudiBundle\Entity\Sale\ReturnItem', 's')
                ->innerJoin('s.session', 'e')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->gt('e.openDate', ':start'),
                        $query->expr()->lt('e.openDate', ':end')
                    )
                )
                ->setParameter('start', $startDate)
                ->setParameter('end', $endDate)
                ->getQuery()
                ->getSingleScalarResult();
        }

        if ($resultSet === null) {
            $resultSet = 0;
        }

        return (int) $resultSet;
    }

    /**
     * @param  SessionEntity     $session
     * @param  Organization|null $organization
     * @return integer
     */
    public function getPurchasedAmountBySession(SessionEntity $session, Organization $organization = null)
    {
        if ($organization !== null) {
            $session->setEntityManager($this->getEntityManager());

            $ids = $this->personsByAcademicYearAndOrganization($session->getAcademicYear(), $organization);

            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet = $query->select('SUM(s.purchasePrice)')
                ->from('CudiBundle\Entity\Sale\SaleItem', 's')
                ->innerJoin('s.queueItem', 'q')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->in('q.person', $ids),
                        $query->expr()->eq('s.session', ':session')
                    )
                )
                ->setParameter('session', $session->getId())
                ->getQuery()
                ->getSingleScalarResult();
        } else {
            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet = $query->select('SUM(s.purchasePrice)')
                ->from('CudiBundle\Entity\Sale\SaleItem', 's')
                ->where(
                    $query->expr()->eq('s.session', ':session')
                )
                ->setParameter('session', $session->getId())
                ->getQuery()
                ->getSingleScalarResult();
        }

        if ($resultSet === null) {
            $resultSet = 0;
        }

        return $resultSet;
    }

    /**
     * @param  AcademicYear      $academicYear
     * @param  Organization|null $organization
     * @return integer
     */
    public function getPurchasedAmountByAcademicYear(AcademicYear $academicYear, Organization $organization = null)
    {
        return $this->getPurchasedAmountBetween($academicYear->getUniversityStartDate(), $academicYear->getUniversityEndDate(), $organization);
    }

    /**
     * @param  DateTime          $startDate
     * @param  DateTime          $endDate
     * @param  Organization|null $organization
     * @return integer
     */
    public function getPurchasedAmountBetween(DateTime $startDate, DateTime $endDate, Organization $organization = null)
    {
        if ($organization !== null) {
            $academicYear = AcademicYearUtil::getUniversityYear($this->getEntityManager(), $startDate);

            $ids = $this->personsByAcademicYearAndOrganization($academicYear, $organization);

            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet = $query->select('SUM(s.purchasePrice)')
                ->from('CudiBundle\Entity\Sale\SaleItem', 's')
                ->innerJoin('s.session', 'e')
                ->innerJoin('s.queueItem', 'q')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->in('q.person', $ids),
                        $query->expr()->gt('e.openDate', ':start'),
                        $query->expr()->lt('e.openDate', ':end')
                    )
                )
                ->setParameter('start', $startDate)
                ->setParameter('end', $endDate)
                ->getQuery()
                ->getSingleScalarResult();
        } else {
            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet = $query->select('SUM(s.purchasePrice)')
                ->from('CudiBundle\Entity\Sale\SaleItem', 's')
                ->innerJoin('s.session', 'e')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->gt('e.openDate', ':start'),
                        $query->expr()->lt('e.openDate', ':end')
                    )
                )
                ->setParameter('start', $startDate)
                ->setParameter('end', $endDate)
                ->getQuery()
                ->getSingleScalarResult();
        }

        if ($resultSet === null) {
            $resultSet = 0;
        }

        return $resultSet;
    }

    /**
     * @return \CudiBundle\Entity\Sale\Session|null
     */
    public function getLast()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s')
            ->from('CudiBundle\Entity\Sale\Session', 's')
            ->orderBy('s.openDate', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param  DateTime $date
     * @return \CudiBundle\Entity\Sale\Session|null
     */
    public function findOnebyDate(DateTime $date)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s')
            ->from('CudiBundle\Entity\Sale\Session', 's')
            ->where(
                $query->expr()->andX(
                    $query->expr()->lte('s.openDate', ':now'),
                    $query->expr()->gte('s.closeDate', ':now')
                )
            )
            ->setParameter('now', $date)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function findOpenQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s')
            ->from('CudiBundle\Entity\Sale\Session', 's')
            ->where(
                $query->expr()->isNull('s.closeDate')
            )
            ->orderBy('s.openDate', 'DESC')
            ->getQuery();
    }

    /**
     * @param  AcademicYear $academicYear
     * @return \Doctrine\ORM\Query
     */
    public function findAllByAcademicYearQuery(AcademicYear $academicYear)
    {
        return $this->findAllBetweenQuery($academicYear->getUniversityStartDate(), $academicYear->getUniversityEndDate());
    }

    /**
     * @param  DateTime $startDate
     * @param  DateTime $endDate
     * @return \Doctrine\ORM\Query
     */
    public function findAllBetweenQuery(DateTime $startDate, DateTime $endDate)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s')
            ->from('CudiBundle\Entity\Sale\Session', 's')
            ->where(
                $query->expr()->andX(
                    $query->expr()->gt('s.openDate', ':start'),
                    $query->expr()->lt('s.openDate', ':end')
                )
            )
            ->setParameter('start', $startDate)
            ->setParameter('end', $endDate)
            ->getQuery();
    }
}
