<?php

namespace Litus\Repository\Cudi\Sales;

use Doctrine\ORM\EntityRepository;

/**
 * SaleSession
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleSession extends EntityRepository
{
}