<?php

namespace Litus\Repository\Cudi\Sales;

use Doctrine\ORM\EntityRepository;

/**
 * ServingQueueItem
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServingQueueItem extends EntityRepository
{

    private $_cache;

    public function getQueueNumber( $sessionId ) {

        if( isset( $_cache[$sessionId] ) )
            return $_cache[$sessionId];
    
        $query = $this->createQueryBuilder("qi");
        $query->select( "COUNT(qi)" )
              ->where( "qi.session = '".$sessionId."'");

        $result = $query->getQuery()->getResult();
        $count = $result[0][1];

        $_cache[$sessionId] = $count + 1;

        return $count + 1;
    }

}
