<?php

namespace MailBundle\Repository;

use CommonBundle\Entity\User\Person\Academic,
    Doctrine\ORM\EntityRepository;

/**
 * Alias
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Alias extends EntityRepository
{
    public function findByAliasName($name)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('p')
            ->from('MailBundle\Entity\Alias','p')
            ->where(
                $query->expr()->like('p.name', ':name')
            )
            ->setParameter('name', '%' . strtolower($name) . '%')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }

    public function searchByAcademic(Academic $academic)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('p')
            ->from('MailBundle\Entity\Alias\Academic','p')
            ->where(
                $query->expr()->like('p.academic', ':academic')
            )
            ->setParameter('academic', '%' . strtolower($academic) . '%')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }
}
