<?php

namespace MailBundle\Repository;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * MailingList
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailingList extends EntityRepository
{
}
