<?php

namespace MailBundle\Repository;

use CommonBundle\Component\Util\EntityRepository;

/**
 * MailingList
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailingList extends EntityRepository
{
    public function findAllByNameQuery($name)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('l')
            ->from('MailBundle\Entity\MailingList\Named','l')
            ->where(
                $query->expr()->like($query->expr()->lower('l.name'), ':name')
            )
            ->setParameter('name', '%' . strtolower($name) . '%')
            ->getQuery();

        return $resultSet;
    }
}
