<?php

/**
 * Section
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
namespace MailBundle\Repository;

class Section extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    public function findAllByNameQuery($name)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('a')
            ->from('MailBundle\Entity\Section', 'a')
            ->where(
                $query->expr()->like('a.name', ':name')
            )
            ->setParameter('name', '%' . strtolower($name) . '%')
            ->getQuery();
    }
}