<?php

namespace CudiBundle\Repository\Articles\StockArticles;

use Doctrine\ORM\EntityRepository;

/**
 * Internal
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Internal extends EntityRepository
{
     public function findOneByBarcode($barcode)
    {
        if (strlen($barcode) == 13)
            $barcode = floor($barcode / 10);
        echo 'dsf';
		$query = $this->_em->createQueryBuilder();
		$resultSet = $query->select('s')
			->from('CudiBundle\Entity\Articles\StockArticles\Internal', 's')
			->where($query->expr()->eq('s.barcode', ':barcode'))
			->setParameter('barcode', $barcode)
			->setMaxResults(1)
			->getQuery()
			->getResult();
		
		if (isset($resultSet[0]))
            return $resultSet[0];

        return null;
    }
}