<header id="controller_header">
    <div class="title"><span class="companies">Companies</span></div>

    <nav id="controller_nav">
        <ul>
            <? if ($this->hasAccess('admin', 'company', 'add')): ?>
                <li><a <? if('add' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->url(array('action' => 'add')); ?>">Add</a></li>
            <? endif; ?>
        </ul>
    </nav>
</header>