<?php

namespace MailBundle\Repository\MailingList\Entry;

use Doctrine\ORM\EntityRepository;

/**
 * MailingList
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailingList extends EntityRepository
{
}
