<?php

namespace CommonBundle\Repository\Acl;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * Action
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Action extends EntityRepository
{
}
