<?php

namespace CommonBundle\Repository\Acl;

use CommonBundle\Component\Util\EntityRepository;

/**
 * Role
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Role extends EntityRepository
{
}
