<?= $this->partial('partials/company/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="controller_action">
    <? if ($this->companyCreated): ?>
        <div class="success_message">
            <div class="title">Success</div>
            <div class="content">
                <p>The company was successfully created!</p>
            </div>
        </div>
    <? endif; ?>

    <?= $this->form; ?>
</div>

<aside>
    <div class="sidebox">
        <div class="title">Note</div>
        <div class="content">
            Please keep in mind that you are creating a new <b>contact</b> for a certain company. This contact
            will have privileges in some areas of our website and as such requires credentials.
        </div>
    </div>
</aside>