<?= $this->broker('partial')->direct('company/partials/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="controller_action">
    <? if (!$this->companyCreated): ?>
        <? if(isset($this->error)): ?>
            <span class="error_message"><?= $this->error; ?></span>
        <? endif; ?>

        <i>
            Note: Please keep in mind that you are creating a new <b>contact</b> for a certain company. This contact
            will have privileges in some areas of our website and as such requires credentials.
        </i>
        <?= $this->form; ?>
    <? else: ?>
        <span class="success_message">The company was successfully created!</span>
    <? endif; ?>
</div>