version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily

    ignore:
      - dependency-name: twitter/bootstrap
        versions:
          - "> 3.4.1"
