version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily

    ignore:
      - dependency-name: symfony/event-dispatcher
        versions:
          - ^5.0
      - dependency-name: twitter/bootstrap
        versions:
          - ^4.0

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
