<?= $this->partial('partials/user/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="controller_action">
    <? if ($this->userCreated): ?>
        <div class="success_message">
            <div class="title">Success</div>
            <div class="content">
                <p>The user was successfully created!</p>
            </div>
        </div>
    <? endif; ?>

    <?= $this->form; ?>
</div>