<?= $this->partial('partials/user/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <? foreach($this->flashMessages as $message) { echo $message; } ?>

    <div class="error_message full_width">
        <div class="title">Warning</div>
        <div class="content">
            <p>
                You are about to delete the following user: <b><?= $this->user->getUsername(); ?></b> (<?= $this->user->getFullName(); ?>)?
                Please note that this operation cannot be undone!
            </p>

            <p>
                Are you sure you want to continue?<br />
                <a href="<?= $this->url(array('confirm' => '1')); ?>">Yes</a>
                <a href="<?= $this->url(array('confirm' => '0')); ?>">No</a>
            </p>
        </div>
    </div>
</div>