<?= $this->partial('partials/user/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <div class="error_message">
        <div class="title">Warning</div>
        <div class="content">
            <? if ($this->userDeleted): ?>
                <p>The user was successfully deleted.</p>
            <? else: ?>
                <p>
                    You are about to delete the following user: <b><?= $this->user->getUsername(); ?></b> (<?= $this->user->getFirstName(); ?> <?= $this->user->getLastName(); ?>)?
                    Please note that this operation cannot be undone!
                </p>

                <p>
                    Are you sure you want to continue?<br />
                    <a href="<?= $this->url(array('confirm' => '1')); ?>">Yes</a>
                    <a href="<?= $this->url(array('confirm' => '0')); ?>">No</a>
                </p>
            <? endif; ?>
        </div>
    </div>
</div>