<?php

namespace Litus\Repository\Acl;

use Doctrine\ORM\EntityRepository;

/**
 * Action
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Action extends EntityRepository
{
}