<?php

namespace FormBundle\Repository;

use DateTime,
    Doctrine\ORM\EntityRepository;

/**
 * FormField
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormField extends EntityRepository
{
    public function findAll()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('n')
            ->from('FormBundle\Entity\FormField', 'n')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }
}
