<?php

namespace FormBundle\Repository;

use DateTime,
    Doctrine\ORM\EntityRepository;

/**
 * Viewermap
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewerMap extends EntityRepository
{
    public function findAll()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('n')
            ->from('FormBundle\Entity\ViewerMap', 'n')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }

    public function findOneById($id) {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('n')
            ->from('FormBundle\Entity\ViewerMap', 'n')
            ->where(
                $query->expr()->eq('n.id', ':id')
            )
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        if (isset($resultSet[0]))
            return $resultSet[0];

        return null;
    }

    public function findAllByForm($formId) {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('n')
            ->from('FormBundle\Entity\ViewerMap', 'n')
            ->where(
                $query->expr()->eq('n.form', ':id')
            )
            ->setParameter('id', $formId)
            ->getQuery()
            ->getResult();

        return $resultSet;
    }
}
