language: php
services:
    - mongodb
    - redis-server

node_js:
    - node
php:
    - 7.2

cache:
    apt: true
    directories:
        - $HOME/.composer/cache/
        - phpcs/
        - phpstan/
        - vendor/

before_install:
    - yes | pecl install -f igbinary
    - yes | pecl install -f imagick
    - yes | pecl install -f mailparse
    - yes | pecl install -f redis
    - phpenv config-add travis/config/php.ini
install:
    - travis/bin/install.sh

script: travis/bin/test.sh $LITUS_TEST
env:
    - LITUS_TEST=analyze
    - LITUS_TEST=install
