language: php
node_js:
    - node
php:
    - 7.2

services:
    - mongodb

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
    - LITUS_TEST=install
    - LITUS_TEST=codestyle

before_install: phpenv config-add travis/config/php.ini

install: travis/bin/install.sh

script: travis/bin/test.sh $LITUS_TEST
