version: "3.7"

volumes:
  assetic:
    driver: local

  postgres:
    driver: local

services:
  litus:
    image: litusproject/litus:latest
    build:
      context: .
    environment:
      LITUS_DATABASE_HOST: postgres
      LITUS_DATABASE_USER: litus
      LITUS_DATABASE_PASSWORD: huQeyU8te3aXusaz
      LITUS_DATABASE_DBNAME: litus

      LITUS_REDIS_HOST: redis
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - assetic:/app/public/_assetic
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: litus
      POSTGRES_PASSWORD: huQeyU8te3aXusaz
      POSTGRES_DB: litus
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped
