<?php

namespace CudiBundle\Repository\Articles;

use CudiBundle\Entity\Article,
    Doctrine\ORM\EntityRepository;

/**
 * Comment
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Comment extends EntityRepository
{
    public function findAllByArticle(Article $article)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('c')
        	->from('CudiBundle\Entity\Articles\Comment', 'c')
        	->where(
        	    $query->expr()->eq('c.article', ':article')
        	)
        	->setParameter('article', $article->getId())
        	->orderBy('c.date', 'DESC')
        	->getQuery()
        	->getResult();
        	
        return $resultSet;
    }
    
    public function findAllByArticleAndType(Article $article, $type)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('c')
        	->from('CudiBundle\Entity\Articles\Comment', 'c')
        	->where(
        	    $query->expr()->andX(
        	        $query->expr()->eq('c.article', ':article'),
        	        $query->expr()->eq('c.type', ':type')
        	    )
        	)
        	->setParameter('article', $article->getId())
        	->setParameter('type', $type)
        	->orderBy('c.date', 'DESC')
        	->getQuery()
        	->getResult();
        	
        return $resultSet;
    }
}