<?= $this->broker('partial')->direct('acl/partials/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="controller_action">
    <? if (!$this->roleCreated): ?>
    <?= $this->form; ?>
    <? else: ?>
    <span class="success_message">The role was successfully created!</span>
    <? endif; ?>
</div>

<aside>
    <div class="sidebox">
        <div class="title">Current Rights</div>
        <div class="content">
            Lorem<br />
            Lorem<br />
            Lorem<br />
            Lorem<br />
            Lorem<br />
            Lorem<br />
            Lorem<br />
            Lorem<br />
            Lorem<br />
            Lorem
        </div>
    </div>
</aside>