<?php

namespace CommonBundle\Repository\Users\Statuses;

use Doctrine\ORM\EntityRepository;

/**
 * Union
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Union extends EntityRepository
{
}