<?php

return array(
    'Logistics'                                                                                                                                                                                                                                 => 'Logistics',
    'Van'                                                                                                                                                                                                                                       => 'Van',

    'January'                                                                                                                                                                                                                                   => 'January',
    'February'                                                                                                                                                                                                                                  => 'February',
    'March'                                                                                                                                                                                                                                     => 'March',
    'April'                                                                                                                                                                                                                                     => 'April',
    'May'                                                                                                                                                                                                                                       => 'May',
    'June'                                                                                                                                                                                                                                      => 'June',
    'July'                                                                                                                                                                                                                                      => 'July',
    'August'                                                                                                                                                                                                                                    => 'August',
    'September'                                                                                                                                                                                                                                 => 'September',
    'October'                                                                                                                                                                                                                                   => 'October',
    'November'                                                                                                                                                                                                                                  => 'November',
    'December'                                                                                                                                                                                                                                  => 'December',
    'Jan'                                                                                                                                                                                                                                       => 'Jan',
    'Feb'                                                                                                                                                                                                                                       => 'Feb',
    'Mar'                                                                                                                                                                                                                                       => 'Mar',
    'Apr'                                                                                                                                                                                                                                       => 'Apr',
    'Jun'                                                                                                                                                                                                                                       => 'Jun',
    'Jul'                                                                                                                                                                                                                                       => 'Jul',
    'Aug'                                                                                                                                                                                                                                       => 'Aug',
    'Sep'                                                                                                                                                                                                                                       => 'Sep',
    'Oct'                                                                                                                                                                                                                                       => 'Oct',
    'Nov'                                                                                                                                                                                                                                       => 'Nov',
    'Dec'                                                                                                                                                                                                                                       => 'Dec',
    'Sunday'                                                                                                                                                                                                                                    => 'Sunday',
    'Monday'                                                                                                                                                                                                                                    => 'Monday',
    'Tuesday'                                                                                                                                                                                                                                   => 'Tuesday',
    'Wednesday'                                                                                                                                                                                                                                 => 'Wednesday',
    'Thursday'                                                                                                                                                                                                                                  => 'Thursday',
    'Friday'                                                                                                                                                                                                                                    => 'Friday',
    'Saturday'                                                                                                                                                                                                                                  => 'Saturday',
    'Sun'                                                                                                                                                                                                                                       => 'Sun',
    'Mon'                                                                                                                                                                                                                                       => 'Mon',
    'Tue'                                                                                                                                                                                                                                       => 'Tue',
    'Wed'                                                                                                                                                                                                                                       => 'Wed',
    'Thu'                                                                                                                                                                                                                                       => 'Thu',
    'Fri'                                                                                                                                                                                                                                       => 'Fri',
    'Sat'                                                                                                                                                                                                                                       => 'Sat',
    'today'                                                                                                                                                                                                                                     => 'today',
    'month'                                                                                                                                                                                                                                     => 'month',
    'week'                                                                                                                                                                                                                                      => 'week',
    'day'                                                                                                                                                                                                                                       => 'day',

    'Start Date'                                                                                                                                                                                                                                => 'Start Date',
    'End Date'                                                                                                                                                                                                                                  => 'End Date',
    'Reason'                                                                                                                                                                                                                                    => 'Reason',
    'Load'                                                                                                                                                                                                                                      => 'Load',
    'Additional Information'                                                                                                                                                                                                                    => 'Additional Information',
    'Driver'                                                                                                                                                                                                                                    => 'Driver',
    'Passenger'                                                                                                                                                                                                                                 => 'Passenger',
    'Car'                                                                                                                                                                                                                                       => 'Car',
    'Add'                                                                                                                                                                                                                                       => 'Add',
    'New Reservation'                                                                                                                                                                                                                           => 'New Reservation',
    'Edit Reservation'                                                                                                                                                                                                                          => 'Edit Reservation',

    'There was an error while loading the reservations.'                                                                                                                                                                                        => 'There was an error while loading the reservations.',
    'There was an error while deleting the reservation.'                                                                                                                                                                                        => 'There was an error while deleting the reservation.',
    'The reservation was successfully removed.'                                                                                                                                                                                                 => 'The reservation was successfully removed.',
    'There was an error while adding the reservation.'                                                                                                                                                                                          => 'There was an error while adding the reservation.',
    'The reservation was successfully added.'                                                                                                                                                                                                   => 'The reservation was successfully added.',
    'There was an error while updating the reservation.'                                                                                                                                                                                        => 'There was an error while updating the reservation.',
    'The reservation was successfully updated.'                                                                                                                                                                                                 => 'The reservation was successfully updated.',

    'Piano'                                                                                                                                                                                                                                     => 'Piano',
    'Reservations'                                                                                                                                                                                                                              => 'Reservations',
    'Confirmed'                                                                                                                                                                                                                                 => 'Confirmed',
    'The reservation was succesfully created!'                                                                                                                                                                                                  => 'The reservation was succesfully created!',
    'Book'                                                                                                                                                                                                                                      => 'Book',

    '<p>For the culture lovers who didn\'t know it, VTK has its own piano! You can find it in room 01.52 (next to the proclamation hall) of the castle. Students can make weekly use of it for free and on the following time slots:<p>

        <ul>
            <li>every Monday, Tuesday and Thursday evening from 19h until 22h from week 39 until 21, except official closing days of the KU Leuven</li>
            <li>all workdays between 9h and 18h in the Christmas and Easter holidays, except official closing days of KU Leuven</li>
            <li>all workdays between 9h and 18h in July (from week 28) and August, except official closing days of KU Leuven</li>
        </ul>

        <p>Choose a moment you want to play music below, and reserve it! One reservation each week will be assigned to you, if you want to play more times a week, other students are given priority.</p>

        <p>It is important you always have the accompanying letter with you if you are going to play. You can get this in Blok 6 (Studentenwijk Arenberg) from the vice. You should be able to show this letter when security asks for it.</p>' => '<p>For the culture lovers who didn\'t know it, VTK has its own piano! You can find it in room 01.52 (next to the proclamation hall) of the castle. Students can make weekly use of it for free and on the following time slots:<p>

        <ul>
            <li>every Monday, Tuesday and Thursday evening from 19h until 22h from week 39 until 21, except official closing days of the KU Leuven</li>
            <li>all workdays between 9h and 18h in the Christmas and Easter holidays, except official closing days of KU Leuven</li>
            <li>all workdays between 9h and 18h in July (from week 28) and August, except official closing days of KU Leuven</li>
        </ul>

        <p>Choose a moment you want to play music below, and reserve it! One reservation each week will be assigned to you, if you want to play more times a week, other students are given priority.</p>

        <p>It is important you always have the accompanying letter with you if you are going to play. You can get this in Blok 6 (Studentenwijk Arenberg) from the vice. You should be able to show this letter when security asks for it.</p>',
    'Please login to reserve a slot.'                                                                                                                                                                                                           => 'Please login to reserve a slot.',

    'Lease'                                                                                                                                                                                                                                     => 'Lease',
    'Return'                                                                                                                                                                                                                                    => 'Return',
    'Leases'                                                                                                                                                                                                                                    => 'Leases',
    'Item Name'                                                                                                                                                                                                                                 => 'Item Name',
    'Barcode'                                                                                                                                                                                                                                   => 'Barcode',
    'Amount'                                                                                                                                                                                                                                    => 'Amount',
    'Leased To'                                                                                                                                                                                                                                 => 'Leased To',
    'Leased On'                                                                                                                                                                                                                                 => 'Leased On',
    'Pawn'                                                                                                                                                                                                                                      => 'Pawn',
    'Received Pawn'                                                                                                                                                                                                                             => 'Received Pawn',
    'Returned Pawn'                                                                                                                                                                                                                             => 'Returned Pawn',
    'Actions'                                                                                                                                                                                                                                   => 'Actions',
    'Details'                                                                                                                                                                                                                                   => 'Details',
    'Item Search'                                                                                                                                                                                                                               => 'Item Search',
    'Search'                                                                                                                                                                                                                                    => 'Search',
    'Lease History'                                                                                                                                                                                                                             => 'Lease History',
    'Returned By'                                                                                                                                                                                                                               => 'Returned By',
    'Additional Info'                                                                                                                                                                                                                           => 'Additional Info',
    'Leased'                                                                                                                                                                                                                                    => 'Leased',
    'From'                                                                                                                                                                                                                                      => 'From',
    'To'                                                                                                                                                                                                                                        => 'To',
    'Date'                                                                                                                                                                                                                                      => 'Date',
    'Comment'                                                                                                                                                                                                                                   => 'Comment',
    'Returned'                                                                                                                                                                                                                                  => 'Returned',
    'Not Yet Returned'                                                                                                                                                                                                                          => 'Not Yet Returned',
    'Request'                                                                                                                                                                                                                                   => 'Request',
    'Pending'                                                                                                                                                                                                                                   => 'Pending',
    'Creator'                                                                                                                                                                                                                                   => 'Creator',
    'History'                                                                                                                                                                                                                                   => 'History',

    'The lease was successfully added!'                                                                                                                                                                                                         => 'The lease was successfully added!',
    'The return was successfully added!'                                                                                                                                                                                                        => 'The return was successfully added!',
    'No id was given to identify the lease!'                                                                                                                                                                                                    => 'No id was given to identify the lease!',
    'No lease with the given id was found!'                                                                                                                                                                                                     => 'No lease with the given id was found!',
    'No id or barcode was given to identify the item!'                                                                                                                                                                                          => 'No id or barcode was given to identify the item!',
    'No item with the given id or barcode was found!'                                                                                                                                                                                           => 'No item with the given id or barcode was found!',

    'General'                                                                                                                                                                                                                                   => 'General',
    'Personal'                                                                                                                                                                                                                                  => 'Personal',

    'Article Name'                                                                                                                                                                                                                              => 'Article Name',
    'Order Name'                                                                                                                                                                                                                                => 'Order Name',
    'Material'                                                                                                                                                                                                                                  => 'Material',
    'Inventory'                                                                                                                                                                                                                                 => 'Inventory',
    'Flesserke Form'                                                                                                                                                                                                                            => 'Inventory Form',
    'Reserve'                                                                                                                                                                                                                                   => 'Reserve',
);
