<?php

namespace CudiBundle\Repository;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * Log
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Log extends EntityRepository
{
    public function findBookingLogsQuery()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('l')
            ->from('CudiBundle\Entity\Log', 'l')
            ->where(
                $query->expr()->orX(
                    'l INSTANCE OF :assignments',
                    'l INSTANCE OF :cancellations'
                )
            )
            ->setParameter('assignments', $this->_em->getMetadataFactory()->getMetadataFor('CudiBundle\Entity\Log\Sale\Assignments'))
            ->setParameter('cancellations', $this->_em->getMetadataFactory()->getMetadataFor('CudiBundle\Entity\Log\Sale\Cancellations'))
            ->orderBy('l.timestamp', 'DESC')
            ->getQuery();

        return $resultSet;
    }
}
