<?php

namespace BrBundle\Repository\Invoice;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceEntry
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceEntry extends EntityRepository
{
}
