<?php

namespace CommonBundle\Repository\General;

use Doctrine\ORM\EntityRepository;

/**
 * AcademicYear
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicYear extends EntityRepository
{
}