<?php

namespace BrBundle\Repository\Product;

use BrBundle\Entity\Product,
    BrBundle\Entity\Product\Order,
    Doctrine\ORM\EntityRepository;

/**
 * OrderEntry
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderEntry extends EntityRepository
{
    public function findOneByOrderAndProduct(Order $order, Product $product) {

        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('o')
            ->from('BrBundle\Entity\Product\OrderEntry', 'o')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('o.order', ':order'),
                    $query->expr()->eq('o.product', ':product')
                )
            )
            ->setParameter('order', $order)
            ->setParameter('product', $product)
            ->getQuery()
            ->getResult();

        if (isset($resultSet[0]))
            return $resultSet[0];
        return null;
    }
}
