<?php

namespace BrBundle\Repository\Product;

/**
 * Order
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Order extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllNotOldUnsignedQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('o')
            ->from('BrBundle\Entity\Product\Order', 'o')
            ->leftJoin('o.contract', 'c')
            ->where(
                $query->expr()->andx(
                    $query->expr()->eq('o.old', 'false'),
                    $query->expr()->orx(
                        $query->expr()->eq('c.signed', 'false'),
                        $query->expr()->isNull('c.signed')
                    )
                )
            )
            ->orderBy('o.creationTime', 'DESC')
            ->getQuery();
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllNotOldSignedQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('o')
            ->from('BrBundle\Entity\Product\Order', 'o')
            ->innerJoin('o.contract', 'c')
            ->where(
                $query->expr()->andx(
                    $query->expr()->eq('o.old', 'false'),
                    $query->expr()->eq('c.signed', 'true')
                )
            )
            ->orderBy('o.creationTime', 'DESC')
            ->getQuery();
    }
}
