<?php

namespace CommonBundle\Repository\User;

use CommonBundle\Entity\General\AcademicYear;
use CommonBundle\Entity\General\Organization;
use CommonBundle\Entity\User\Person;
use RuntimeException;

/**
 * Barcode
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Barcode extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @param  string $barcode
     * @return \CommonBundle\Entity\User\Barcode|null
     */
    public function findOneByBarcode($barcode)
    {
        $ean12Result = null;
        if (is_numeric($barcode)) {
            $eanBarcode = $barcode;
            if (strlen($barcode) == 13) {
                $eanBarcode = floor($barcode / 10);
            }

            $query = $this->getEntityManager()->createQueryBuilder();
            $ean12Result = $query->select('b')
                ->from('CommonBundle\Entity\User\Barcode\Ean12', 'b')
                ->where(
                    $query->expr()->eq('b.barcode', ':barcode')
                )
                ->setParameter('barcode', $eanBarcode)
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();
        }

        $query = $this->getEntityManager()->createQueryBuilder();
        $qrResult = $query->select('b')
            ->from('CommonBundle\Entity\User\Barcode\Qr', 'b')
            ->where(
                $query->expr()->eq('b.barcode', ':barcode')
            )
            ->setParameter('barcode', $barcode)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        if ($ean12Result !== null && $qrResult !== null) {
            throw new RuntimeException('Found both an EAN-12 and QR code for this barcode');
        }

        return $ean12Result ?? $qrResult;
    }

    /**
     * @param  string $barcode
     * @return array
     */
    public function findAllByBarcode($barcode)
    {
        $ean12Result = array();
        if (is_numeric($barcode)) {
            $eanBarcode = $barcode;
            if (strlen($barcode) == 13) {
                $eanBarcode = floor($barcode / 10);
            }

            $query = $this->getEntityManager()->createQueryBuilder();
            $ean12Result = $query->select('b')
                ->from('CommonBundle\Entity\User\Barcode\Ean12', 'b')
                ->where(
                    $query->expr()->like($query->expr()->concat('b.barcode', '\'\''), ':barcode')
                )
                ->setParameter('barcode', strtolower($eanBarcode) . '%')
                ->getQuery()
                ->getResult();
        }

        $query = $this->getEntityManager()->createQueryBuilder();
        $qrResult = $query->select('b')
            ->from('CommonBundle\Entity\User\Barcode\Qr', 'b')
            ->where(
                $query->expr()->like($query->expr()->concat('b.barcode', '\'\''), ':barcode')
            )
            ->setParameter('barcode', strtolower($barcode) . '%')
            ->getQuery()
            ->getResult();

        return array_merge($qrResult, $ean12Result);
    }

    /**
     * @param  string       $barcode
     * @param  AcademicYear $academicYear
     * @param  Organization $organization
     * @return array
     */
    public function findAllByBarcodeAndOrganization($barcode, AcademicYear $academicYear, Organization $organization)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        $resultSet = $query->select('a.id')
            ->from('CommonBundle\Entity\User\Person\Organization\AcademicYearMap', 'm')
            ->innerJoin('m.academic', 'a')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('m.organization', ':organization'),
                    $query->expr()->eq('m.academicYear', ':academicYear')
                )
            )
            ->setParameter('organization', $organization)
            ->setParameter('academicYear', $academicYear)
            ->getQuery()
            ->getResult();

        $ids = array(0);

        foreach ($resultSet as $result) {
            $query = $this->getEntityManager()->createQueryBuilder();
            $resultSet = $query->select('a.id')
                ->from('CommonBundle\Entity\User\Person\Organization\AcademicYearMap', 'm')
                ->innerJoin('m.academic', 'a')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->eq('m.organization', ':organization'),
                        $query->expr()->eq('m.academicYear', ':academicYear')
                    )
                )
                ->setParameter('organization', $organization)
                ->setParameter('academicYear', $academicYear)
                ->getQuery()
                ->getResult();

            foreach ($resultSet as $result) {
                $ids[] = $result['id'];
            }
        }

        $ean12Result = array();
        if (is_numeric($barcode)) {
            $eanBarcode = $barcode;
            if (strlen($barcode) == 13) {
                $eanBarcode = floor($barcode / 10);
            }

            $query = $this->getEntityManager()->createQueryBuilder();
            $ean12Result = $query->select('b')
                ->from('CommonBundle\Entity\User\Barcode\Ean12', 'b')
                ->where(
                    $query->expr()->andX(
                        $query->expr()->like($query->expr()->concat('b.barcode', '\'\''), ':barcode'),
                        $query->expr()->in('b.person', $ids)
                    )
                )
                ->setParameter('barcode', strtolower($eanBarcode) . '%')
                ->getQuery()
                ->getResult();
        }

        $query = $this->getEntityManager()->createQueryBuilder();
        $qrResult = $query->select('b')
            ->from('CommonBundle\Entity\User\Barcode\Qr', 'b')
            ->where(
                $query->expr()->andX(
                    $query->expr()->like($query->expr()->concat('b.barcode', '\'\''), ':barcode'),
                    $query->expr()->in('b.person', $ids)
                )
            )
            ->setParameter('barcode', strtolower($barcode) . '%')
            ->getQuery()
            ->getResult();

        return array_merge($qrResult, $ean12Result);
    }

    /**
     * @param  Person $person
     * @return \CommonBundle\Entity\User\Barcode\Ean12|null
     */
    public function findEan12ByPerson($person)
    {
        if (!($person instanceof Person)) {
            return null;
        }

        $query = $this->getEntityManager()
            ->createQueryBuilder();

        return $query->select('b')
            ->from('CommonBundle\Entity\User\Barcode\Ean12', 'b')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('b.person', ':person')
                )
            )
            ->setParameter('person', $person->getId())
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
