<?php
/**
 * Litus is a project by a group of students from the KU Leuven. The goal is to create
 * various applications to support the IT needs of student unions.
 *
 * @author Niels Avonds <niels.avonds@litus.cc>
 * @author Karsten Daemen <karsten.daemen@litus.cc>
 * @author Koen Certyn <koen.certyn@litus.cc>
 * @author Bram Gotink <bram.gotink@litus.cc>
 * @author Dario Incalza <dario.incalza@litus.cc>
 * @author Pieter Maene <pieter.maene@litus.cc>
 * @author Kristof Mariën <kristof.marien@litus.cc>
 * @author Lars Vierbergen <lars.vierbergen@litus.cc>
 * @author Daan Wendelen <daan.wendelen@litus.cc>
 *
 * @license http://litus.cc/LICENSE
 */

namespace CommonBundle\Repository\User;

use CommonBundle\Entity\Acl\Role,
    CommonBundle\Entity\General\AcademicYear,
    CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * Person
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Person extends EntityRepository
{
    public function findAllByNameQuery($name)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('p')
            ->from('CommonBundle\Entity\User\Person', 'p')
            ->where(
                $query->expr()->orX(
                    $query->expr()->like(
                        $query->expr()->concat(
                            $query->expr()->lower($query->expr()->concat('p.firstName', "' '")),
                            $query->expr()->lower('p.lastName')
                        ),
                        ':name'
                    ),
                    $query->expr()->like(
                        $query->expr()->concat(
                            $query->expr()->lower($query->expr()->concat('p.lastName', "' '")),
                            $query->expr()->lower('p.firstName')
                        ),
                        ':name'
                    )
                )
            )
            ->setParameter('name', '%' . strtolower($name) . '%')
            ->getQuery();

        return $resultSet;
    }

    public function findAllByRoleQuery(Role $role)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('p')
            ->from('CommonBundle\Entity\User\Person', 'p')
            ->innerJoin('p.roles', 'r')
            ->where(
                $query->expr()->eq('r.name', ':name')
            )
            ->setParameter('name', $role->getName())
            ->getQuery();

        return $resultSet;
    }

    public function findAllByUsernameQuery($username)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('p')
            ->from('CommonBundle\Entity\User\Person', 'p')
            ->where(
                $query->expr()->like('p.username', ':username')
            )
            ->setParameter('username', '%' . strtolower($username) . '%')
            ->getQuery();

        return $resultSet;
    }

    public function findOneByUsername($username)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('p')
            ->from('CommonBundle\Entity\User\Person', 'p')
            ->where(
                $query->expr()->eq('p.username', ':username')
            )
            ->setParameter('username', $username)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        if ($resultSet)
            return $resultSet;

        $barcode = $this->_em
            ->getRepository('CommonBundle\Entity\User\Barcode')
            ->findOneByBarcode($username);

        if ($barcode)
            return $barcode->getPerson();

        return null;
    }

    public function findAllByNameTypeaheadQuery($name)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('p')
            ->from('CommonBundle\Entity\User\Person', 'p')
            ->where(
                $query->expr()->orX(
                    $query->expr()->like(
                        $query->expr()->concat(
                            $query->expr()->lower($query->expr()->concat('p.firstName', "' '")),
                            $query->expr()->lower('p.lastName')
                        ),
                        ':name'
                    ),
                    $query->expr()->like(
                        $query->expr()->concat(
                            $query->expr()->lower($query->expr()->concat('p.lastName', "' '")),
                            $query->expr()->lower('p.firstName')
                        ),
                        ':name'
                    )
                )
            )
            ->setParameter('name', '%' . strtolower($name) . '%')
            ->setMaxResults(20)
            ->getQuery();

        return $resultSet;
    }
}
