<?php

namespace FormBundle\Repository\Node;

use DateTime,
    Doctrine\ORM\EntityRepository;

/**
 * Form
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Form extends EntityRepository
{
    public function findAll()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('n')
            ->from('FormBundle\Entity\Node\Form', 'n')
            ->orderBy('n.creationTime', 'DESC')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }

    public function findOneById($id) {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('n')
            ->from('FormBundle\Entity\Node\Form', 'n')
            ->where(
                $query->expr()->eq('n.id', ':id')
            )
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        if (isset($resultSet[0]))
            return $resultSet[0];

        return null;
    }

    public function findAllActive()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('f')
            ->from('FormBundle\Entity\Node\Form', 'f')
            ->where(
                $query->expr()->gt('f.endDate', ':now')
            )
            ->orderBy('f.creationTime', 'DESC')
            ->setParameter('now', new DateTime())
            ->getQuery()
            ->getResult();

        return $resultSet;
    }

    public function findAllOld()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('f')
            ->from('FormBundle\Entity\Node\Form', 'f')
            ->where(
                $query->expr()->lt('f.endDate', ':now')
            )
            ->orderBy('f.creationTime', 'DESC')
            ->setParameter('now', new DateTime())
            ->getQuery()
            ->getResult();

        return $resultSet;
    }

}
