<?php

namespace FormBundle\Repository\Node;

use DateTime;

/**
 * Form
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Form extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    public function findAllQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('n')
            ->from('FormBundle\Entity\Node\Form', 'n')
            ->orderBy('n.startDate', 'DESC')
            ->getQuery();
    }

    public function findAllActiveQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('f')
            ->from('FormBundle\Entity\Node\Form', 'f')
            ->where(
                $query->expr()->gt('f.endDate', ':now')
            )
            ->orderBy('f.startDate', 'DESC')
            ->setParameter('now', new DateTime())
            ->getQuery();
    }

    public function findAllOldQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('f')
            ->from('FormBundle\Entity\Node\Form', 'f')
            ->where(
                $query->expr()->lt('f.endDate', ':now')
            )
            ->orderBy('f.startDate', 'DESC')
            ->setParameter('now', new DateTime())
            ->getQuery();
    }
}
