<section>
    <div class="page-header">
        <h1>Group of Friends <small>run laps in a group of friends</small></h1>
    </div>

    <div class="row">
        <div class="span4 columns">
            <p>
                A group of friends is a small team of runners. Each team must choose 2 slots of 2 hours during the run.
                During these happy hours, you get 2 points for each lap. When you run outside of these hours, each lap earns you one point.
                Off course, the group who has collected the most points at the end of the run wins!
            </p>
        </div>
        <div class="span12 columns">
            <? if ($this->groupCreated): ?>
                <div class="alert-message success">
                    <p><strong>Success!</strong> Your group of friends was successfully created.</p>
                </div>
            <? else: ?>
                <? if ($this->request()->isPost()): ?>
                    <div class="alert-message alert">
                        <p>
                            <strong>Error!</strong> You forgot to enter a name somewhere, or one of you already is in another group.
                        </p>
                    </div>
                <? endif; ?>
                
                <?= $this->form; ?>
            <? endif; ?>
        </div>
    </div>
</section>

<script type="text/javascript">
    function hideShowFieldset(show, hide) {
        $('#fieldset-user_' + hide).hide();

        $('#university_identification_' + show).keyup(function() {
            if (8 == $('#university_identification_' + show).val().length)
                $('#fieldset-user_' + hide).fadeIn('slow');
        });
    }

    hideShowFieldset('one', 'two');
    hideShowFieldset('two', 'three');
    hideShowFieldset('three', 'four');
    hideShowFieldset('four', 'five');
</script>