<?= $this->partial('partials/run/navigation.phtml', array('currentAction' => 'queue')); ?>

<div id="controller_action">
    <? if (null === $this->nextLap): ?>
        <div class="error_message">
            <div class="title">Warning</div>
            <div class="content">
                <p>There is no next runner queued; go and find one, fast!</p>
            </div>
        </div>
    <? endif; ?>

    <table>
        <thead>
            <tr>
                <th>Runner</th>
                <th width="150px">Registration Time</th>
                <th width="150px">Duration</th>
                <th width="70px">Action</th>
            </tr>
        </thead>

        <tbody>
            <? foreach ($this->previousLaps as $previousLap): ?>
                <tr>
                    <td><?= $previousLap->getRunner()->getFullName(); ?></td>
                    <td><?= $previousLap->getRegistrationTime()->format('H:i:s'); ?></td>
                    <td><?= $previousLap->getLapTime()->format('%i:%S'); ?></td>
                    <td>
                        <a href="<?= $this->url(array('action' => 'delete', 'id' => $previousLap->getId())); ?>" class="delete">Delete</a>
                    </td>
                </tr>
            <? endforeach; ?>

            <? if (null !== $this->currentLap): ?>
                <tr>
                    <td>&raquo; <?= $this->currentLap->getRunner()->getFullName(); ?></td>
                    <td><?= $this->currentLap->getRegistrationTime()->format('d/m/Y H:i:s'); ?></td>
                    <td><i>Running</i></td>
                    <td>
                        <a href="<?= $this->url(array('action' => 'delete', 'id' => $this->currentLap->getId())); ?>" class="delete">Delete</a>
                    </td>
                </tr>
            <? endif; ?>

            <? foreach ($this->nextLaps as $nextLap): ?>
                <tr>
                    <td><?= $nextLap->getRunner()->getFullName(); ?></td>
                    <td><?= $nextLap->getRegistrationTime()->format('d/m/Y H:i:s'); ?></td>
                    <td><i>Queued</i></td>
                    <td>
                        <a href="<?= $this->url(array('action' => 'delete', 'id' => $nextLap->getId())); ?>" class="delete">Delete</a>
                    </td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>

<aside>
	<div class="sidebox">
        <div class="title">New Round</div>
        <div class="content">
            <p>
                <i>Please hit the link below to start timing a new lap!</i>
            </p>
            <p style="font-size: 17px;">
                <? if (null !== $this->nextLap): ?>
                    <a href="<?= $this->url(array('action' => 'start')); ?>">&rarr; Next Lap</a>
                <? else: ?>
                    <? if (null !== $this->currentLap): ?>
                        <a href="<?= $this->url(array('action' => 'stop')); ?>">&rarr; Stop</a>
                    <? else: ?>
                        &rarr; Stop
                    <? endif; ?>
                <? endif; ?>
            </p>
        </div>
    </div>

	<div class="sidebox">
        <div class="title">Total Laps</div>
        <div class="content">
            <p>
                According to our own counter, we have run <b><?= $this->nbLaps; ?></b> laps right now.
            </p>

            <p>
                The official count currently is <b><?= $this->nbOfficialLaps; ?></b>.
            </p>
        </div>
    </div>
</aside>

<?
foreach ($this->previousLaps as $previousLap)
    $previousLap->getId();
?>
