<?php

namespace CudiBundle\Repository\Stock\Deliveries;

use Doctrine\ORM\EntityRepository;

/**
 * Delivery
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Delivery extends EntityRepository
{
}