<?php

namespace BrBundle\Repository\Match\MatcheeMap;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentMatcheeMap extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
