<?php
/**
 * Litus is a project by a group of students from the KU Leuven. The goal is to create
 * various applications to support the IT needs of student unions.
 *
 * @author Niels Avonds <niels.avonds@litus.cc>
 * @author Karsten Daemen <karsten.daemen@litus.cc>
 * @author Koen Certyn <koen.certyn@litus.cc>
 * @author Bram Gotink <bram.gotink@litus.cc>
 * @author Dario Incalza <dario.incalza@litus.cc>
 * @author Pieter Maene <pieter.maene@litus.cc>
 * @author Kristof Mariën <kristof.marien@litus.cc>
 * @author Lars Vierbergen <lars.vierbergen@litus.cc>
 * @author Daan Wendelen <daan.wendelen@litus.cc>
 * @author Mathijs Cuppens <mathijs.cuppens@litus.cc>
 * @author Floris Kint <floris.kint@vtk.be>
 *
 * @license http://litus.cc/LICENSE
 */

namespace CommonBundle\Repository\General\Node\FAQ;

use CommonBundle\Entity\General\Node\FAQ\FAQ;
use PageBundle\Entity\Node\Page;

/**
 * FAQPageMap
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FAQPageMap extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @param FAQ  $faq
     * @param Page $page
     * @return \Doctrine\ORM\Query
     */
    public function findOneByFAQAndPage(FAQ $faq, Page $page)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('m')
            ->from('CommonBundle\Entity\General\Node\FAQ\FAQPageMap', 'm')
            ->innerJoin('m.referencedFAQ', 'f')
            ->innerJoin('m.referencedPage', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq(':faq', 'f.id'),
                    $query->expr()->eq(':page', 'p.id')
                )
            )
            ->setParameter('page', $page->getId())
            ->setParameter('faq', $faq->getId())
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param FAQ $faq
     * @return \Doctrine\ORM\Query
     */
    public function findAllByFAQQuery(FAQ $faq)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('m')
            ->from('CommonBundle\Entity\General\Node\FAQ\FAQPageMap', 'm')
            ->innerJoin('m.referencedFAQ', 'f')
            ->where(
                $query->expr()->eq(':faq', 'f.id')
            )
            ->orderBy('f.name', 'ASC')
            ->setParameter('faq', $faq->getId())
            ->getQuery();
    }

    /**
     * @param Page $page
     * @return \Doctrine\ORM\Query
     */
    public function findAllByPageQuery(Page $page)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('m')
            ->from('CommonBundle\Entity\General\Node\FAQ\FAQPageMap', 'm')
            ->innerJoin('m.referencedPage', 'p')
            ->where(
                $query->expr()->eq(':page', 'p.id')
            )
            ->orderBy('p.name', 'ASC')
            ->setParameter('page', $page->getId())
            ->getQuery();
    }
}
