<?= $this->partial('partials/section/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="controller_action">
    <? if ($this->sectionCreated): ?>
        <div class="success_message">
            <div class="title">Success</div>
            <div class="content">
                <p>The section was successfully created!</p>
            </div>
        </div>
    <? endif; ?>

    <?= $this->form; ?>
</div>

<aside>
    <div class="sidebox">
        <div class="title">Variables</div>
        <div class="content">
            <p>
                <i>These variables may be used in the text and will be substituted with their appropriate values.</i>
            </p>

            <p>
				<i>Company Name:</i> <br />
                &lt;company_name /&gt;
			</p>
			
			<p>	
				<i>Date:</i> <br />
				&lt;date /&gt;
			</p>	
			
			<p>
				<i>Euro Sign:</i> <br />
				&lt;euro /&gt;
            </p>
        </div>
    </div>

	<div class="sidebox">
        <div class="title">Formatting</div>
        <div class="content">
            <p>
                <i>When you enclose text in the following tags, </i>
            </p>

            <p>
                <b>&lt;b&gt;Bold:&lt;/b&gt;</b> <br />
				<i>&lt;i&gt;Italic:&lt;/i&gt;</i> <br />
				<u>&lt;u&gt;Underline:&lt;/u&gt;</u>
            </p>
        </div>
    </div>
</aside>