<?= $this->broker('partial')->direct('section/partials/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="controller_action">
    <? if ($this->sectionCreated): ?>
        <div class="success_message">
            <div class="title">Success</div>
            <div class="content">
                <p>The section was successfully created!</p>
            </div>
        </div>
    <? endif; ?>

    <?= $this->form; ?>
</div>

<aside>
    <div class="sidebox">
        <div class="title">Variables</div>
        <div class="content">
            <p>
                <i>These variables may be used in the text and will be substituted with their appropiate values.</i>
            </p>

            <p>
                {COMPANY_NAME}
            </p>
        </div>
    </div>
</aside>