<?= $this->partial('partials/section/navigation.phtml', array('currentAction' => '')); ?>

<div id="controller_action">
    <?= $this->form; ?>
</div>

<aside>
    <div class="sidebox">
        <div class="title">Variables</div>
        <div class="content">
            <p>
                <i>These variables may be used in the text and will be substituted with their appropriate values.</i>
            </p>

            <p>
				<i>Company Name:</i> <br />
                &lt;company_name /&gt;
			</p>

			<p>
				<i>Date:</i> <br />
				&lt;date /&gt;
			</p>

			<p>
				<i>Euro Sign:</i> <br />
				&lt;euro /&gt;
            </p>
        </div>
    </div>

	<div class="sidebox">
        <div class="title">Formatting</div>
        <div class="content">
            <p>
                <i>When you enclose text in the following tags, </i>
            </p>

            <p>
                <b>&lt;b&gt;Bold:&lt;/b&gt;</b> <br />
				<i>&lt;i&gt;Italic:&lt;/i&gt;</i> <br />
				<u>&lt;u&gt;Underline:&lt;/u&gt;</u>
            </p>
        </div>
    </div>
</aside>