<?= $this->broker('partial')->direct('partials/section/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <table class="zebra-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th width="100px">Author</th>
                <th width="75px">Year</th>
                <th width="80px">Action</th>
            </tr>
        </thead>

        <tbody>
            <? foreach ($this->paginator as $section): ?>
                <tr>
                    <td><?= $section->getName(); ?></td>
                    <td><?= $section->getAuthor()->getFirstName(); ?> <?= $section->getAuthor()->getLastName(); ?></td>
                    <td><?= $section->getYear(); ?></td>
                    <td><a href="/admin/section/edit/id/<?= $section->getId(); ?>">Edit</a> Delete</td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>