<?php

namespace Litus\Repository\Cudi\Stock;

use Doctrine\ORM\EntityRepository;

/**
 * Order
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Order extends EntityRepository
{
	public function findOneOpenByArticle($article)
	{
		$query = $this->_em->createQueryBuilder();
		$order = $query->select('o')
			->from('Litus\Entity\Cudi\Stock\Order', 'o')
			->where($query->expr()->andX(
					$query->expr()->eq('o.supplier', ':supplier'),
					$query->expr()->isNull('o.date')
				)
			)
			->setParameter('supplier', $article->getSupplier()->getId())
			->setMaxResults(1)
			->getQuery()
			->getResult();

		if (!isset($order[0]))
			return null;

		$item = $this->_em
			->getRepository('Litus\Entity\Cudi\Stock\OrderItem')
			->findOneByArticleAndOrder($article, $order[0]);
		
		return $item;
	}
}