<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SportBundle\Module'                             => __DIR__ . '//Module.php',
    'SportBundle\Controller\Admin\InstallController' => __DIR__ . '//src/Controller/Admin/InstallController.php',
    'SportBundle\Controller\Admin\RunController'     => __DIR__ . '//src/Controller/Admin/RunController.php',
    'Run\GroupController'                            => __DIR__ . '//src/Controller/GroupController.php',
    'Run\IndexController'                            => __DIR__ . '//src/Controller/IndexController.php',
    'Run\QueueController'                            => __DIR__ . '//src/Controller/QueueController.php',
    'Run\ScreenController'                           => __DIR__ . '//src/Controller/ScreenController.php',
    'SportBundle\Entity\Group'                       => __DIR__ . '//src/Entity/Group.php',
    'SportBundle\Entity\Lap'                         => __DIR__ . '//src/Entity/Lap.php',
    'SportBundle\Entity\Runner'                      => __DIR__ . '//src/Entity/Runner.php',
    'Run\Form\Group\Add'                             => __DIR__ . '//src/Form/Admin/Group/Add.php',
    'Run\Form\Queue\Add'                             => __DIR__ . '//src/Form/Admin/Queue/Add.php',
    'SportBundle\Repository\Group'                   => __DIR__ . '//src/Repository/Group.php',
    'SportBundle\Repository\Lap'                     => __DIR__ . '//src/Repository/Lap.php',
    'SportBundle\Repository\Runner'                  => __DIR__ . '//src/Repository/Runner.php',
);