<?php

namespace DoorBundle\Repository;

use DateTime;

/**
 * Rule
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rule extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('r')
            ->from('DoorBundle\Entity\Rule', 'r')
            ->where(
                $query->expr()->gt('r.endDate', ':now')
            )
            ->setParameter('now', new DateTime())
            ->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function findOld()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('r')
            ->from('DoorBundle\Entity\Rule', 'r')
            ->where(
                $query->expr()->lte('r.endDate', ':now')
            )
            ->setParameter('now', new DateTime())
            ->getQuery()
            ->getResult();
    }
}
