<?php

namespace MistDoctrine\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CommonBundleEntityGeneralBankCashRegisterProxy extends \CommonBundle\Entity\General\Bank\CashRegister implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getMoneyUnitAmounts()
    {
        $this->__load();
        return parent::getMoneyUnitAmounts();
    }

    public function getBankDeviceAmounts()
    {
        $this->__load();
        return parent::getBankDeviceAmounts();
    }

    public function getTotalAmount()
    {
        $this->__load();
        return parent::getTotalAmount();
    }

    public function getAmountForUnit(\CommonBundle\Entity\General\Bank\MoneyUnit $unit)
    {
        $this->__load();
        return parent::getAmountForUnit($unit);
    }

    public function getAmountForDevice(\CommonBundle\Entity\General\Bank\BankDevice $device)
    {
        $this->__load();
        return parent::getAmountForDevice($device);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'moneyUnitAmounts', 'bankDeviceAmounts');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}