<?= $this->partial('partials/article/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="controller_action">
    <? foreach($this->flashMessages as $message) { echo $message; } ?>

    <?= $this->form; ?>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		$('#internal').click(toggle);
		toggle();
	});
	
	function toggle() {
		if ($('#internal').is(':checked'))
			$('#internal_form').show();
		else
			$('#internal_form').hide();
	}
</script>