<?= $this->partial('partials/article/navigation.phtml', array('currentAction' => 'managefiles')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
    <h1>Article</h1>
    
    <p>Title: <b><?= $this->article->getTitle() . ($article->getVersionNumber() != 1 ? ' (v' . $article->getVersionNumber() . ')' : ''); ?></b></p>
    <p>Author: <b><?= $this->article->getMetaInfo()->getAuthors(); ?></b></p>
    <p>Publisher: <b><?= $this->article->getMetaInfo()->getPublishers(); ?></b></p>
    <br />
    
    <?= $this->form; ?>
	<br style="clear:both"/>
    
    <table class="full_width">
    
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th width="150px">Action</th>
        </tr>

        <? foreach ($this->article->getFiles() as $file): ?>

            <tr>
                <td><?= $file->getName(); ?></td>
                <td><?= $file->getDescription(); ?></td>
				<td>
					<a href="#" class="downloadFile view" data-file="<?= $this->url(array('action' => 'downloadfile', 'id' => $file->getId())); ?>">Download</a>
                    <a href="<?= $this->url(array('action' => 'deletefile', 'id' => $file->getId())); ?>" class="delete">Delete</a>
                </td>
            </tr>

        <? endforeach; ?>
    </table>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		$('.downloadFile').each(function () {
			$(this).downloadFile($(this).data('file'));
		});
	});
</script>