<?= $this->partial('partials/article/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<div id="stock_search" style="display:none;">
		<div style="padding:4px;text-align:right">
			Search: 
			<select id="searchField">
				<option value="title">Title</option>
				<option value="author">Author</option>
				<option value="publisher">Publisher</option>
			</select>
			is
			<input type="text" id="searchString" />
		</div>
		
		<table class="full_width">
    
        	<tr>
            	<th>Title</th>
            	<th>Author</th>
            	<th>Publisher</th>
            	<th>Year</th>
				<th>Type</th>
            	<th>Actions</th>
			</tr>
			
		</table>
	</div>
	
	<div id="default_page">
		<table class="full_width">

	        <tr>
	            <th>Title</th>
	            <th>Author</th>
	            <th>Publisher</th>
	            <th>Year</th>
				<th>Type</th>
	            <th width="130px">Action</th>
	        </tr>

	        <? foreach ($this->paginator as $article): ?>

	            <tr>
	                <td><?= $article->getTitle(); ?></td>
	                <td><?= $article->getMetaInfo()->getAuthors(); ?></td>
	                <td><?= $article->getMetaInfo()->getPublishers(); ?></td>
	                <td><?= $article->getMetaInfo()->getYearPublished(); ?></td>
	                <td><?= $article->isStock() ? 'Stock' : 'Stub'; ?></td>
					<td>
	                    <a href="<?= $this->url(array('action' => 'edit', 'id' => $article->getId())); ?>" class="edit">Edit</a>
	                    <a href="<?= $this->url(array('action' => 'delete', 'id' => $article->getId())); ?>" class="delete">Delete</a>
	                </td>
	            </tr>

	        <? endforeach; ?>
	    </table>

		<?= $this->paginationControl($this->paginator, 'all', 'partials/pagination.phtml', array('fullWidth' => true)); ?>
	</div>
</div>

<script language="javascript">
	$(document).ready(function () {
		$.SearchDatabase({
			defaultPage: $('#default_page'),
			searchDiv: $('#stock_search'),
			searchString: $('#searchString'),
			searchField: $('#searchField'),
			url: '<?= $this->url(array('action' => 'search')); ?>',
			display: function (data) {
				$('#stock_search table').find('tr.item').remove();
				$(data).each(function () {
					$('#stock_search table').append(row = $('<tr>', {class: 'item'}));
					row.append('<td>' + this.title + '</td>')
						.append('<td>' + this.author + '</td>')
						.append('<td>' + this.publisher + '</td>')
						.append('<td>' + this.yearPublished + '</td>')
						.append('<td>' + (this.isStock ? 'Stock' : 'Stub') + '</td>')
						.append('<td>'
							+ '<a href="<?= $this->url(array('action' => 'edit')); ?>/id/' + this.id + '" class="edit">Edit</a>'
							+ '<a href="<?= $this->url(array('action' => 'delete')); ?>/id/' + this.id + '" class="delete">Delete</a>'
							+ '</td>');
				});
			},
			clear: function () {
				$('#stock_search table').find('tr.item').remove();
			}
		});
	});
</script>