<?= $this->partial('partials/article/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <?php foreach($this->flashMessages as $message) { echo $message; } ?>

    <table>
    
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>Year</th>
            <th width="130px">Action</th>
        </tr>
        
        <? foreach ($this->articles as $article): ?>

            <tr>
                <td><?= $article->getTitle(); ?></td>
                <td><?= $article->getMetaInfo()->getAuthors(); ?></td>
                <td><?= $article->getMetaInfo()->getPublishers(); ?></td>
                <td><?= $article->getMetaInfo()->getYearPublished(); ?></td>
				<td>
                    <a href="<?= $this->url(array('action' => 'edit', 'id' => $article->getId())); ?>" class="edit">Edit</a>
                    <a href="<?= $this->url(array('action' => 'delete', 'id' => $article->getId())); ?>" class="delete">Delete</a>
                </td>
            </tr>
    
        <? endforeach; ?>
    </table>
</div>
