<?= $this->partial('partials/article/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<div id="stock_search" style="display:none;">
		<div style="padding:4px;text-align:right">
			Search: 
			<select id="searchField">
				<option value="title">Title</option>
				<option value="author">Author</option>
				<option value="publisher">Publisher</option>
			</select>
			is
			<input type="text" id="searchString" />
		</div>
		
		<table class="full_width">
    
        	<tr>
            	<th>Title</th>
            	<th>Author</th>
            	<th>Publisher</th>
            	<th>Year</th>
            	<th>Actions</th>
			</tr>
			
		</table>
	</div>
	
	<div id="default_page">
		<table class="full_width">

	        <tr>
	            <th>Title</th>
	            <th>Author</th>
	            <th>Publisher</th>
	            <th>Year</th>
	            <th width="130px">Action</th>
	        </tr>

	        <? foreach ($this->paginator as $article): ?>

	            <tr>
	                <td><?= $article->getTitle(); ?></td>
	                <td><?= $article->getMetaInfo()->getAuthors(); ?></td>
	                <td><?= $article->getMetaInfo()->getPublishers(); ?></td>
	                <td><?= $article->getMetaInfo()->getYearPublished(); ?></td>
					<td>
	                    <a href="<?= $this->url(array('action' => 'edit', 'id' => $article->getId())); ?>" class="edit">Edit</a>
	                    <a href="<?= $this->url(array('action' => 'delete', 'id' => $article->getId())); ?>" class="delete">Delete</a>
	                </td>
	            </tr>

	        <? endforeach; ?>
	    </table>

		<?= $this->paginationControl($this->paginator, 'all', 'partials/pagination.phtml', array('fullWidth' => true)); ?>
	</div>
</div>

<script language="javascript">
	$(document).keypress(function (e) {
		if (102 == e.keyCode && e.metaKey) {
			if ($('#stock_search').is(':visible')) {
				$('#stock_search').hide();
				$('#default_page').show();
			} else {
				$('#stock_search').show();
				$('#default_page').hide();
				$('#searchString').focus();
			}
			return false;
		}
	}).keyup(function (e) {
		if (27 == e.keyCode) {
			$('#stock_search').hide();
			$('#default_page').show();
		}
	}).ready(function () {
		$('#searchString, #searchField').bind('change click keyup', function () {
			var table = $('#stock_search table');
			if ('' == $('#searchString').val()) {
				table.find('tr.item').remove();
				return;
			}
			$.ajax({
				url: '<?= $this->url(array('action' => 'search')); ?>' + '/field/' + $('#searchField').val() + '/string/' + $('#searchString').val(),
				method: 'get',
				dataType: 'json',
				success: function (data) {
					table.find('tr.item').remove();
					$(data).each(function () {
						table.append(row = $('<tr>', {class: 'item'}));
						row.append('<td>' + this.title + '</td>')
							.append('<td>' + this.author + '</td>')
							.append('<td>' + this.publisher + '</td>')
							.append('<td>' + this.yearPublished + '</td>')
							.append('<td><a href="<?= $this->url(array('action' => 'edit')); ?>/id/' + this.id + '" class="edit">Edit</a></td>');
					});
				}
			});
		});
	});
</script>