<?php

	$this->layout()->disableLayout();

foreach( $queueItems as $queueItem ):
    echo "<div class=\"".$queueItem->getStatus()->getName()." queue_item\"><div onClick=\"itemClick(".$queueItem->getQueueNumber().", event);\" id=\"".$queueItem->getQueueNumber()."\"><div class=\"selectable_item\">";
    echo $queueItem->getQueueNumber() . ". ";
    echo is_null($queueItem->getPerson())?(" guest".$queueItem->getId()):$queueItem->getPerson()->getUsername();
    echo " : ".$queueItem->getStatus()->getName();
    echo "</div></div></div>\n";
endforeach;

