<?php

namespace CudiBundle\Repository\Article\Notification;

/**
 * Subscription
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Subscription extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
