<?php
return array(
    'SyllabusBundle\Module'                              => __DIR__ . '//Module.php',
    'SyllabusBundle\Component\WebSocket\Syllabus\Update' => __DIR__ . '//src/Component/WebSocket/Syllabus/Update.php',
    'SyllabusBundle\Component\XMLParser\Study'           => __DIR__ . '//src/Component/XMLParser/Study.php',
    'SyllabusBundle\Controller\Admin\InstallController'  => __DIR__ . '//src/Controller/Admin/InstallController.php',
    'SyllabusBundle\Controller\Admin\ProfController'     => __DIR__ . '//src/Controller/Admin/ProfController.php',
    'SyllabusBundle\Controller\Admin\StudyController'    => __DIR__ . '//src/Controller/Admin/StudyController.php',
    'SyllabusBundle\Controller\Admin\SubjectController'  => __DIR__ . '//src/Controller/Admin/SubjectController.php',
    'SyllabusBundle\Controller\Admin\UpdateController'   => __DIR__ . '//src/Controller/Admin/UpdateController.php',
    'SyllabusBundle\Entity\Study'                        => __DIR__ . '//src/Entity/Study.php',
    'SyllabusBundle\Entity\StudySubjectMap'              => __DIR__ . '//src/Entity/StudySubjectMap.php',
    'SyllabusBundle\Entity\Subject'                      => __DIR__ . '//src/Entity/Subject.php',
    'SyllabusBundle\Entity\SubjectProfMap'               => __DIR__ . '//src/Entity/SubjectProfMap.php',
    'SyllabusBundle\Form\Admin\Prof\Add'                 => __DIR__ . '//src/Form/Admin/Prof/Add.php',
    'SyllabusBundle\Repository\Study'                    => __DIR__ . '//src/Repository/Study.php',
    'SyllabusBundle\Repository\StudySubjectMap'          => __DIR__ . '//src/Repository/StudySubjectMap.php',
    'SyllabusBundle\Repository\Subject'                  => __DIR__ . '//src/Repository/Subject.php',
    'SyllabusBundle\Repository\SubjectProfMap'           => __DIR__ . '//src/Repository/SubjectProfMap.php',
);