<?php

namespace BrBundle\Repository\Contracts;

use Doctrine\ORM\EntityRepository;

/**
 * Section
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Section extends EntityRepository
{
}