<?php

namespace ProfBundle\Repository\Action\Mapping;

use Doctrine\ORM\EntityRepository;

/**
 * Add
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Add extends EntityRepository
{
}