<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PublicationBundle\Module'                                         => __DIR__ . '//Module.php',
    'PublicationBundle\Component\Validator\HtmlEditionTitleValidator'  => __DIR__ . '//src/Component/Validator/HtmlEditionTitleValidator.php',
    'PublicationBundle\Component\Validator\PdfEditionTitleValidator'   => __DIR__ . '//src/Component/Validator/PdfEditionTitleValidator.php',
    'PublicationBundle\Component\Validator\PublicationTitleValidator'  => __DIR__ . '//src/Component/Validator/PublicationTitleValidator.php',
    'PublicationBundle\Controller\Admin\Edition\HtmlEditionController' => __DIR__ . '//src/Controller/Admin/Edition/HtmlController.php',
    'PublicationBundle\Controller\Admin\Pdf\PdfEditionController'      => __DIR__ . '//src/Controller/Admin/Edition/PdfController.php',
    'PublicationBundle\Controller\Admin\InstallController'             => __DIR__ . '//src/Controller/Admin/InstallController.php',
    'PublicationBundle\Controller\Admin\PublicationController'         => __DIR__ . '//src/Controller/Admin/PublicationController.php',
    'PublicationBundle\Entity\Edition'                                 => __DIR__ . '//src/Entity/Edition.php',
    'PublicationBundle\Entity\Editions\Html'                           => __DIR__ . '//src/Entity/Editions/Html.php',
    'PublicationBundle\Entity\Editions\Pdf'                            => __DIR__ . '//src/Entity/Editions/Pdf.php',
    'PublicationBundle\Entity\Publication'                             => __DIR__ . '//src/Entity/Publication.php',
    'PublicationBundle\Form\Admin\Edition\Html\Add'                    => __DIR__ . '//src/Form/Admin/Edition/Html/Add.php',
    'PublicationBundle\Form\Admin\Edition\Pdf\Add'                     => __DIR__ . '//src/Form/Admin/Edition/Pdf/Add.php',
    'PublicationBundle\Form\Admin\Publication\Add'                     => __DIR__ . '//src/Form/Admin/Publication/Add.php',
    'PublicationBundle\Form\Admin\Publication\Edit'                    => __DIR__ . '//src/Form/Admin/Publication/Edit.php',
    'PublicationBundle\Repository\Edition'                             => __DIR__ . '//src/Repository/Edition.php',
    'PublicationBundle\Repository\Editions\HtmlEdition'                => __DIR__ . '//src/Repository/Editions/HtmlEdition.php',
    'PublicationBundle\Repository\Editions\PdfEdition'                 => __DIR__ . '//src/Repository/Editions/PdfEdition.php',
    'PublicationBundle\Repository\Publication'                         => __DIR__ . '//src/Repository/Publication.php',
);