<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'orders')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<table>
    
        <tr>
            <th>Name</th>
			<th>Actions</th>
        </tr>
        
        <? foreach ($this->suppliers as $supplier): ?>
            <tr>
                <td><?= $supplier->getName(); ?></td>
				<td>
					<a href="<?= $this->url(array('action' => 'supplier', 'id' => $supplier->getId())); ?>" class="view">View</a>
				</td>
            </tr>
        <? endforeach; ?>
    </table>
</div>

<aside>
	<div class="sidebox">
        <div class="title">New Order</div>
        <div class="content">
            <p>
                <i>Please hit the link below to add a new order item!</i>
            </p>
            <p>
                <a href="<?= $this->url(array('action' => 'add')); ?>">&rarr; Add order item</a>
            </p>
        </div>
    </div>
</aside>