<header id="controller_header">
    <div class="title"><span class="stock">Stock</span></div>

    <nav id="controller_nav">
        <ul>
            <? if ($this->hasAccess('admin', 'stock', 'orders')): ?>
                <li><a <? if('orders' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->url(array('action' => 'orders')); ?>">Orders</a></li>
            <? endif; ?>
			<? if ($this->hasAccess('admin', 'stock', 'deliveries')): ?>
                <li><a <? if('deliveries' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->url(array('action' => 'deliveries')); ?>">Deliveries</a></li>
            <? endif; ?>
            <? if ($this->hasAccess('admin', 'stock', 'overview')): ?>
                <li><a <? if('overview' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->url(array('action' => 'overview')); ?>">Overview</a></li>
            <? endif; ?>
        </ul>
    </nav>
</header>