<header id="controller_header">
    <div class="title"><span class="stock">Stock</span></div>

    <nav id="controller_nav">
        <ul>
            <? if ($this->hasAccess('admin', 'stock', 'manage')): ?>
                <li><a <? if('manage' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->url(array('action' => 'manage')); ?>">Manage</a></li>
            <? endif; ?>
        </ul>
    </nav>
</header>