<?= $this->partial('partials/contract/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <div class="error_message full_width">
        <div class="title">Warning</div>
        <div class="content">
            <? if ($this->contractDeleted): ?>
                <p>The contract was successfully deleted.</p>
            <? else: ?>
                <p>
                    You are about to delete the <b><?= $this->contract->getTitle(); ?></b> contract for <b><?= $this->contract->getCompany()->getName(); ?></b>.
                    Please note that this operation cannot be undone!
                </p>

                <p>
                    Are you sure you want to continue?<br />
                    <a href="<?= $this->url(array('confirm' => '1')); ?>">Yes</a>
                    <a href="<?= $this->url(array('confirm' => '0')); ?>">No</a>
                </p>
            <? endif; ?>
        </div>
    </div>
</div>