<?= $this->plugin('partial')->direct('partials/contract/navigation.phtml', array('currentAction' => 'download')); ?>

<div id="controller_action">
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th width="125px">Author</th>
                <th width="75px">Date</th>
                <th width="170px">Type</th>
            </tr>
        </thead>

        <tbody>
            <? foreach ($this->paginator as $contract): ?>
                <tr>
                    <td><?= $contract->getTitle() ?></td>
                    <td><?= $contract->getAuthor()->getFirstName(); ?> <?= $contract->getAuthor()->getLastName(); ?></td>
                    <td><?= $contract->getDate()->format('j/m/Y'); ?></td>
                    <td>
                        <a href="<?= $this->plugin('url')->direct(array('action' => 'download', 'id' => $contract->getId(), 'type' => 'contract')); ?>?format=pdf">Contract</a>
                        <a href="<?= $this->plugin('url')->direct(array('action' => 'download', 'id' => $contract->getId(), 'type' => 'letter')); ?>?format=pdf">Letter</a>
                        <? if ($contract->isSigned()): ?><a href="<?= $this->plugin('url')->direct(array('action' => 'download', 'id' => $contract->getId(), 'type' => 'invoice')); ?>?format=pdf">Invoice</a><? endif ?>
                    </td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>

    <?= $this->plugin('paginationControl')->direct($this->paginator, 'all', 'partials/pagination.phtml'); ?>
</div>
