<?= $this->broker('partial')->direct('contract/partials/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <table class="zebra-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th width="100px">Author</th>
                <th width="75px">Date</th>
                <th width="120px">Action</th>
            </tr>
        </thead>

        <tbody>
            <? foreach ($this->paginator as $contract): ?>
                <tr>
                    <td><?= $contract->getTitle() ?></td>
                    <td><?= $contract->getAuthor()->getFirstName(); ?> <?= $contract->getAuthor()->getLastName(); ?></td>
                    <td><?= $contract->getDate()->format('j/m/Y') ?></td>
                    <td><a href="/admin/contract/edit/id/<?= $contract->getId(); ?>">Edit</a> Delete <? if (!$contract->isSigned()): ?><a href="/admin/contract/sign/id/<?= $contract->getId(); ?>">Sign</a><? endif ?></td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>