<?= $this->partial('partials/contract/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
    <table class="full_width">
        <thead>
            <tr>
                <th>Title</th>
                <th width="150px">Author</th>
                <th width="75px">Date</th>
                <th width="200px">Action</th>
            </tr>
        </thead>

        <tbody>
            <? foreach ($this->paginator as $contract): ?>
                <tr>
                    <td><?= $contract->getTitle() ?></td>
                    <td><?= $contract->getAuthor()->getFirstName(); ?> <?= $contract->getAuthor()->getLastName(); ?></td>
                    <td><?= $contract->getDate()->format('j/m/Y'); ?></td>
                    <td>
                        <a href="<?= $this->url(array('action' => 'edit', 'id' => $contract->getId())); ?>" class="edit">Edit</a>
                        <a href="<?= $this->url(array('action' => 'delete', 'id' => $contract->getId())); ?>" class="delete">Delete</a>
                        <? if (!$contract->isSigned()): ?><a href="<?= $this->url(array('action' => 'sign', 'id' => $contract->getId())); ?>" class="sign">Sign</a><? endif ?>
                    </td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>

    <?= $this->paginationControl($this->paginator, 'all', 'partials/pagination.phtml', array('fullWidth' => true)); ?>
</div>