<?php

namespace MailBundle\Repository\MailingList;

/**
 * AdminRoleMap
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRoleMap extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
