<?php

namespace MailBundle\Repository\MailingList;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * AdminRoleMap
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRoleMap extends EntityRepository
{
}
