<?php

namespace MailBundle\Repository\MailingList;

use CommonBundle\Component\Util\EntityRepository;

/**
 * Entry
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Entry extends EntityRepository
{
}
