<?php

namespace BrBundle\Repository\Match;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Profile extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
