<? if (0 != $this->vars('pageCount')): ?>
    <table class="pagination <? if ($this->vars('fullWidth')): ?>full_width<? endif; ?>">
        <tr>
            <td>
                <? if (null !== $this->vars('previous')): ?>
                    <a href="<?= $this->url(array('page' => $this->first)); ?>">First</a>
                <? else: ?>
                    <? if (1 != $this->vars('pageCount')): ?>
                        First
                    <? endif; ?>
                <? endif; ?>

                <? if (null !== $this->vars('previous')): ?>
                    <a href="<?= $this->url(array('page' => $this->previous)); ?>">Previous</a>
                <? endif; ?>
            </td>

            <td>
                <?= $this->vars('current'); ?>/<?= $this->vars('pageCount'); ?>
            </td>

            <td>
                <? if (null !== $this->vars('next')): ?>
                    <a href="<?= $this->url(array('page' => $this->next)); ?>">Next</a>
                <? endif; ?>

                <? if (null !== $this->vars('next')): ?>
                    <a href="<?= $this->url(array('page' => $this->last)); ?>">Last</a>
                <? else: ?>
                    <? if (1 != $this->vars('pageCount')): ?>
                        Last
                    <? endif; ?>
                <? endif; ?>
            </td>
        </tr>
    </table>
<? endif; ?>