<? if (0 != $this->vars('pageCount')): ?>
    <table class="pagination <? if ($this->vars('fullWidth')): ?>full_width<? endif; ?>">
        <tr>
            <td>
                <? if (null !== $this->vars('previous')): ?>
                    <a href="<?= $this->url(array('page' => $this->first)); ?>">&larr; First</a>
                <? else: ?>
                    <? if (1 != $this->vars('pageCount') && 1 != $this->vars('current')): ?>
                        &larr; First
                    <? endif; ?>
                <? endif; ?>

                <? if (null !== $this->vars('previous')): ?>
                    <a href="<?= $this->url(array('page' => $this->previous)); ?>">&laquo; Previous</a>
                <? endif; ?>
            </td>

            <td>
                <?= $this->vars('current'); ?>/<?= $this->vars('pageCount'); ?>
            </td>

            <td>
                <? if (null !== $this->vars('next')): ?>
                    <a href="<?= $this->url(array('page' => $this->next)); ?>">Next &raquo;</a>
                <? endif; ?>

                <? if (null !== $this->vars('next')): ?>
                    <a href="<?= $this->url(array('page' => $this->last)); ?>">Last &rarr;</a>
                <? else: ?>
                    <? if (1 != $this->vars('pageCount') && $this->vars('pageCount') != $this->vars('current')): ?>
                        Last &rarr;
                    <? endif; ?>
                <? endif; ?>
            </td>
        </tr>
    </table>
<? endif; ?>