<head>

	<script type="text/javascript">
	<!--
		function toggle_visibility() {
			var e = document.getElementById('internal_form');
	      	if(document.getElementById('internal').checked) {
				e.style.display = 'block';
	      	} else {
	          	e.style.display = 'none';
	      	}
	    }
	//-->
	</script>

</head>

<?= $this->partial('partials/textbook/navigation.phtml', array('currentAction' => 'add')); ?>

<body>

	<div id="controller_action">
	    <? if ($this->textbookCreated): ?>
        	<div class="success_message full_width">
	            <div class="title">Success</div>
	            <div class="content">
	                <p>The textbook was successfully created!</p>
	            </div>
	        </div>
	    <? endif; ?>
	    <?= $this->form; ?>
	</div>
	
	<script type="text/javascript">
	<!--
		// Run the script on pageload to set the visibility correctly
		toggle_visibility();
	//-->
	</script>
	
</body>