<head>

	<script type="text/javascript">
	<!--
		function toggle_visibility() {
			var e = document.getElementById('internal_form');
	      	if(document.getElementById('internal').checked) {
				e.style.display = 'block';
	      	} else {
	          	e.style.display = 'none';
	      	}
	    }
	//-->
	</script>

</head>

<?= $this->broker('partial')->direct('textbook/partials/navigation.phtml', array('currentAction' => 'add')); ?>

<body>

	<div id="controller_action">
	    <?= $this->form; ?>
	</div>
	
	<script type="text/javascript">
	<!--
		// Run the script on pageload to set the visibility correctly
		toggle_visibility();
	//-->
	</script>
	
</body>