<?= $this->partial('partials/textbook/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <table>
    
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>Year</th>
        </tr>
        
        <? foreach ($this->articles as $article): ?>

            <tr>
                <td><?= $article->getTitle(); ?></td>
                <td><?= $article->getMetaInfo()->getAuthors(); ?></td>
                <td><?= $article->getMetaInfo()->getPublishers(); ?></td>
                <td><?= $article->getMetaInfo()->getYearPublished(); ?></td>
            </tr>
    
        <? endforeach; ?>
    </table>
</div>