<?= $this->broker('partial')->direct('textbook/partials/navigation.phtml', array('currentAction' => 'manage')); ?>
 
 
<head>

    <style type="text/css" >
    
        th {
            text-align: left;
            font-weight: bold;
            width: 80px;
        }
    
    </style>

</head>

<div id="controller_action">
    <table>
    
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>Year</th>
        </tr>
        
        <? foreach ($this->articles as $article) { ?>

            <tr>
                <td><?= $article->getTitle(); ?></td>
                <td><?= $article->getMetaInfo()->getAuthors(); ?></td>
                <td><?= $article->getMetaInfo()->getPublishers(); ?></td>
                <td><?= $article->getMetaInfo()->getYearPublished(); ?></td>
            </tr>
    
        <? } ?>
    </table>
</div>