<?php

namespace PageBundle\Repository\Node;

/**
 * CategoryPage
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPage extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    public function findOneByCategory($category)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('PageBundle\Entity\Node\CategoryPage', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('p.category', ':category'),
                )
            )
            ->setParameter('category', $category)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}