<?php
$this->headMeta()
    ->setCharset('utf-8');
$this->headTitle('24h-Run', 'PREPEND')
    ->setSeparator('-');

$this->headLink()
    ->appendStylesheet($this->baseUrl('/_bootstrap/bootstrap.min.css'))
    ->appendStylesheet($this->baseUrl('/_run/stylesheet/css/run.css'));
$this->headScript()
    ->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js')
    ->appendFile($this->baseUrl('/_bootstrap/js/bootstrap-alerts.js'));
?>

<?= $this->docType(); ?>

<html lang="en">
<head>

	<?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headLink(); ?>
	<?= $this->headScript(); ?>
	<?= $this->headStyle(); ?>

    <script>
        window.jQuery || document.write("<script src='<?= $this->baseUrl('/_run/js/jquery-1.6.2.min.js'); ?>'>\x3C/script>")
    </script>

</head>

<body id="bootstrap-js">

    <div class="container">
        <section>
            <div class="page-header">
                <h1>Welcome!</h1>
            </div>

            <div class="row">
                <div class="span4">
                    <h2>Laps</h2>

                    <p>
                        Up till now, we have run <span class="label important" style="font-size: 16px;"><?= $this->nbOfficialLaps; ?></span> laps.
                    </p>

                    <h2>Runners</h2>

                    <p>
                        There have been <span class="label success" style="font-size: 16px;"><?= $this->uniqueRunners; ?></span> unique runners.
                    </p>
                </div>
                <div class="span12">
                    <h2>Current Runner</h2>
                    <div id="currentLap" class="alert-message success">
                        <p>
                            <span style="font-size: 18px;">
                                <strong id="currentLapRunnerName">
                                    <?= null !== $this->currentLap ? $this->currentLap->getRunner()->getFullName() : 'Nobody'; ?>
                                </strong>
                            </span>
                        </p>

                        <p id="currentLapTime">
                            <?= null !== $this->currentLap ? $this->currentLap->getLapTime()->format('%i:%S') : '00:00'; ?>
                        </p>
                    </div>

                    <div id="noCurrentLap" class="alert-message error" style="display: none;">
                        <p>
                            <span style="font-size: 18px;">There is no next runner!</span>
                        </p>
                    </div>

                    <div class="row">
                        <div class="span6">
                            <h3>Previous Runners</h3>

                            <table class="zebra-striped">
                                <thead>
                                    <tr>
                                        <th width="10%">#</th>
                                        <th width="60%">Runner</th>
                                        <th width="30%">Lap Time</th>
                                    </tr>
                                </thead>

                                <tbody id="previous_runners">
                                    <tr>
                                        <td colspan="3"><i>There are no previous runners!</i></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="span6">
                            <h3>Next Runners</h3>

                            <table class="zebra-striped">
                                <thead>
                                    <tr>
                                        <th width="10%">#</th>
                                        <th width="90%">Runner</th>
                                    </tr>
                                </thead>

                                <tbody id="next_runners">
                                    <tr>
                                        <td colspan="3"><i>There are no next runners!</i></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script type="text/javascript">
        setInterval(function() {
                $.getJSON('<?= $this->url(array('action' => 'update')); ?>?format=json', function(data) {
                    if (false != data.currentLap) {
                        $('#noCurrentLap').fadeOut('slow', function() {
                            $('#currentLap').fadeIn('slow');
                        });

                        $('#currentLapRunnerName').text(data.currentLap.runnerName);
                        $('#currentLapTime').text(data.currentLap.time);
                    } else {
                        $('#currentLap').fadeOut('slow', function() {
                            $('#noCurrentLap').fadeIn('slow');
                        });
                    }

                    if (0 != data.previousLaps.length) {
                        $('#previous_runners').empty();

                        $.each(data.previousLaps, function(lapNb, previousLap) {
                            $('#previous_runners').append('<tr><td>' + previousLap.id + '</td><td>' + previousLap.runner + '</td><td>' + previousLap.time + '</td></tr>')
                        });
                    }

                    if (0 != data.nextLaps.length) {
                        $('#next_runners').empty();

                        $.each(data.nextLaps, function(lapNb, nextLap) {
                            $('#next_runners').append('<tr><td>' + nextLap.id + '</td><td>' + nextLap.runner + '</td></tr>')
                        });
                    }
                })
            },
            1000
        );
    </script>

</body>

</html>