<?php

namespace ShiftBundle\Repository\Shifts;

use Doctrine\ORM\EntityRepository;

/**
 * Responsible
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Responsible extends EntityRepository
{
}
