<?php

namespace ShopBundle\Repository\Session\Message;

/**
 * Translation
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Translation extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
