<?php

namespace Litus\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class LitusEntityCudiStockStockItemProxy extends \Litus\Entity\Cudi\Stock\StockItem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getArticle()
    {
        $this->__load();
        return parent::getArticle();
    }

    public function getNumberInStock()
    {
        $this->__load();
        return parent::getNumberInStock();
    }

    public function setNumberInStock($number)
    {
        $this->__load();
        return parent::setNumberInStock($number);
    }

    public function addNumber($number)
    {
        $this->__load();
        return parent::addNumber($number);
    }

    public function getTotalOrdered()
    {
        $this->__load();
        return parent::getTotalOrdered();
    }

    public function getNumberNotDelivered()
    {
        $this->__load();
        return parent::getNumberNotDelivered();
    }

    public function getNumberQueueOrder()
    {
        $this->__load();
        return parent::getNumberQueueOrder();
    }

    public function getTotalDelivered()
    {
        $this->__load();
        return parent::getTotalDelivered();
    }

    public function getNumberBooked()
    {
        $this->__load();
        return parent::getNumberBooked();
    }

    public function getNumberAssigned()
    {
        $this->__load();
        return parent::getNumberAssigned();
    }

    public function getNumberSold()
    {
        $this->__load();
        return parent::getNumberSold();
    }

    public function getNumberAvailable()
    {
        $this->__load();
        return parent::getNumberAvailable();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'article', 'numberInStock');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}