<?php
/**
 * Litus is a project by a group of students from the KU Leuven. The goal is to create
 * various applications to support the IT needs of student unions.
 *
 * @author Niels Avonds <niels.avonds@litus.cc>
 * @author Karsten Daemen <karsten.daemen@litus.cc>
 * @author Koen Certyn <koen.certyn@litus.cc>
 * @author Bram Gotink <bram.gotink@litus.cc>
 * @author Dario Incalza <dario.incalza@litus.cc>
 * @author Pieter Maene <pieter.maene@litus.cc>
 * @author Kristof Mariën <kristof.marien@litus.cc>
 * @author Lars Vierbergen <lars.vierbergen@litus.cc>
 * @author Daan Wendelen <daan.wendelen@litus.cc>
 * @author Mathijs Cuppens <mathijs.cuppens@litus.cc>
 * @author Floris Kint <floris.kint@vtk.be>
 *
 * @license http://litus.cc/LICENSE
 */

namespace PublicationBundle\Repository;

/**
 * Publication
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Publication extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    public function findOneActiveById($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('PublicationBundle\Entity\Publication', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('p.id', ':id'),
                    $query->expr()->eq('p.deleted', 'false')
                )
            )
            ->setParameter('id', $id)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findOneByTitle($title)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('PublicationBundle\Entity\Publication', 'p')
            ->where(
                $query->expr()->eq('p.title', ':title')
            )
            ->setParameter('title', $title)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findAllActiveQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('PublicationBundle\Entity\Publication', 'p')
            ->where(
                $query->expr()->eq('p.deleted', 'false')
            )
            ->orderBy('p.title', 'ASC')
            ->getQuery();
    }

    public function findAllActiveWithEditionQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('PublicationBundle\Entity\Publication', 'p')
            ->where(
                $query->expr()->andx(
                    $query->expr()->eq('p.deleted', 'false'),
                    $query->expr()->exists(
                        'SELECT e FROM PublicationBundle\Entity\Edition e WHERE e.publication = p'
                    )
                )
            )
            ->orderBy('p.title', 'ASC')
            ->getQuery();
    }
}
