<?php

namespace NewsBundle\Repository\Node;

use Doctrine\ORM\EntityRepository;

/**
 * News
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class News extends EntityRepository
{
    public function findAll($nbResults = 3)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('n')
            ->from('NewsBundle\Entity\Node\News', 'n')
            ->orderBy('n.creationTime', 'DESC')
            ->setMaxResults($nbResults)
            ->getQuery()
            ->getResult();

        return $resultSet;
    }

    public function findAllSite()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('n')
            ->from('NewsBundle\Entity\Node\News', 'n')
            ->where(
                $query->expr()->orX(
                    $query->expr()->gte('n.endDate', ':now'),
                    $query->expr()->isNull('n.endDate')
                )
            )
            ->setParameter('now', new \DateTime())
            ->orderBy('n.creationTime', 'DESC')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }

    public function findNbSite($nbResults = 3)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('n')
            ->from('NewsBundle\Entity\Node\News', 'n')
            ->where(
                $query->expr()->orX(
                    $query->expr()->gte('n.endDate', ':now'),
                    $query->expr()->isNull('n.endDate')
                )
            )
            ->setParameter('now', new \DateTime())
            ->orderBy('n.creationTime', 'DESC')
            ->setMaxResults($nbResults)
            ->getQuery()
            ->getResult();

        return $resultSet;
    }
}
