<?php

namespace PublicationBundle\Repository\Edition;

use CommonBundle\Entity\General\AcademicYear;
use PublicationBundle\Entity\Publication as PublicationEntity;

/**
 * Pdf
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pdf extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    public function findAllByPublicationAndAcademicYearQuery(PublicationEntity $publication, AcademicYear $academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('PublicationBundle\Entity\Edition\Pdf', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('p.publication', ':publication'),
                    $query->expr()->eq('p.academicYear', ':year')
                )
            )
            ->setParameter('publication', $publication)
            ->setParameter('year', $academicYear)
            ->orderBy('p.date', 'ASC')
            ->getQuery();
    }

    public function findAllByPublicationQuery(PublicationEntity $publication)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('PublicationBundle\Entity\Edition\Pdf', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('p.publication', ':publication'),
                )
            )
            ->setParameter('publication', $publication)
            ->orderBy('p.date', 'DESC')
            ->getQuery();
    }

    public function findOneByPublicationTitleAndAcademicYear(PublicationEntity $publication, $title, AcademicYear $academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('PublicationBundle\Entity\Edition\Pdf', 'p')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('p.publication', ':publication'),
                    $query->expr()->eq('p.title', ':title'),
                    $query->expr()->eq('p.academicYear', ':year')
                )
            )
            ->setParameter('publication', $publication)
            ->setParameter('title', $title)
            ->setParameter('year', $academicYear)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
