<?php
/**
 * Litus is a project by a group of students from the K.U.Leuven. The goal is to create
 * various applications to support the IT needs of student unions.
 *
 * @author Karsten Daemen <karsten.daemen@litus.cc>
 * @author Bram Gotink <bram.gotink@litus.cc>
 * @author Pieter Maene <pieter.maene@litus.cc>
 * @author Kristof Mariën <kristof.marien@litus.cc>
 * @author Michiel Staessen <michiel.staessen@litus.cc>
 * @author Alan Szepieniec <alan.szepieniec@litus.cc>
 *
 * @license http://litus.cc/LICENSE
 */

namespace CommonBundle\Controller\Admin;

use CommonBundle\Entity\General\Address\City,
    CommonBundle\Entity\General\Address\Street,
    CommonBundle\Entity\General\Language;

/**
 * InstallController
 *
 * @author Pieter Maene <pieter.maene@litus.cc>
 */
class InstallController extends \CommonBundle\Component\Controller\ActionController\InstallController
{
    protected function initConfig()
    {
        $this->_installLanguages();
        $this->_installCities();

        $this->installConfig(
            array(
                array(
                    'key'         => 'common.profile_path',
                    'value'       => 'data/common/profile',
                    'description' => 'The path for profile photo\'s',
                ),
                array(
                    'key'         => 'search_max_results',
                    'value'       => '30',
                    'description' => 'The maximum number of search results shown',
                ),
                array(
                    'key'         => 'account_deactivated_mail',
                    'value'       => 'Dear,

Your account on Litus is deactivated.
Click here to activate it again: http://litus/account/activate/code/{{ code }}',
                    'description' => 'The email sent when an account is deactivated',
                ),
                array(
                    'key'         => 'account_deactivated_subject',
                    'value'       => 'Account deactivated',
                    'description' => 'The mail subject when an account is deactivated',
                ),
                array(
                    'key'         => 'system_mail_address',
                    'value'       => 'info@litus.cc',
                    'description' => 'The system mail address',
                ),
                array(
                    'key'         => 'system_mail_name',
                    'value'       => 'Litus Project',
                    'description' => 'The system mail name',
                ),
                array(
                    'key'         => 'account_activated_mail',
                    'value'       => 'Dear {{ name }},

An account for you is created on Litus with username {{ username }}.
Click here to activate it: http://litus/account/activate/code/{{ code }}',
                    'description' => 'The email sent when an account is deactivated',
                ),
                array(
                    'key'         => 'account_activated_subject',
                    'value'       => 'Account created',
                    'description' => 'The mail subject when an account is deactivated',
                ),
                array(
                    'key'         => 'start_organization_year',
                    'value'       => '{{ year }}-7-15 0:0:0',
                    'description' => 'The start date of the organization year',
                ),
                array(
                    'key'         => 'shibboleth_url',
                    'value'       => 'https://arianna.vtk.be/Shibboleth.sso/Login?target=https%3A%2F%2Farianna.vtk.be%2Fshibboleth%2F',
                    'description' => 'The Shibboleth authentication URL, wherein the target parameter specifies the redirect',
                ),
                array(
                    'key'         => 'shibboleth_person_key',
                    'value'       => 'Shib-Person-uid',
                    'description' => 'The key in the $_SERVER array that accesses the university identification',
                ),
                array(
                    'key'         => 'shibboleth_session_key',
                    'value'       => 'Shib-Session-ID',
                    'description' => 'The key in the $_SERVER array that accesses the shibboleth session',
                ),
                array(
                    'key'         => 'shibboleth_code_handler_url',
                    'value'       => serialize(
                        array(
                            'admin'    => 'https://dev.vtk.be/admin/auth/shibboleth',
                            'prof'     => 'https://dev.vtk.be/cudi/prof/auth/shibboleth',
                            'site'     => 'https://dev.vtk.be/auth/shibboleth',
                            'register' => 'https://dev.vtk.be/secretary/registration',
                        )
                    ),
                    'description' => 'The Shibboleth handler URL, without a trailing slash',
                ),
                array(
                    'key'         => 'system_administrator_mail',
                    'value'       => 'it@vtk.be',
                    'description' => 'The mail address of system administrator',
                ),
                array(
                    'key'         => 'fallback_language',
                    'value'       => 'nl',
                    'description' => 'The abbreviation of the language that will be used of no other translation is present',
                ),
            )
        );
    }

    protected function initAcl()
    {
        $this->installAcl(
            array(
                'commonbundle' => array(
                    'admin_academic' => array(
                        'add', 'delete', 'edit', 'manage', 'search', 'typeahead'
                    ),
                    'admin_auth' => array(
                        'authenticate', 'login', 'logout'
                    ),
                    'admin_cache' => array(
                        'manage', 'flush'
                    ),
                    'admin_config' => array(
                        'edit', 'manage'
                    ),
                    'admin_index' => array(
                        'index'
                    ),
                    'admin_role' => array(
                        'add', 'edit', 'delete', 'manage'
                    ),
                    'index' => array(
                        'index'
                    ),

                    'api_install' => array(
                        'index'
                    ),
                    'br_install' => array(
                        'index'
                    ),
                    'calendar_install' => array(
                        'index'
                    ),
                    'common_install' => array(
                        'index'
                    ),
                    'cudi_install' => array(
                        'index'
                    ),
                    'gallery_install' => array(
                        'index'
                    ),
                    'mail_install' => array(
                        'index'
                    ),
                    'news_install' => array(
                        'index'
                    ),
                    'page_install' => array(
                        'index'
                    ),
                    'secretary_install' => array(
                        'index'
                    ),
                    'syllabus_install' => array(
                        'index'
                    ),
                )
            )
        );

        $this->installRoles(
            array(
                'guest' => array(
                    'system' => true,
                    'parents' => array(
                    ),
                    'actions' => array(
                        'admin_auth' => array(
                            'authenticate', 'login', 'logout'
                        ),
                        'index' => array(
                            'index'
                        ),
                    ),
                ),
            )
        );
    }

    private function _installLanguages()
    {
        $languages = array(
            'en' => 'English',
            'nl' => 'Nederlands'
        );

        foreach($languages as $abbrev => $name) {
            $language = $this->getEntityManager()
                ->getRepository('CommonBundle\Entity\General\Language')
                ->findOneByAbbrev($abbrev);

            if (null == $language) {
                $language = new Language($abbrev, $name);
                $this->getEntityManager()->persist($language);
            }
        }

        $this->getEntityManager()->flush();
    }

    private function _installCities()
    {
        $cities = array(
            array(
                'name'    => 'Heverlee',
                'postal'  => '3001',
                'streets' => array(
                    0054 => '',
                    0001 => 'Abdij van Park',
                    0002 => 'Abdijstraat',
                    0003 => 'Adjudant Harboortstraat',
                    0156 => 'Alaudastraat',
                    0063 => 'Albert Stainierstraat',
                    0021 => 'Alfred Delaunoislaan',
                    0004 => 'Alsembergstraat',
                    0205 => 'Ambachtenlaan',
                    0131 => 'Antonius Rodolphestraat',
                    0006 => 'Armand Thiérylaan',
                    0141 => 'Arthur Meulemanslaan',
                    0125 => 'Beeklaan',
                    0007 => 'Berkenhoflaan',
                    0160 => 'Bertembosstraat',
                    0008 => 'Bertemstraat',
                    0212 => 'Berthe Gottignystraat',
                    0009 => 'Beukenlaan',
                    0120 => 'Bierbeekpleindreef',
                    0010 => 'Bierbeekstraat',
                    0011 => 'Bloemenlaan',
                    0012 => 'Boogschuttersstraat',
                    0013 => 'Boskantlaan',
                    0206 => 'Brabantlaan',
                    0117 => 'Bredeweg',
                    0014 => 'Bremstraat',
                    0015 => 'Broekstraat',
                    0016 => 'Bronlaan',
                    0017 => 'Brugstraat',
                    0126 => 'Burgemeester Stanislas De Rijcklaan',
                    0018 => 'Celestijnenlaan',
                    0161 => 'Damendreef',
                    0128 => 'Dellenhof',
                    0169 => 'Dennendreef',
                    0164 => 'Dodendreef',
                    0023 => 'Doleegstraat',
                    0024 => 'Dreefstraat',
                    0114 => 'Duinberglaan',
                    0129 => 'Duisburgsestraat',
                    0027 => 'Eburonenlaan',
                    0025 => 'Egenhovenweg',
                    0140 => 'Emiel Hullebroecklaan',
                    0111 => 'Erasme Ruelenspark',
                    0079 => 'Erasme Ruelensvest',
                    0151 => 'Esperantolaan',
                    0208 => 'Evementenlaan',
                    0068 => 'Ferdinand Verbiestlaan',
                    0127 => 'Filosofenbaan',
                    0168 => 'Filosofendreef',
                    0155 => 'Frans Cnopslaan',
                    0138 => 'Gaston Feremanslaan',
                    0030 => 'Geldenaaksebaan',
                    0031 => 'Goede Haardlaan',
                    0032 => 'Goswin III-laan',
                    0122 => 'Goudfazantenlaan',
                    0020 => 'Graaf de Grunnelaan',
                    0201 => 'Grauwmeer',
                    0170 => 'Grezweg',
                    0033 => 'Groeneweg',
                    0034 => 'Groenstraat',
                    0036 => 'Groenveldstraat',
                    0152 => 'Haanhofweg',
                    0038 => 'Heidelaan',
                    0029 => 'Henri Geeraertlaan',
                    0118 => 'Herendreef',
                    0039 => 'Hertog Engelbertlaan',
                    0041 => 'Hertogstraat',
                    0043 => 'Hollestraat',
                    0067 => 'Hoveniersdreef',
                    0044 => 'Huttelaan',
                    0110 => 'Idalaan',
                    0105 => 'Ijzerenmolenstraat',
                    0154 => 'Industrieweg',
                    0202 => 'Interleuvenlaan',
                    0157 => 'Jachthorenstraat',
                    0123 => 'Jachtlaan',
                    0143 => 'Jef Van Hooflaan',
                    0142 => 'Jef Vanden Eyndelaan',
                    0139 => 'Joos Florquinlaan',
                    0136 => 'Jos De Haeslaan',
                    0145 => 'Jozef Eerdekensstraat',
                    0094 => 'Jules Vandenbemptlaan',
                    0134 => 'Kantineplein',
                    0109 => 'Kapelberg',
                    0045 => 'Kapeldreef',
                    0046 => 'Kardinaal Mercierlaan',
                    0162 => 'Karrendreef',
                    0116 => 'Kastanjelaan',
                    0215 => 'Kasteelpark Arenberg',
                    0047 => 'Keibergstraat',
                    0048 => 'Kerkhofdreef',
                    0049 => 'Kerspelstraat',
                    0050 => 'Kloosterlaan',
                    0209 => 'Kneuterweg',
                    0056 => 'Koning Leopold III-laan',
                    0051 => 'Korbeek-Losestraat',
                    0147 => 'Korbeekhof',
                    0052 => 'Kriekenboslaan',
                    0042 => 'Krommelaan',
                    0148 => 'Lange Hagen',
                    0053 => 'Langendaallaan',
                    0171 => 'Langestaart',
                    0055 => 'Leo Dartelaan',
                    0057 => 'Lievevrouweplein',
                    0115 => 'Lindelaan',
                    0172 => 'Lissenweg',
                    0137 => 'Lodewijk De Vochtlaan',
                    0005 => 'Lodewijk Engelbertus Van Arenbergplein',
                    0081 => 'Léon Schreursvest',
                    0091 => 'Matadilaan',
                    0058 => 'Mezenlaan',
                    0059 => 'Middelweg',
                    0214 => 'Mijlboomweg',
                    0106 => 'Milseweg',
                    0061 => 'Naamsesteenweg',
                    0062 => 'Nachtegalenstraat',
                    0207 => 'Neringenweg',
                    0174 => 'Nieuwe Kerkhofdreef',
                    0166 => 'Nieuwedreef',
                    0211 => 'Ondernemingenweg',
                    0213 => 'Ormendaalpad',
                    0028 => 'Oud-Heverleestraat',
                    0119 => 'Oude Nijvelseweg',
                    0064 => 'Pakenstraat',
                    0065 => 'Parkbosstraat',
                    0066 => 'Parkdallaan',
                    0163 => 'Parnassusbergdreef',
                    0069 => 'Pater Perquylaan',
                    0037 => 'Paul van Ostaijenlaan',
                    0203 => 'Petrusberg',
                    0217 => 'Philipssite',
                    0075 => 'Pieter De Somerlaan',
                    0070 => 'Pleinstraat',
                    0072 => 'Populierenlaan',
                    0175 => 'Praegeweg',
                    0022 => 'Prins de Lignestraat',
                    0071 => 'Prinses Lydialaan',
                    0073 => 'Priorijlaan',
                    0074 => 'Prosperdreef',
                    0076 => 'Raalbeeklaan',
                    0124 => 'Reeboklaan',
                    0144 => 'Renaat Veremanslaan',
                    0135 => 'René De Clercqlaan',
                    0210 => 'Romeinse straat',
                    0077 => 'Rotspoel',
                    0078 => 'Rotspoelstraat',
                    0176 => 'Rozenberg',
                    0080 => 'Saffranenbergstraat',
                    0177 => 'Settekensstraat',
                    0082 => 'Sint-Jansbergsesteenweg',
                    0083 => 'Sint-Jorislaan',
                    0060 => 'Sint-Lambertusstraat',
                    0112 => 'Sint-Reneldislaan',
                    0113 => 'Sint-Reneldisplein',
                    0130 => 'Slagmaaldelle',
                    0084 => 'Sparrendreef',
                    0104 => 'Spoorwegstraat',
                    0035 => 'Steengroevenlaan',
                    0204 => 'Stenenkruis',
                    0216 => 'Studentenwijk Arenberg',
                    0153 => 'Technologielaan',
                    0085 => 'Ter Elstlaan',
                    0040 => 'Terbankstraat',
                    0026 => 'Tereikenlaan',
                    0178 => 'Termunckdreef',
                    0086 => 'Termunckstraat',
                    0087 => 'Tervuursesteenweg',
                    0088 => 'Tervuursevest',
                    0089 => 'Tiensesteenweg',
                    0090 => 'Tivolistraat',
                    0149 => 'Toverberg',
                    0150 => 'Twaalfbunder',
                    0092 => 'Tweekleinewegenstraat',
                    0167 => 'Valseweg',
                    0165 => 'Van Harcourtdreef',
                    0146 => 'Veilingweg',
                    0095 => 'Veldstraat',
                    0096 => 'Verbindingslaan',
                    0158 => 'Vijfbunderstraat',
                    0159 => 'Vinkenbosstraat',
                    0097 => 'Vinkenlaan',
                    0098 => 'Vlietstraat',
                    0173 => 'Vloedgracht',
                    0132 => 'Voervalleilaan',
                    0179 => 'Vogelzang',
                    0099 => 'Volhardingslaan',
                    0100 => 'Voordelaan',
                    0101 => 'Waversebaan',
                    0103 => 'Wijngaardlaan',
                    0093 => 'Willem Vanden Abeelelaan',
                    0019 => 'Willem de Croylaan',
                    0102 => 'Withoflaan',
                    0180 => 'Zeepweg',
                    0107 => 'Zegelaan',
                    0108 => 'Zwaluwenlaan',
                ),
            ),
            array(
                'name'    => 'Kessel-Lo',
                'postal'  => '3010',
                'streets' => array(
                    4087 => '',
                    3001 => 'Aarschotsesteenweg',
                    2003 => 'Abdij Vlierbeek',
                    3150 => 'Acaciaplein',
                    3151 => 'Acaciastraat',
                    1004 => 'Achturenstraat',
                    2174 => 'Alberdingk Thijmlaan',
                    4198 => 'Albert De Jonghestraat',
                    2095 => 'Albrecht Rodenbachstraat',
                    2096 => 'Alfons Roelandtsstraat',
                    4120 => 'August Vermeylenlaan',
                    2044 => 'Bareelweg',
                    1023 => 'Baron August de Becker-Remyplein',
                    1063 => 'Beemdenpad',
                    2008 => 'Beemdenstraat',
                    3068 => 'Begijnenberg',
                    2009 => 'Benedictijnenlaan',
                    3073 => 'Bergpad',
                    3011 => 'Bergstraat',
                    5045 => 'Beverloopad',
                    1018 => 'Bijendreef',
                    2175 => 'Blokweg',
                    2043 => 'Boerenkrijglaan',
                    2012 => 'Borstelsstraat',
                    3013 => 'Boskouter',
                    4014 => 'Boulevardstraat',
                    5101 => 'Bovenloweg',
                    1015 => 'Broederlijkheidstraat',
                    2018 => 'Broekweg',
                    1027 => 'Brugbergpad',
                    2017 => 'Bruineveld',
                    2019 => 'Bruineveldpad',
                    1185 => 'Cristianlaan',
                    2146 => 'Dennenboslaan',
                    1024 => 'Diestsesteenweg',
                    1025 => 'Dijledreef',
                    4122 => 'Distelvinkenstraat',
                    3016 => 'Domeinstraat',
                    4026 => 'Don Boscolaan',
                    3152 => 'Doornbergpad',
                    3170 => 'Douaneweg',
                    3162 => 'Duchesnelaan',
                    4027 => 'Duivenstraat',
                    1070 => 'Désiré Mellaertsstraat',
                    3153 => 'Edelzangerslaan',
                    3154 => 'Eendenpad',
                    4029 => 'Eeuwfeeststraat',
                    5030 => 'Eikenboslaan',
                    1031 => 'Elfnovemberlaan',
                    2179 => 'Emiel Vlieberghlaan',
                    1109 => 'Ernest Solvaystraat',
                    4093 => 'Eugeen Vanhoorenbekelaan',
                    1028 => 'Eénmeilaan',
                    3147 => 'Fazantenlaan',
                    3168 => 'Formatie',
                    2073 => 'Frans Nackaertsplein',
                    2074 => 'Frans Nackaertsstraat',
                    4102 => 'Franz Schollaertstraat',
                    2076 => 'Garestalaan',
                    4089 => 'Gaston Eyskenslaan',
                    1033 => 'Gelijkheidstraat',
                    2034 => 'Gemeenteplein',
                    1035 => 'Gemeentestraat',
                    3012 => 'Genadeweg',
                    1037 => 'Gezondheidstraat',
                    4038 => 'Grensstraat',
                    3038 => 'Groddeveldweg',
                    3039 => 'Groddeweg',
                    4036 => 'Guido Gezellelaan',
                    2042 => 'Guldensporenlaan',
                    5043 => 'Heidebergstraat',
                    5044 => 'Heidebloempad',
                    3156 => 'Heikneuterlaan',
                    2021 => 'Herbeemdpad',
                    2045 => 'Herfstlaan',
                    4143 => 'Herman Teirlincklaan',
                    3066 => 'Hertendries',
                    2046 => 'Heuvelhof',
                    1047 => 'Heuvelstraat',
                    2048 => 'Holsbeeksesteenweg',
                    4178 => 'Hugo Verriestlaan',
                    3190 => 'Hulsberg',
                    1139 => 'Ijzerenwegstraat',
                    2022 => 'Jan Davidtsstraat',
                    3201 => 'Jan Van Bouwelstraat',
                    4118 => 'Jan Vandeveldelaan',
                    1049 => 'Jeugdplein',
                    1050 => 'Jeugdstraat',
                    4021 => 'Jozef Deveusterlaan',
                    1087 => 'Jozef Pierrestraat',
                    1131 => 'Jozef Wautersstraat',
                    5156 => 'Kamperfoeliepad',
                    5155 => 'Kamperfoelieweg',
                    5186 => 'Kapellekensweg',
                    3148 => 'Karekietenlaan',
                    1105 => 'Karel Schurmansstraat',
                    3158 => 'Katjeswilgenlaan',
                    1051 => 'Kerkstraat',
                    4051 => 'Kerselarenstraat',
                    3014 => 'Kesselbergpad',
                    3159 => 'Kesselbergplein',
                    3160 => 'Kesseldallaan',
                    3074 => 'Kesselpad',
                    3161 => 'Kesselsteinplein',
                    3196 => 'Kesselveld',
                    4041 => 'Klein-Rijselstraat',
                    3052 => 'Kloosterbosstraat',
                    2178 => 'Kloosterdijkpad',
                    5162 => 'Kluisdelle',
                    3069 => 'Koestaart',
                    4053 => 'Koetsweg',
                    4005 => 'Koning Albertlaan',
                    4006 => 'Koning Albertplein',
                    4007 => 'Koningin Astridlaan',
                    2032 => 'Koningin Fabiolalaan',
                    3054 => 'Koningsstraat',
                    4055 => 'Korenstraat',
                    2057 => 'Kortrijksestraat',
                    1183 => 'Krakaulaan',
                    1184 => 'Krakauplein',
                    3189 => 'Kriekenbergweg',
                    1058 => 'Landbouwstraat',
                    5059 => 'Lange Lostraat',
                    2078 => 'Laurent-Benoit Dewezlaan',
                    3061 => 'Leming',
                    3142 => 'Lemingberg',
                    1062 => 'Lentedreef',
                    2010 => 'Leopold Beosierlaan',
                    2098 => 'Leopold Ruelensstraat',
                    1064 => 'Leuvensestraat',
                    3163 => 'Libelpad',
                    3040 => 'Liemingenstraat',
                    4072 => 'Lijsterlaan',
                    1066 => 'Lindensestraat',
                    5164 => 'Lobergenbos',
                    5067 => 'Lodreef',
                    1188 => 'Lolanden',
                    5047 => 'Lopad',
                    5165 => 'Losbergenlaan',
                    4084 => 'Louis Pasteurwijk',
                    3165 => 'Lovenarenbroek',
                    1068 => 'Lovensveldstraat',
                    2058 => 'Lovensvoetpad',
                    2093 => 'Marie-Elisabeth Belpairestraat',
                    1069 => 'Martelarenlaan',
                    3192 => 'Martellekensweg',
                    3065 => 'Meesbergpad',
                    2016 => 'Molenbeekpad',
                    2071 => 'Molenstraat',
                    2145 => 'Molenveldlaan',
                    2166 => 'Molenveldplein',
                    3067 => 'Musbergpad',
                    2176 => 'Negenbunderspad',
                    4076 => 'Onafhankelijkheidsstraat',
                    4077 => 'Ontvoogdingstraat',
                    1078 => 'Onze-Toevluchtstraat',
                    3195 => 'Op de Vliet',
                    1079 => 'Opvoedingstraat',
                    4141 => 'Ortolanenstraat',
                    1056 => 'Oude Diestsesteenweg',
                    4080 => 'Overwinningstraat',
                    1082 => 'Partisanenstraat',
                    5083 => 'Pasteelsblokweg',
                    2149 => 'Pastoor Eeckelaerslaan',
                    4065 => 'Pater Lievenslaan',
                    1085 => 'Paternosterstraat',
                    3167 => 'Patrijzenlaan',
                    4201 => 'Pellenbergstraat',
                    4009 => 'Peter Benoitlaan',
                    2079 => 'Peter Scribslaan',
                    4075 => 'Pieter Nollekensstraat',
                    2075 => 'Pieter Paradaenslaan',
                    4088 => 'Platte Lostraat',
                    1112 => 'Poortveldstraat',
                    4090 => 'Predikherenberg',
                    4020 => 'Priester Daensstraat',
                    1092 => 'Prins-Regentlaan',
                    1093 => 'Prins-Regentplein',
                    2091 => 'Raadhuislaan',
                    2094 => 'Rerum Novarumlaan',
                    1117 => 'Richard Valvekensstraat',
                    3169 => 'Rietgors',
                    4170 => 'Romain Rollandstraat',
                    1097 => 'Rondestraat',
                    5042 => 'Rozenpad',
                    2099 => 'Ruiterslaan',
                    2081 => 'Rustoordlaan',
                    1100 => 'Schakellaan',
                    5046 => 'Scheivoorpad',
                    2103 => 'Schoolbergenstraat',
                    4104 => 'Schoolstraat',
                    4202 => 'Sint-Martinusberg',
                    3105 => 'Slangenpad',
                    3106 => 'Slangenstraat',
                    1107 => 'Smidsestraat',
                    3072 => 'Smokkelweg',
                    3108 => 'Sneppenstraat',
                    1110 => 'Spaarstraat',
                    3173 => 'Sparrenboslaan',
                    1118 => 'Sportpleinpad',
                    4091 => 'Spreeuwenstraat',
                    2063 => 'Stadionlaan',
                    4092 => 'Steenbakkerijstraat',
                    4111 => 'Stijn Streuvelslaan',
                    3070 => 'Sukkelpad',
                    3055 => 'Sypestraat',
                    1186 => 'Tarweschoof',
                    2184 => 'Thomas Woodrow Wilsonlaan',
                    4113 => 'Tiensesteenweg',
                    1114 => 'Tiensevest',
                    2116 => 'Toekomstpad',
                    2115 => 'Toekomststraat',
                    4116 => 'Trolieberg',
                    5175 => 'Troliebergplein',
                    3197 => 'Tweebunders',
                    4203 => 'Uitbreidingslaan',
                    2124 => 'Van Rodestraat',
                    3176 => 'Varenspad',
                    2177 => 'Veeweidelaan',
                    3193 => 'Velderblok',
                    5187 => 'Veldovenweg',
                    3037 => 'Veldweg',
                    3071 => 'Verbrandenbos',
                    4119 => 'Verenigingstraat',
                    4204 => 'Vertommensberg',
                    1121 => 'Verzoeningstraat',
                    2129 => 'Vijverlaan',
                    2123 => 'Vlierbeekgang',
                    2002 => 'Vlierbeeklaan',
                    5125 => 'Vosseweg',
                    1126 => 'Vredeplein',
                    1127 => 'Vredestraat',
                    1128 => 'Vrijheidstraat',
                    2144 => 'Warandelaan',
                    1130 => 'Waterleidingstraat',
                    3180 => 'Waterlelielaan',
                    3191 => 'Waterlelieplein',
                    2132 => 'Weergalmlaan',
                    1133 => 'Weerstandlaan',
                    1134 => 'Werkhuizenstraat',
                    3182 => 'Wielewaallaan',
                    3199 => 'Wijkweg',
                    3138 => 'Wijnbergenstraat',
                    3194 => 'Wilderbos',
                    3183 => 'Wildvogelpad',
                    3200 => 'Wilgenhof',
                    1019 => 'Willem Coosemansstraat',
                    5168 => 'Willem Quarrélaan',
                    3135 => 'Wilselsesteenweg',
                    5136 => 'Wimmershof',
                    5185 => 'Wimmershofpad',
                    1137 => 'Wipstraat',
                    2020 => 'Witte-Vrouwenpad',
                    5140 => 'Zavelstraat',
                    1187 => '\'t Pachthof',
                ),
            ),
            array(
                'name'    => 'Korbeek-Lo',
                'postal'  => '3000',
                'streets' => array(
                    7111 => 'De vier vaantjes',
                ),
            ),
            array(
                'name'    => 'Leuven',
                'postal'  => '3000',
                'streets' => array(
                    5161 => '',
                    6014 => 'Achter de Latten',
                    4020 => 'Adolphe Bastinstraat',
                    4071 => 'Albert Giraudstraat',
                    4010 => 'Albrechtplein',
                    2192 => 'Alfons Smetsplein',
                    6012 => 'Amerikalaan',
                    3224 => 'Andreas Vesaliusstraat',
                    1010 => 'Ankerstraat',
                    2010 => 'Arendstraat',
                    2140 => 'Arnould Nobelstraat',
                    4041 => 'Arthur De Greefstraat',
                    1011 => 'Asstraat',
                    1012 => 'Augustijnenstraat',
                    6020 => 'Balsembloemhof',
                    5020 => 'Bankstraat',
                    1051 => 'Baron d\' Eynattenstraat',
                    5300 => 'Beursgang',
                    6022 => 'Bieststraat',
                    5022 => 'Biezenstraat',
                    1300 => 'Blauwputgang',
                    2020 => 'Blijde-Inkomststraat',
                    5301 => 'Bloemenberggang',
                    3020 => 'Boekhandelstraat',
                    2021 => 'Bogaardenstraat',
                    2022 => 'Bondgenotenlaan',
                    3021 => 'Brabançonnestraat',
                    6023 => 'Brouwersstraat',
                    6024 => 'Brusselsesteenweg',
                    5023 => 'Brusselsestraat',
                    6025 => 'Burchtstraat',
                    2023 => 'Burgemeestersstraat',
                    1301 => 'Busleidengang',
                    3300 => 'Cansgang',
                    0000 => 'Cardenberch',
                    7030 => 'Casablancalaan',
                    3041 => 'Charles Deberiotstraat',
                    4031 => 'Collegeberg',
                    4130 => 'Constantin Meunierstraat',
                    6031 => 'Craenendonck',
                    2040 => 'Dagobertstraat',
                    7040 => 'Dalemhof',
                    5303 => 'Daneelsgang',
                    3042 => 'Dekenstraat',
                    6043 => 'Den Boschsingel',
                    1043 => 'Diestsepoort',
                    1040 => 'Diestsestraat',
                    1041 => 'Diestsevest',
                    6010 => 'Dirk Boutslaan',
                    6042 => 'Donkerstraat',
                    4042 => 'Drie-Engelenberg',
                    5040 => 'Drinkwaterstraat',
                    7041 => 'Duivelsweg',
                    5180 => 'Edouard Remyvest',
                    3221 => 'Edward Van Evenstraat',
                    3050 => 'Eikstraat',
                    4304 => 'Elzasgang',
                    3130 => 'Emile Mathieustraat',
                    4220 => 'Emile Van Arenberghstraat',
                    1050 => 'Engels Plein',
                    2181 => 'Erasmusplein',
                    7051 => 'Escoriallaan',
                    7052 => 'Esplanadelaan',
                    4070 => 'Eugène Gilbertstraat',
                    3040 => 'Familie de Bayostraat',
                    1193 => 'Ferdinand Smoldersplein',
                    6060 => 'Fonteinstraat',
                    4142 => 'Frans Nensstraat',
                    4223 => 'Frans Vermeylenstraat',
                    6013 => 'Franz Tielemanslaan',
                    3122 => 'Frederik Lintsstraat',
                    6070 => 'Galgebergstraat',
                    3070 => 'Geldenaaksevest',
                    5070 => 'Gijzelaarsstraat',
                    3161 => 'Gildenstraat',
                    6071 => 'Glasblazerijstraat',
                    5071 => 'Goudsbloemstraat',
                    4050 => 'Grasmushof',
                    5304 => 'Groefgang',
                    5073 => 'Groefplein',
                    5072 => 'Groefstraat',
                    4021 => 'Groot Begijnhof',
                    6073 => 'Grote Markt',
                    3220 => 'Gérard Vander Lindenstraat',
                    3301 => 'Haaggang',
                    1080 => 'Halfmaartstraat',
                    4300 => 'Hallengang',
                    6080 => 'Halvestraat',
                    6165 => 'Hambrugpad',
                    2300 => 'Hanengang',
                    5080 => 'Heilige-Geeststraat',
                    4032 => 'Hendrik Consciencestraat',
                    3180 => 'Henri Regastraat',
                    2080 => 'Herbert Hooverplein',
                    5081 => 'Herestraat',
                    5082 => 'Hertstraat',
                    6305 => 'Het Torentje',
                    7080 => 'Hoegaardsestraat',
                    3302 => 'Hofgang',
                    3080 => 'Hogeschoolplein',
                    5083 => 'Hogestraat',
                    7081 => 'Hoogland',
                    5305 => 'Horengang',
                    5090 => 'Ierse-Predikherenstraat',
                    7250 => 'Ijzerenpoortstraat',
                    4090 => 'Isabellaplein',
                    2191 => 'Jan Stasstraat',
                    1131 => 'Jan-Pieter Minckelersstraat',
                    4022 => 'Janseniusstraat',
                    5302 => 'Jean Bulenswijk',
                    5021 => 'Jean-Baptiste Ectorsstraat',
                    1224 => 'Jean-Baptiste Van Monsstraat',
                    6015 => 'Joanna-Maria Artoisplein',
                    1100 => 'Jodenstraat',
                    2100 => 'Jozef II-straat',
                    3226 => 'Jozef Vounckplein',
                    2101 => 'Justus Lipsiusstraat',
                    5110 => 'Kaboutermansstraat',
                    4110 => 'Kapucijnenvoer',
                    3131 => 'Kardinaal Mercierplein',
                    1110 => 'Kardinaalstraat',
                    1111 => 'Karel van Lotharingenstraat',
                    5111 => 'Kartuizersstraat',
                    6111 => 'Keizersberg',
                    4112 => 'Kiekenstraat',
                    6021 => 'Klein Begijnhof',
                    1112 => 'Kolveniershof',
                    4023 => 'Koning Boudewijnlaan',
                    2121 => 'Koning Leopold I--straat',
                    7050 => 'Koningin Elisabethlaan',
                    2179 => 'Korbeeklogang',
                    7110 => 'Korbeekoase',
                    4113 => 'Kortestraat',
                    4114 => 'Krakenstraat',
                    4115 => 'Kroegberg',
                    5112 => 'Kruisstraat',
                    6159 => 'La Vignette',
                    3120 => 'Lakenweversstraat',
                    4120 => 'Lavorenberg',
                    6164 => 'Leerlooierijstraat',
                    6120 => 'Lei',
                    2221 => 'Leopold Vanderkelenstraat',
                    2122 => 'Lepelstraat',
                    3303 => 'Liergang',
                    1020 => 'Lombaardenstraat',
                    2132 => 'Louis Melsensstraat',
                    7259 => 'Ludovicus Zamenhofstraat',
                    4030 => 'Léon Colinslaan',
                    6121 => 'Lüdenscheidsingel',
                    2060 => 'Maarschalk Fochplein',
                    1130 => 'Margarethaplein',
                    4224 => 'Maria Van Belstraat',
                    2130 => 'Maria-Theresiastraat',
                    2131 => 'Martelarenplein',
                    1021 => 'Mathias Van den Gheynlaan',
                    6040 => 'Mathieu de Layensplein',
                    6130 => 'Mechelsesteenweg',
                    6131 => 'Mechelsestraat',
                    6132 => 'Mechelsevest',
                    7132 => 'Meerdaalboslaan',
                    6134 => 'Mercatorpad',
                    7130 => 'Minneveld',
                    6301 => 'Mispelaarsgang',
                    7133 => 'Molweg',
                    3132 => 'Monnikenstraat',
                    2120 => 'Monseigneur Ladeuzeplein',
                    5222 => 'Monseigneur Van Waeyenberghlaan',
                    3133 => 'Muntstraat',
                    2134 => 'Mussenstraat',
                    5131 => 'Muurkruidstraat',
                    4140 => 'Naamsestraat',
                    4141 => 'Naamsevest',
                    1140 => 'Nerviërsstraat',
                    6133 => 'Nieuwe Mechelsesteenweg',
                    5140 => 'Noormannenstraat',
                    7141 => 'Norbertijnerweg',
                    7150 => 'Oaselaan',
                    5150 => 'Onze-Lieve-Vrouwstraat',
                    2129 => 'Oostertunnel',
                    1302 => 'Oppendorpgang',
                    4150 => 'Oude Markt',
                    6150 => 'Oude Rondelaan',
                    7151 => 'Oudebaan',
                    7262 => 'Overlo',
                    4160 => 'Parijsstraat',
                    3160 => 'Parkstraat',
                    4040 => 'Pater Damiaanplein',
                    6041 => 'Paul Delvauxwijk',
                    3121 => 'Paul Lebrunstraat',
                    5160 => 'Pelgrimstraat',
                    6160 => 'Penitentienenstraat',
                    6161 => 'Pensstraat',
                    6162 => 'Pereboomstraat',
                    6163 => 'Petermannenstraat',
                    6302 => 'Peterseliegang',
                    7160 => 'Philipslaan',
                    2220 => 'Pierre Joseph Van Benedenstraat',
                    3223 => 'Pierre Joseph Verhaghenstraat',
                    5030 => 'Pieter Coutereelstraat',
                    4176 => 'Pieter Van Dalepad',
                    5162 => 'Predikerinnenstraat',
                    3162 => 'Prelatenstraat',
                    5307 => 'Prentengang',
                    4161 => 'Prosper Poulletlaan',
                    2161 => 'Provincie-esplanade',
                    2160 => 'Provincieplein',
                    2133 => 'Quinten Metsysplein',
                    4180 => 'Ramberg',
                    4178 => 'Ramenstraatje',
                    6030 => 'Raoul Claesstraat',
                    3304 => 'Rapengang',
                    4301 => 'Rattemanspoort',
                    2180 => 'Ravenstraat',
                    1180 => 'Redersstraat',
                    4181 => 'Redingenhof',
                    4182 => 'Redingenstraat',
                    4221 => 'Remi Vandervaerenlaan',
                    5181 => 'Rennessingel',
                    6180 => 'Ridderstraat',
                    1182 => 'Rijdende-Artillerielaan',
                    1181 => 'Rijschoolstraat',
                    4029 => 'Rixvonderendijk',
                    4175 => 'Ruteriuspad',
                    2190 => 'Savoyestraat',
                    4190 => 'Schapenstraat',
                    3190 => 'Schepenenstraat',
                    1190 => 'Schrijnmakersstraat',
                    5190 => 'Sellekensstraat',
                    5191 => 'Sint-Annastraat',
                    4191 => 'Sint-Antoniusberg',
                    5192 => 'Sint-Barbarastraat',
                    4192 => 'Sint-Beggaberg',
                    1197 => 'Sint-Geertruiabdij',
                    5193 => 'Sint-Hubertusstraat',
                    5194 => 'Sint-Jacobsplein',
                    1191 => 'Sint-Maartensdal',
                    1192 => 'Sint-Maartenstraat',
                    3191 => 'Sint-Michielsstraat',
                    4302 => 'Sint-Quintensberg',
                    5195 => 'Sint-Servatiusstraat',
                    4193 => 'Slachthuislaan',
                    6192 => 'Sluisstraat',
                    1198 => 'Snoekenpad',
                    7190 => 'Spaanse-Burchtlaan',
                    7191 => 'Spaanse-Kroonlaan',
                    7192 => 'Spaanse-Lindelaan',
                    3194 => 'Standonckstraat',
                    1194 => 'Stapelhuisstraat',
                    2303 => 'Straatjesgang',
                    1195 => 'Strijdersstraat',
                    4200 => 'Ten Hovelaan',
                    6201 => 'Ten Wijngaard',
                    6200 => 'Ter Boelhage',
                    5200 => 'Tervuursesteenweg',
                    5201 => 'Tervuursestraat',
                    5202 => 'Tervuursevest',
                    5203 => 'Tessenstraat',
                    2304 => 'Theresianengang',
                    7200 => 'Tiensesteenweg',
                    2200 => 'Tiensestraat',
                    2201 => 'Tiensevest',
                    5232 => 'Tolhuizenstraat',
                    3193 => 'Tomveldstraat',
                    6026 => 'Tramweg',
                    4303 => 'Trapgang',
                    1042 => 'Tweewatersstraat',
                    1220 => 'Vaartkom',
                    1221 => 'Vaartstraat',
                    6223 => 'Valkenplein',
                    6306 => 'Valkerijgang',
                    3222 => 'Van \'t Sestichstraat',
                    1223 => 'Vanden Tymplestraat',
                    5310 => 'Verbrande Poort',
                    4222 => 'Verkortingstraat',
                    6222 => 'Verloren Kost',
                    5311 => 'Vestinggang',
                    7220 => 'Villapark',
                    1225 => 'Vismarkt',
                    1226 => 'Vissersstraat',
                    2041 => 'Vital Decosterstraat',
                    3225 => 'Vlamingenstraat',
                    7221 => 'Vlinderlaan',
                    4225 => 'Volmolenlaan',
                    5220 => 'Voorzorgstraat',
                    5221 => 'Vriesenhof',
                    1227 => 'Vuurkruisenlaan',
                    5230 => 'Waaistraat',
                    5231 => 'Wagenweg',
                    6230 => 'Wandelingstraat',
                    1230 => 'Weidestraat',
                    3230 => 'Weldadigheidsstraat',
                    1231 => 'Werkmanstraat',
                    5233 => 'Wieringstraat',
                    6231 => 'Wijnpersstraat',
                    2230 => 'Willemsstraat',
                    3231 => 'Windmolenstraat',
                    3232 => 'Windmolenveldstraat',
                    7120 => 'Wittehoevelaan',
                    1303 => 'Wolvengang',
                    4177 => 'Wolvepoortpad',
                    6309 => 'Zandgang',
                    7260 => 'Zavelberg',
                    4260 => 'Zeelstraat',
                    1260 => 'Zeilstraat',
                    5260 => 'Zevenslapersstraat',
                    7261 => 'Ziekelingenstraat',
                    5312 => 'Zongang',
                    1261 => 'Zoutstraat',
                    4261 => 'Zwartzusterstraat',
                    6190 => '\'s Hertogenlaan',
                    6191 => '\'s Hertogenwijngaard',
                    3192 => '\'s-Meiersstraat',
                    4179 => 'de Angelispad',
                ),
            ),
            array(
                'name'    => 'Wijgmaal',
                'postal'  => '3018',
                'streets' => array(
                    6001 => 'Acht-Meistraat',
                    6002 => 'Baron Descampslaan',
                    6038 => 'Bloemersweg',
                    6004 => 'Casinolaan',
                    6005 => 'Dijlebrug',
                    6006 => 'Dongelsplein',
                    6007 => 'Driesstraat',
                    6008 => 'Gebroeders Tassetstraat',
                    6009 => 'Groeningestraat',
                    6010 => 'Hambosstraat',
                    6011 => 'Haverstraat',
                    6013 => 'Korte Dolagestraat',
                    6014 => 'Kroonstraat',
                    6015 => 'Langenbos',
                    6037 => 'Lentelaan + gedeelte',
                    6016 => 'Meerstraat',
                    6017 => 'Michielstraat',
                    6019 => 'Nieuwstraat',
                    6020 => 'Pastoor Bellonstraat',
                    6021 => 'Pikkelstraat',
                    6022 => 'Privaatweg',
                    6003 => 'Remy Alloingstraat',
                    6023 => 'Remylaan',
                    6024 => 'Rietensplein',
                    6025 => 'Rotselaarsesteenweg',
                    6026 => 'Rozengaard',
                    6027 => 'Sint-Hadrianusstraat',
                    6012 => 'Spoorstraat',
                    6028 => 'Stationsstraat',
                    6029 => 'Steenakkerstraat',
                    6030 => 'Torenstraat',
                    6031 => 'Ursulinenstraat',
                    6032 => 'Vaartdijk',
                    6033 => 'Wakkerzeelsebaan',
                    6039 => 'Watermolenpad',
                    6018 => 'Watermolenstraat',
                    6034 => 'Weduwenrij',
                    6035 => 'Wijgmaalbroek',
                    6036 => 'Wijveld',
                ),
            ),
            array(
                'name'    => 'Wilsele',
                'postal'  => '3012',
                'streets' => array(
                    0077 => '',
                    0095 => 'Aambeeldstraat',
                    0001 => 'Aarschotsesteenweg',
                    0003 => 'Achttienaprillaan',
                    0148 => 'Achttienaprilpad',
                    0119 => 'Albert Woutersstraat',
                    0036 => 'Alfons Fierensstraat',
                    0089 => 'Alfons Stesselstraat',
                    0112 => 'Alfons Van Geelstraat',
                    0108 => 'Alfons Verbovenstraat',
                    0034 => 'André Emondstraat',
                    0064 => 'Armand Meyswijk',
                    0004 => 'Bavenhofstraat',
                    0006 => 'Berg Bogaertlaan',
                    0007 => 'Berghoekstraat',
                    0140 => 'Bermpad',
                    0008 => 'Bleydenberglaan',
                    0147 => 'Bleydenbergpad',
                    0009 => 'Boomgaardstraat',
                    0010 => 'Bornestraat',
                    0011 => 'Bosstraat',
                    0012 => 'Braambessenlaan',
                    0013 => 'Brandenstraat',
                    0122 => 'Brandweg / Tunnelstraat (deel)',
                    0132 => 'Broekhout',
                    0016 => 'Brugveldstraat',
                    0017 => 'Bunsbeekstraat',
                    0018 => 'Bunswijkstraat',
                    0125 => 'Centrumstraat',
                    3166 => 'Compostweg',
                    0139 => 'Crabeelsweg',
                    0024 => 'De Roestestraat',
                    0138 => 'Dijkstraat',
                    0025 => 'Draaklaan',
                    0015 => 'Durasstraat',
                    0027 => 'Eegstraat',
                    0134 => 'Eegveld',
                    0028 => 'Eendebroekstraat',
                    0091 => 'Egelantierlaan',
                    0029 => 'Eikenbergstraat',
                    0014 => 'Eksterveldstraat',
                    0030 => 'Elektriciteitswijk',
                    0019 => 'Englebert Carleerlaan',
                    0085 => 'Ferdinand Perdieusstraat',
                    0113 => 'Fortlaan',
                    0023 => 'François Demarsinstraat',
                    0038 => 'Gasthuisbosstraat',
                    0048 => 'Hagelandstraat',
                    0040 => 'Hasselbroekbaan',
                    0021 => 'Henri Corbeelsplein',
                    0032 => 'Henri Elsenwijk',
                    0061 => 'Henricus Bosmanslaan',
                    0041 => 'Herentsesteenweg',
                    0043 => 'Hoge-Berglaan',
                    0045 => 'Hoogveldweg',
                    0046 => 'Invalidenlaan',
                    0146 => 'Jaagpad',
                    0106 => 'Jan Van Avondtstraat',
                    0099 => 'Jan-Baptist Vanderelststraat',
                    0137 => 'Jef Scherensstraat',
                    0087 => 'Joseph Ravoetstraat',
                    0079 => 'Jules Persoonsstraat',
                    0069 => 'Juliaan Haestweg',
                    0047 => 'Kapellelaan',
                    0049 => 'Kerkhofweg',
                    0051 => 'Kessel-Losesteenweg',
                    0052 => 'Kleine-Huizenstraat',
                    0141 => 'Koksijdepad',
                    0022 => 'Koksijdewijk',
                    0005 => 'Kolonel Begaultlaan',
                    0044 => 'Korte Holsbeeksesteenweg',
                    0053 => 'Kwadenhoekstraat',
                    0054 => 'Lange-Beemdenlaan',
                    0055 => 'Langekant',
                    0056 => 'Langenhofstraat',
                    0057 => 'Langerijlaan',
                    0060 => 'Leibeekstraat',
                    0142 => 'Lijnloperspad',
                    0145 => 'Limburglaan',
                    0100 => 'Louis Tielemanswijk',
                    0120 => 'Louis Woutersstraat',
                    0026 => 'Marguerite Lefèvrelaan',
                    0020 => 'Marie Clootsstraat',
                    0062 => 'Mechelsesteenweg',
                    0063 => 'Meibloemweg',
                    0066 => 'Mothstraat',
                    0068 => 'Natuurvriendenlaan',
                    0070 => 'Nieuwe Bornestraat',
                    0071 => 'Nieuwe Prinsstraat',
                    0058 => 'Oosterhemstraat',
                    0072 => 'Oude Aarschotseweg',
                    0074 => 'Oude Wakkerzeelsebaan',
                    0075 => 'Oudstrijderslaan',
                    0076 => 'Overloopstraat',
                    0035 => 'Pastoor Eralystraat',
                    0059 => 'Pastoor Legrandstraat',
                    0078 => 'Pastorijweg',
                    0127 => 'Perkstraat',
                    0067 => 'Petrus Geeraertslaan',
                    0080 => 'Plankenbosstraat',
                    0126 => 'Poelstraat',
                    0081 => 'Politieke-Gevangenenlaan',
                    0086 => 'Pompstraat',
                    0082 => 'Prinsstraat',
                    0083 => 'Processiestraat',
                    0107 => 'Prosper Vanlangendoncklaan',
                    0084 => 'Puttebroekstraat',
                    0135 => 'René Verbeeckstraat',
                    0131 => 'Ristweg',
                    0088 => 'Roeselbergdal',
                    0128 => 'Rooistraat',
                    0092 => 'Schmaesveldstraat',
                    0093 => 'Schoonzichtlaan',
                    0133 => 'Schorenshof',
                    0094 => 'Schotelveldstraat',
                    0096 => 'Spaarzaamheidstraat',
                    0097 => 'Stadsvest',
                    0129 => 'Straetmanshof',
                    0098 => 'Streekstraat',
                    0101 => 'Tuinstraat',
                    0102 => 'Tunnelstraat',
                    0144 => 'Tunnelweg',
                    0103 => 'Twaalfmeistraat',
                    0105 => 'Valleistraat',
                    0124 => 'Van Calsterenstraat',
                    0118 => 'Van Den Steenstraat',
                    0039 => 'Van der Nootstraat',
                    0109 => 'Verbroederingstraat',
                    0111 => 'Vergezichtlaan',
                    0090 => 'Vierhuizenstraat',
                    0136 => 'Vuntcomplex',
                    0114 => 'Vuntlaan',
                    0143 => 'Vuntpad',
                    3164 => 'Vuntrotonde',
                    0115 => 'Wakkerzeelsebaan',
                    0116 => 'Watervloedstraat',
                    0117 => 'Weggevoerdenstraat',
                    0121 => 'Wijgmaalsesteenweg',
                    0073 => 'Wijk Ouderenvreugd',
                    0130 => 'Woudluchtstraat',
                    0123 => 'Zavelputstraat',
                    0042 => 'Zwanenberglaan',
                ),
            ),
        );

        foreach($cities as $cityData) {
            $city = $this->getEntityManager()
                ->getRepository('CommonBundle\Entity\General\Address\City')
                ->findOneByPostal($cityData['postal']);

            if (null == $city) {
                $city = new City($cityData['postal'], $cityData['name']);
                $this->getEntityManager()->persist($city);
            }

            foreach($cityData['streets'] as $register => $street) {
                $this->getEntityManager()->persist(new Street($city, $register, $street));
            }
        }

        $this->getEntityManager()->flush();
    }
}
