<?php

namespace CommonBundle\Repository\General\Bank\BankDevice;

use CommonBundle\Component\Util\EntityRepository;

/**
 * BankDeviceAmount
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Amount extends EntityRepository
{
}
