<?= $this->broker('partial')->direct('role/partials/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="controller_action">
    <? if ($this->roleCreated): ?>
        <div class="success_message">
            <div class="title">Success</div>
            <div class="content">
                <p>The role was successfully created!</p>
            </div>
        </div>
    <? endif; ?>

    <?= $this->form; ?>
</div>

<aside>
    <div class="sidebox">
        <div class="title">Current Access</div>
        <div class="content">
            
        </div>
    </div>
</aside>