<?= $this->broker('partial')->direct('role/partials/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="controller_action">
    <? if (!$this->roleCreated): ?>
        <?= $this->form; ?>
    <? else: ?>
        <span class="success_message">The role was successfully created!</span>
    <? endif; ?>
</div>

<aside>
    <div class="sidebox">
        <div class="title">Current Access</div>
        <div class="content">
            
        </div>
    </div>
</aside>