<?= $this->partial('partials/role/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<?= $this->form; ?>
</div>

<aside>
    <div class="sidebox">
        <div class="title">Current Access</div>
        <div class="content">
            
        </div>
    </div>
</aside>