<?php

namespace CommonBundle\Repository\General\Organization;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * Unit
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Unit extends EntityRepository
{
    public function findAllActiveQuery()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('u')
            ->from('CommonBundle\Entity\General\Organization\Unit', 'u')
            ->where(
                $query->expr()->eq('u.active', 'true')
            )
            ->orderBy('u.name', 'ASC')
            ->getQuery();

        return $resultSet;
    }

    public function findAllActiveAndDisplayedQuery()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('u')
            ->from('CommonBundle\Entity\General\Organization\Unit', 'u')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('u.active', 'true'),
                    $query->expr()->eq('u.displayed', 'true')
                )
            )
            ->orderBy('u.name', 'ASC')
            ->getQuery();

        return $resultSet;
    }

    public function findAllActiveAndNotDisplayedQuery()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('u')
            ->from('CommonBundle\Entity\General\Organization\Unit', 'u')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('u.active', 'true'),
                    $query->expr()->eq('u.displayed', 'false')
                )
            )
            ->orderBy('u.name', 'ASC')
            ->getQuery();

        return $resultSet;
    }
}
