<?php

namespace QuizBundle\Repository;

/**
 * Tiebreaker
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tiebreaker extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
