<?php

namespace QuizBundle\Repository;

use QuizBundle\Entity\Quiz as QuizEntity;

/**
 * TiebreakerAnswer
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiebreakerAnswer extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * Gets all tiebreaker answers belonging to a quiz
     * @param QuizEntity $quiz The quiz the points must belong to
     */
    public function findAllByQuizQuery(QuizEntity $quiz)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('p')
            ->from('QuizBundle\Entity\TiebreakerAnswer', 'p')
            ->innerJoin('p.tiebreaker', 'tb')
            ->innerJoin('p.team', 't')
            ->where(
                $query->expr()->eq('tb.quiz', ':quiz')
            )
            ->orderBy('tb.order', 'ASC')
            ->setParameter('quiz', $quiz)
            ->getQuery();
    }
}
