<?php

namespace SportBundle\Repository;

use CommonBundle\Entity\General\AcademicYear,
    Doctrine\ORM\EntityRepository;

/**
 * Lap
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lap extends EntityRepository
{
    public function findPrevious(AcademicYear $academicYear, $nbResults = 1)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('l')
            ->from('SportBundle\Entity\Lap', 'l')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('l.academicYear', ':academicYear'),
                    $query->expr()->isNotNull('l.startTime'),
                    $query->expr()->isNotNull('l.endTime')
                )
            )
            ->setParameter('academicYear', $academicYear)
            ->orderBy('l.registrationTime', 'DESC')
            ->setMaxResults($nbResults)
            ->getQuery()
            ->getResult();

        return array_reverse($resultSet);
    }

    public function findCurrent(AcademicYear $academicYear)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('l')
            ->from('SportBundle\Entity\Lap', 'l')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('l.academicYear', ':academicYear'),
                    $query->expr()->isNotNull('l.startTime'),
                    $query->expr()->isNull('l.endTime')
                )
            )
            ->setParameter('academicYear', $academicYear)
            ->orderBy('l.registrationTime', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();

        if (isset($resultSet[0]))
            return $resultSet[0];

        return null;
    }

    public function findNext($nbResults = 1)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('l')
            ->from('SportBundle\Entity\Lap', 'l')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('l.academicYear', ':academicYear'),
                    $query->expr()->isNull('l.startTime'),
                    $query->expr()->isNull('l.endTime')
                )
            )
            ->setParameter('academicYear', $academicYear)
            ->orderBy('l.registrationTime', 'ASC')
            ->setMaxResults($nbResults)
            ->getQuery()
            ->getResult();

        if (1 == $nbResults)
            return isset($resultSet[0]) ? $resultSet[0] : null;

        return $resultSet;
    }

    public function countAll(AcademicYear $academicYear)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('l')
            ->from('SportBundle\Entity\Lap', 'l')
            ->select(
                $query->expr()->count('l.id')
            )
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('l.academicYear', ':academicYear'),
                    $query->expr()->isNotNull('l.startTime'),
                    $query->expr()->isNotNull('l.endTime')
                )
            )
            ->setParameter('academicYear', $academicYear)
            ->getQuery()
            ->getResult();

        return $resultSet[0][1];
    }

    public function countRunners(AcademicYear $academicYear)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('l')
            ->from('SportBundle\Entity\Lap', 'l')
            ->select(
                $query->expr()->countDistinct('l.runner')
            )
            ->where(
                $query->expr()->eq('l.academicYear', ':academicYear')
            )
            ->setParameter('academicYear', $academicYear)
            ->getQuery()
            ->getResult();

        return $resultSet[0][1];
    }
}
