<?php

namespace Litus\Repositories\Users;

use Doctrine\ORM\EntityRepository;

/**
 * UniversityStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversityStatusRepository extends EntityRepository
{
}