<?= $this->partial('partials/article/navigation.phtml', array('currentAction' => 'add')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
    <?= $this->form; ?>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		$('#internal').click(toggleInternal);
		$('#stock').click(toggleStock);
		toggleInternal();
		toggleStock();
	});
	
	function toggleInternal() {
		if ($('#internal').is(':checked'))
			$('#internal_form').show();
		else
			$('#internal_form').hide();
	}
	
	function toggleStock() {
		if ($('#stock').is(':checked')) {
			$('#stock_form').show();
			toggleInternal();
		} else {
			$('#stock_form, #internal_form').hide();
			$('#internal').removeAttr("checked");
		}
	}
</script>