<?php

namespace BrBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Invoice
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Invoice extends EntityRepository
{
}
