<?php

namespace BrBundle\Repository\Cv;

/**
 * Experience
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Experience extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
