<?php
/**
 * Litus is a project by a group of students from the KU Leuven. The goal is to create
 * various applications to support the IT needs of student unions.
 *
 * @author Niels Avonds <niels.avonds@litus.cc>
 * @author Karsten Daemen <karsten.daemen@litus.cc>
 * @author Koen Certyn <koen.certyn@litus.cc>
 * @author Bram Gotink <bram.gotink@litus.cc>
 * @author Dario Incalza <dario.incalza@litus.cc>
 * @author Pieter Maene <pieter.maene@litus.cc>
 * @author Kristof Mariën <kristof.marien@litus.cc>
 * @author Lars Vierbergen <lars.vierbergen@litus.cc>
 * @author Daan Wendelen <daan.wendelen@litus.cc>
 *
 * @license http://litus.cc/LICENSE
 */

namespace SyllabusBundle\Repository;

use CommonBundle\Component\Doctrine\ORM\EntityRepository,
    CommonBundle\Entity\General\AcademicYear,
    SyllabusBundle\Entity\Poc as PocEntity;

/**
 * Group
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Poc extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllQuery()
    {   
        $query = $this->getEntityManager()->createQueryBuilder();
        $resultSet = $query->select('p', 'g')
            ->from('SyllabusBundle\Entity\Poc', 'p')
             ->where(
            )
            ->innerJoin('p.groupId', 'g')
            ->orderBy('g.name', 'ASC')
            ->getQuery();

        return $resultSet;
    }
     /**
     * @param  AcademicYear        $academicYear
     * @return \Doctrine\ORM\Query
     */
    public function findAllByAcademicYearQuery(AcademicYear $academicYear)
    {	
        $query = $this->getEntityManager()->createQueryBuilder();
        $resultSet = $query->select('p','g')
            ->from('SyllabusBundle\Entity\poc', 'p')
            ->where(
                $query->expr()->eq('p.academicYear', ':academicYear')
            )
            ->setParameter('academicYear', $academicYear)
            ->innerJoin('p.groupId','g')
            ->orderBy('g.name','ASC')
            ->getQuery();
        return $resultSet;
    }
  
    


  
}
