<?php
/**
 * Litus is a project by a group of students from the KU Leuven. The goal is to create
 * various applications to support the IT needs of student unions.
 *
 * @author Niels Avonds <niels.avonds@litus.cc>
 * @author Karsten Daemen <karsten.daemen@litus.cc>
 * @author Koen Certyn <koen.certyn@litus.cc>
 * @author Bram Gotink <bram.gotink@litus.cc>
 * @author Dario Incalza <dario.incalza@litus.cc>
 * @author Pieter Maene <pieter.maene@litus.cc>
 * @author Kristof Mariën <kristof.marien@litus.cc>
 * @author Lars Vierbergen <lars.vierbergen@litus.cc>
 * @author Daan Wendelen <daan.wendelen@litus.cc>
 * @author Mathijs Cuppens <mathijs.cuppens@litus.cc>
 * @author Floris Kint <floris.kint@vtk.be>
 *
 * @license http://litus.cc/LICENSE
 */

namespace SyllabusBundle\Repository;

use CommonBundle\Entity\General\AcademicYear;
use SyllabusBundle\Entity\Study\Combination as CombinationEntity;

/**
 * Study
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Study extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @param  AcademicYear $academicYear
     * @return \Doctrine\ORM\Query
     */
    public function findAllByAcademicYearQuery(AcademicYear $academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s', 'c')
            ->from('SyllabusBundle\Entity\Study', 's')
            ->innerJoin('s.combination', 'c')
            ->where(
                $query->expr()->eq('s.academicYear', ':academicYear')
            )
            ->setParameter('academicYear', $academicYear)
            ->orderBy('c.title', 'ASC')
            ->addOrderBy('c.phase', 'ASC')
            ->getQuery();
    }

    /**
     * @param  CombinationEntity $combination
     * @param  AcademicYear      $academicYear
     * @return \SyllabusBundle\Entity\Study
     */
    public function findOneByCombinationAndAcademicYear(CombinationEntity $combination, AcademicYear $academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s')
            ->from('SyllabusBundle\Entity\Study', 's')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('s.academicYear', ':academicYear'),
                    $query->expr()->eq('s.combination', ':combination')
                )
            )
            ->setParameter('academicYear', $academicYear)
            ->setParameter('combination', $combination)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param  AcademicYear $academicYear
     * @return \Doctrine\ORM\Query
     */
    public function findAllByTitleAndAcademicYearQuery($title, AcademicYear $academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s', 'c')
            ->from('SyllabusBundle\Entity\Study', 's')
            ->innerJoin('s.combination', 'c')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('s.academicYear', ':academicYear'),
                    $query->expr()->like($query->expr()->lower('c.title'), ':title')
                )
            )
            ->setParameter('academicYear', $academicYear)
            ->setParameter('title', '%' . strtolower($title) . '%')
            ->orderBy('c.title', 'ASC')
            ->addOrderBy('c.phase', 'ASC')
            ->getQuery();
    }
}
