<?php
return array(
    'ProfBundle\Module'                                   => __DIR__ . '/Module.php',
    'ProfBundle\Component\Controller\ProfController'      => __DIR__ . '/src/Component/Controller/ProfController.php',
    'ProfBundle\Controller\Admin\InstallerController'     => __DIR__ . '/src/Controller/Admin/InstallerController.php',
    'ProfBundle\Controller\Prof\ArticleController'        => __DIR__ . '/src/Controller/Prof/ArticleController.php',
    'ProfBundle\Controller\Prof\ArticleMappingController' => __DIR__ . '/src/Controller/Prof/ArticleMappingController.php',
    'ProfBundle\Controller\Prof\AuthController'           => __DIR__ . '/src/Controller/Prof/AuthController.php',
    'ProfBundle\Controller\Prof\CommentController'        => __DIR__ . '/src/Controller/Prof/CommentController.php',
    'ProfBundle\Controller\Prof\FileController'           => __DIR__ . '/src/Controller/Prof/FileController.php',
    'ProfBundle\Controller\Prof\IndexController'          => __DIR__ . '/src/Controller/Prof/IndexController.php',
    'ProfBundle\Controller\Prof\ProfController'           => __DIR__ . '/src/Controller/Prof/ProfController.php',
    'ProfBundle\Controller\Prof\SubjectController'        => __DIR__ . '/src/Controller/Prof/SubjectController.php',
    'ProfBundle\Entity\Action\Article\Add'                => __DIR__ . '/src/Entity/Action/Article/Add.php',
    'ProfBundle\Entity\Action\Article\Edit\Item'          => __DIR__ . '/src/Entity/Action/Article/Edit/Item.php',
    'ProfBundle\Entity\Action\Article\Edit'               => __DIR__ . '/src/Entity/Action/Article/Edit.php',
    'ProfBundle\Entity\Action\File\Add'                   => __DIR__ . '/src/Entity/Action/File/Add.php',
    'ProfBundle\Entity\Action\File\Remove'                => __DIR__ . '/src/Entity/Action/File/Remove.php',
    'ProfBundle\Entity\Action\Mapping\Add'                => __DIR__ . '/src/Entity/Action/Mapping/Add.php',
    'ProfBundle\Entity\Action\Mapping\Remove'             => __DIR__ . '/src/Entity/Action/Mapping/Remove.php',
    'ProfBundle\Entity\Action'                            => __DIR__ . '/src/Entity/Action.php',
    'ProfBundle\Form\Prof\Article\Add'                    => __DIR__ . '/src/Form/Prof/Article/Add.php',
    'ProfBundle\Form\Prof\Comment\Add'                    => __DIR__ . '/src/Form/Prof/Comment/Add.php',
    'ProfBundle\Form\Prof\File\Add'                       => __DIR__ . '/src/Form/Prof/File/Add.php',
    'ProfBundle\Form\Prof\Mapping\Add'                    => __DIR__ . '/src/Form/Prof/Mapping/Add.php',
    'ProfBundle\Form\Prof\Prof\Add'                       => __DIR__ . '/src/Form/Prof/Prof/Add.php',
    'ProfBundle\Repository\Action\Article\Add'            => __DIR__ . '/src/Repository/Action/Article/Add.php',
    'ProfBundle\Repository\Action\Article\Edit\Item'      => __DIR__ . '/src/Repository/Action/Article/Edit/Item.php',
    'ProfBundle\Repository\Action\Article\Edit'           => __DIR__ . '/src/Repository/Action/Article/Edit.php',
    'ProfBundle\Repository\Action\File\Add'               => __DIR__ . '/src/Repository/Action/File/Add.php',
    'ProfBundle\Repository\Action\File\Remove'            => __DIR__ . '/src/Repository/Action/File/Remove.php',
    'ProfBundle\Repository\Action\Mapping\Add'            => __DIR__ . '/src/Repository/Action/Mapping/Add.php',
    'ProfBundle\Repository\Action\Mapping\Remove'         => __DIR__ . '/src/Repository/Action/Mapping/Remove.php',
    'ProfBundle\Repository\Action'                        => __DIR__ . '/src/Repository/Action.php',
);