<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'overview')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<h1>General</h1>
    <p>Article: <b><?= $this->item->getArticle()->getTitle() . ($this->item->getArticle()->getVersionNumber() != 1 ? ' (v' . $this->item->getArticle()->getVersionNumber() . ')' : ''); ?></b></p>
    <p>Barcode: <b><?= $this->item->getArticle()->getBarcode(); ?></b></p>
	<p>Supplier: <b><?= $this->item->getArticle()->getSupplier()->getName(); ?></b></p>
	<br style="clear:both" />
	<h1>Orders</h1>
	<table class="half_width">
		<tr>
			<td>Total</td>
			<td style="width:30%"><?= $this->item->getTotalOrdered(); ?></td>
		</tr>
		<tr>
			<td>Not delivered</td>
			<td style="width:30%"><?= $this->item->getNumberNotDelivered(); ?></td>
		</tr>
		<tr>
			<td>Queue</td>
			<td style="width:30%"><?= $this->item->getNumberQueueOrder(); ?></td>
		</tr>
	</table>
	<br style="clear:both" />
	<?= $this->orderForm; ?>
	<br style="clear:both" />
	<h1>Deliveries</h1>
	<table class="half_width">
		<tr>
			<td>Total</td>
			<td style="width:30%"><?= $this->item->getTotalDelivered(); ?></td>
		</tr>
	</table>
	<br style="clear:both" />
	<?= $this->deliveryForm; ?>
	<br style="clear:both" />
	<h1>Bookings</h1>
	<table class="half_width">
		<tr>
			<td>Number assigned</td>
			<td style="width:30%"><?= $this->item->getNumberAssigned(); ?></td>
		</tr>
		<tr>
			<td>Number not assigned</td>
			<td style="width:30%"><?= $this->item->getNumberBooked(); ?></td>
		</tr>
	</table>
	<br style="clear:both" />
	<h1>Sales</h1>
	<table class="half_width">
		<tr>
			<td>Total</td>
			<td style="width:30%"><?= $this->item->getNumberSold(); ?></td>
		</tr>
	</table>
	<br style="clear:both" />
	<h1>Stock</h1>
	<table class="half_width">
		<tr>
			<td>Total</td>
			<td style="width:30%"><?= $this->item->getNumberInStock(); ?></td>
		</tr>
	</table>
	<br style="clear:both" />
	<?= $this->stockForm; ?>
</div>