<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'overview')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<div id="stock_search" style="display:none;">
		<div style="padding:4px;text-align:right">
			Search: 
			<select id="searchField">
				<option value="title">Title</option>
				<option value="barcode">Barcode</option>
				<option value="supplier">Supplier</option>
			</select>
			is
			<input type="text" id="searchString" size="30" />
		</div>
		
		<table class="full_width">
    
        	<tr>
            	<th>Article</th>
            	<th>Supplier</th>
            	<th>Number in stock</th>
            	<th>Wait delivery</th>
            	<th>Queue order</th>
            	<th>Booked</th>
            	<th>Actions</th>
			</tr>
			
		</table>
	</div>
	
	<div id="default_page">
    	<table class="full_width">
    
        	<tr>
            	<th>Article</th>
            	<th>Supplier</th>
            	<th>Number in stock</th>
            	<th>Wait delivery</th>
            	<th>Queue order</th>
            	<th>Booked</th>
            	<th>Actions</th>
			</tr>

	        <? foreach ($this->stock as $item): ?>

	            <tr>
	                <td><?= $item->getArticle()->getTitle(); ?></td>
	                <td><?= $item->getArticle()->getSupplier()->getName(); ?></td>
	                <td><?= $item->getNumberInStock(); ?></td>
	                <td><?= $item->getNumberNotDelivered(); ?></td>
	                <td><?= $item->getNumberQueueOrder(); ?></td>
	                <td><?= $item->getNumberBooked() + $item->getNumberAssigned(); ?></td>
					<td>
						<a href="<?= $this->url(array('action' => 'edit', 'id' => $item->getId())); ?>" class="edit">Edit</a>
	                </td>
	            </tr>

	        <? endforeach; ?>
	    </table>

		<?= $this->paginationControl($this->stock, 'all', 'partials/pagination.phtml', array('fullWidth' => true)); ?>
	</div>
</div>

<script language="javascript">
	$(document).ready(function () {
		$.SearchDatabase({
			defaultPage: $('#default_page'),
			searchDiv: $('#stock_search'),
			searchString: $('#searchString'),
			searchField: $('#searchField'),
			url: '<?= $this->url(array('action' => 'search')); ?>',
			display: function (data) {
				$('#stock_search table').find('tr.item').remove();
				$(data).each(function () {
					$('#stock_search table').append(row = $('<tr>', {class: 'item'}));
					row.append('<td>' + this.title + '</td>')
						.append('<td>' + this.supplier + '</td>')
						.append('<td>' + this.numberInStock + '</td>')
						.append('<td>' + this.numberNotDelivered + '</td>')
						.append('<td>' + this.numberQueueOrder + '</td>')
						.append('<td>' + this.numberBookedAssigned + '</td>')
						.append('<td><a href="<?= $this->url(array('action' => 'edit')); ?>/id/' + this.id + '" class="edit">Edit</a></td>');
				});
			}
			,
			clear: function () {
				$('#stock_search table').find('tr.item').remove();
			}
		});
	});
</script>