<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'overview')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
    <table class="full_width">
    
        <tr>
            <th>Article</th>
            <th>Number in stock</th>
            <th>Actions</th>
        </tr>
        
        <? foreach ($this->stock as $item): ?>

            <tr>
                <td><?= $item->getArticle()->getTitle(); ?></td>
                <td><?= $item->getNumberInStock(); ?></td>
				<td></td>
            </tr>
    
        <? endforeach; ?>
    </table>

	<?= $this->paginationControl($this->stock, 'all', 'partials/pagination.phtml', array('fullWidth' => true)); ?>
</div>