<?php

namespace CudiBundle\Repository\Sale\Articles;

use CommonBundle\Component\Util\EntityRepository;

/**
 * History
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class History extends EntityRepository
{
}
