<?php

return array(
    'Prices'                                                                                                                                                                                                                               => 'Prijzen',
    'Your Tickets'                                                                                                                                                                                                                         => 'Uw Tickets',
    'Status'                                                                                                                                                                                                                               => 'Status',
    'Option'                                                                                                                                                                                                                               => 'Optie',
    'Member'                                                                                                                                                                                                                               => 'Lid',
    'Non Member'                                                                                                                                                                                                                           => 'Geen Lid',
    'Number'                                                                                                                                                                                                                               => 'Nummer',
    'Book Date'                                                                                                                                                                                                                            => 'Reserveer Datum',
    'Sold Date'                                                                                                                                                                                                                            => 'Verkoop Datum',
    'Booked'                                                                                                                                                                                                                               => 'Gereserveerd',
    'Sold'                                                                                                                                                                                                                                 => 'Verkocht',
    'Book Tickets'                                                                                                                                                                                                                         => 'Reserveer Tickets',
    'Remove'                                                                                                                                                                                                                               => 'Verwijder',
    'The ticket was succesfully deleted.'                                                                                                                                                                                                  => 'Het ticket is succesvol verwijderd.',
    'An error occurred while deleting the ticket.'                                                                                                                                                                                         => 'Er is een fout opgetreden tijdens het verwijderen van het ticket.',
    'Delete Ticket'                                                                                                                                                                                                                        => 'Verwijder Ticket',
    'Are you sure you want to delete the ticket'                                                                                                                                                                                           => 'Ben je zeker dat je het ticket wil verwijderen',
    'Yes'                                                                                                                                                                                                                                  => 'Ja',
    'No'                                                                                                                                                                                                                                   => 'Neen',
    'Number Member'                                                                                                                                                                                                                        => 'Aantal Lid',
    'Number Non Member'                                                                                                                                                                                                                    => 'Aantal Geen Lid',

    'The tickets were succesfully booked'                                                                                                                                                                                                  => 'De tickets zijn succesvol gereserveerd',
    'There were not enough tickets available'                                                                                                                                                                                              => 'Er waren onvoldoende tickets beschikbaar',

    'The event isn\'t active anymore.'                                                                                                                                                                                                     => 'Het evenement is niet meer actief.',
//    'We recommend logging in or creating an account on the site before ordering tickets if you can. With an account you can manage your tickets through our site, without account you will only receive an email with the ticket details.' => 'We raden aan om in te loggen of een account aan te maken voor je tickets besteld indien mogelijk. Met een account kan je je tickets managen via onze site, zonder account krijg je enkel een email met je ticket details.',

    'We recommend logging in or creating an account on the site before ordering tickets if you can. With an account you can manage your tickets through our site, without account you will only receive an email with the ticket details.' => 'Belangrijk: De link om te betalen wordt via mail verstuurd. Zorg er dus zeker voor dat je het juiste e-mailadres ingeeft. Kijk zeker ook je spam folder na! Deze mail is de enige bevestiging van je inschrijving.',
    'Maximum of '                                                                                                                                                                                                                          => 'Maximaal ',
    'I have read and accept the GDPR terms and condition specified above'                                                                                                                                                                  => 'Ik heb de bovenstaande privacy policy gelezen en ga er mee akkoord',
    'I have read and accept the terms and conditions specified here'                                                                                                                                                                       => 'Ik heb de voorwaarden, <a href="%url%" target="_blank"><strong><u>hier</u></strong></a> te vinden, gelezen en ga er mee akkoord.',
    'Return to the event information'                                                                                                                                                                                                      => 'Ga terug naar de event pagina',
    'Your ticket has expired. Please book a new ticket!'                                                                                                                                                                                   => 'Uw ticket is vervallen. Gelieven een nieuw ticket te reserveren!'
);
