<?php
$this->headMeta()
    ->setCharset('utf-8');
$this->headTitle('Litus Admin', 'PREPEND')
    ->setSeparator('-');

$this->headLink()
    ->appendStylesheet($this->baseUrl('/_admin/stylesheet/css/admin.css'));
$this->headScript()
    ->appendFile($this->baseUrl('/_admin/js/modernizr-1.7.min.js'))
    ->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js');

$this->inlineScript()
    ->appendFile($this->baseUrl('/_admin/js/jquery-ui-1.8.16.custom.min.js'))
    ->appendFile($this->baseUrl('/_admin/js/functions.js'));
?>

<?= $this->docType(); ?>

<html lang="en">
<head>

    <?= $this->headMeta(); ?>
	<?= $this->headTitle(); ?>
	<?= $this->headLink(); ?>
    <?= $this->headScript(); ?>

    <script>
        window.jQuery || document.write("<script src='<?= $this->baseUrl('/_admin/js/jquery-1.6.2.min.js'); ?>'>\x3C/script>")
    </script>

</head>

<body>

<div id="layout">
	<div id="content">
		<header id="content_header">
			<a href="#" title="Litus Manager"></a>
            
			<p><time datetime="<?= date('c', time()); ?>"><?= date('l, F j Y, H:i', time()); ?></time></p>
			<p id="tag">
                Welcome, <?= $this->authenticatedUser; ?> |
                <a href="<?= $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>">Logout</a>
            </p>
		</header>

		<nav id="content_nav">
            <div class="topmenu">
                <div class="title">Admin</div>

                <ul>
                    <? if ($this->hasAccess('admin', 'index', 'index')): ?>
                        <li><a href="<?= $this->url(array('controller' => 'index', 'action' => 'index')); ?>">Dashboard</a></li>
                    <? endif; ?>
                    <? if ($this->hasAccess('admin', 'user', 'index')): ?>
                        <li><a href="<?= $this->url(array('controller' => 'user', 'action' => 'index')); ?>">Users</a></li>
                    <? endif; ?>
                    <? if ($this->hasAccess('admin', 'role', 'index')): ?>
                        <li><a href="<?= $this->url(array('controller' => 'role', 'action' => 'index')); ?>">Groups</a></li>
                    <? endif; ?>
                </ul>
            </div>

            <div class="submenu">
                <div class="title">Divisions</div>

                <?
                if (
                    $this->hasAccess('admin', 'textbook', 'index')
                ):
                ?>
                    <div class="subtitle"><p id="toggleCursusdienst"><b>CuDi</b><br />Articles, Stock &amp; Financial</p></div>
                    <ul id="submenu_cursusdienst">
                        <? if ($this->hasAccess('admin', 'article', 'index')): ?>
                            <li><a href="<?= $this->url(array('controller' => 'article', 'action' => 'index')); ?>">Articles</a></li>
                        <? endif; ?>
						<? if ($this->hasAccess('admin', 'booking', 'index')): ?>
                            <li><a href ="/admin/booking">Bookings</a></li>
                        <? endif; ?>
                        <? if ($this->hasAccess('admin', 'sale', 'index')): ?>
                            <li><a href ="/admin/sale">Sale</a></li>
                        <? endif; ?>
                    </ul>
                <? endif; ?>

                <?
                if (
                    $this->hasAccess('admin', 'company', 'index') ||
                    $this->hasAccess('admin', 'section', 'index') ||
					$this->hasAccess('admin', 'contract', 'index')
                ):
                ?>
                    <div class="subtitle"><p id="toggleBusiness"><b>Business Relations</b><br />Companies &amp; Contracts</p></div>
                    <ul id="submenu_business">
                        <? if ($this->hasAccess('admin', 'company', 'index')): ?>
                            <li><a href="<?= $this->url(array('controller' => 'company', 'action' => 'index')); ?>">Companies</a></li>
                        <? endif; ?>
                        <? if ($this->hasAccess('admin', 'section', 'index')): ?>
                            <li><a href="<?= $this->url(array('controller' => 'section', 'action' => 'index')); ?>">Sections</a></li>
                        <? endif; ?>
                        <? if ($this->hasAccess('admin', 'contract', 'index')): ?>
                            <li><a href="<?= $this->url(array('controller' => 'contract', 'action' => 'index')); ?>">Contracts</a></li>
                        <? endif; ?>
                    </ul>
                <? endif; ?>

				<?
                if (
                    $this->hasAccess('admin', 'run', 'index')
                ):
                ?>
                    <div class="subtitle"><p id="toggleSport"><b>Sport</b><br />Twenty Four</p></div>
                    <ul id="submenu_sport">
                        <? if ($this->hasAccess('admin', 'run', 'index')): ?>
                            <li><a href="<?= $this->url(array('controller' => 'run', 'action' => 'index')); ?>">24h-Run</a></li>
                        <? endif; ?>
                    </ul>
                <? endif; ?>
            </div>
        </nav>

		<div id="content_controller">
            <?= $this->layout()->content; ?>
        </div>
	</div>

	<div id="footer_push"></div>
</div>

<footer>
    Litus Admin | Code by Litus | Design by <a href="http://www.serayo.com">Robin de Bruin</a>

    <? if ('development' == getenv('APPLICATION_ENV')): ?>
        <div class="development_information">
            Execution Time: <?= round(microtime(true) - $this->startExecutionTime, 3) * 1000; ?> ms |
                Doctrine's UoW: <?= $this->doctrineUnitOfWork; ?>
        </div>
    <? endif; ?>
</footer>

<?= $this->inlineScript(); ?>

</body>
</html>
