<?php
$this->plugin('headMeta')
    ->setCharset('utf-8');
$this->plugin('headTitle')
    ->direct('Litus Admin', 'PREPEND')
    ->setSeparator('-');

$this->plugin('headLink')
    ->appendStylesheet($this->plugin('baseurl')->direct('/_admin/stylesheet/css/litus.css'));
$this->plugin('headScript')
    ->appendFile($this->plugin('baseurl')->direct('/_admin/js/modernizr-1.7.min.js'))
    ->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js');

$this->plugin('inlineScript')
    ->appendFile($this->plugin('baseurl')->direct('/_admin/js/jquery-ui-1.8.16.custom.min.js'))
    ->appendFile($this->plugin('baseurl')->direct('/_admin/js/functions.js'));
?>

<?= $this->plugin('doctype'); ?>

<!--[if lt IE 7 ]> 	   <html class="ie ie6 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    	   <html class="ie ie7 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    	   <html class="ie ie8 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    	   <html class="ie ie9 no-js" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> 		 <!--<![endif]-->

<head id="litus" data-template-set="html5-reset">

    <?= $this->plugin('headMeta'); ?>
	<?= $this->plugin('headTitle'); ?>
	<?= $this->plugin('headLink'); ?>
    <?= $this->plugin('headScript'); ?>

    <script>
        window.jQuery || document.write("<script src='<?= $this->plugin('baseurl')->direct('/_admin/js/jquery-1.6.2.min.js'); ?>'>\x3C/script>")
    </script>

</head>

<body>

<div id="layout">
	<div id="content">
		<header id="content_header">
			<a href="#" title="Litus Manager"></a>
            
			<p><time datetime="<?= date('c', time()); ?>"><?= date('l, F j Y, H:i', time()); ?></time></p>
			<p id="tag">Welcome, <?= $this->authenticatedUser; ?></p>
		</header>

		<nav id="content_nav">
            <div class="topmenu">
                <div class="title">Admin</div>

                <ul>
                    <? if ($this->plugin('hasaccess')->direct('admin', 'index', 'index')): ?>
                        <li><a href="/admin">Dashboard</a></li>
                    <? endif; ?>
                    <? if ($this->plugin('hasaccess')->direct('admin', 'setting', 'index')): ?>
                        <li><a href="#">Settings</a></li>
                    <? endif; ?>
                    <? if ($this->plugin('hasaccess')->direct('admin', 'user', 'index')): ?>
                        <li><a href="/admin/user">Users</a></li>
                    <? endif; ?>
                    <? if ($this->plugin('hasaccess')->direct('admin', 'role', 'index')): ?>
                        <li><a href="/admin/role">Groups</a></li>
                    <? endif; ?>
                </ul>
            </div>

            <div class="submenu">
                <div class="title">Divisions</div>

                <?
                if (
                    $this->plugin('hasaccess')->direct('admin', 'textbook', 'index') ||
                    $this->plugin('hasaccess')->direct('admin', 'syllabus', 'index')
                ):
                ?>
                    <div class="subtitle"><p id="toggleCursusdienst"><b>CuDi</b><br />Textbooks, Stock &amp; Financial</p></div>
                    <ul id="submenu_cursusdienst">
                        <? if ($this->plugin('hasaccess')->direct('admin', 'textbook', 'index')): ?>
                            <li><a href ="/admin/textbook">Textbooks</a></li>
                        <? endif; ?>
                        <? if ($this->plugin('hasaccess')->direct('admin', 'syllabus', 'index')): ?>
                            <li><a href ="/admin/syllabus">Syllabus</a></li>
                        <? endif; ?>
                    </ul>
                <? endif; ?>

                <?
                if (
                    $this->plugin('hasaccess')->direct('admin', 'textbook', 'index') ||
                    $this->plugin('hasaccess')->direct('admin', 'syllabus', 'index')
                ):
                ?>
                    <div class="subtitle"><p id="toggleBedrijvenrelaties"><b>Company Relations</b><br />Companies &amp; Contracts</p></div>
                    <ul id="submenu_bedrijvenrelaties">
                        <? if ($this->plugin('hasaccess')->direct('admin', 'textbook', 'index')): ?>
                            <li><a href="/admin/company">Companies</a></li>
                        <? endif; ?>
                        <? if ($this->plugin('hasaccess')->direct('admin', 'textbook', 'index')): ?>
                            <li><a href="/admin/section">Sections</a></li>
                        <? endif; ?>
                        <? if ($this->plugin('hasaccess')->direct('admin', 'textbook', 'index')): ?>
                            <li><a href="/admin/contract/">Contracts</a></li>
                        <? endif; ?>
                    </ul>
                <? endif; ?>
            </div>
        </nav>

		<div id="content_controller">
            <?= $this->plugin('layout')->direct()->content; ?>
        </div>
	</div>

	<div id="footer_push"></div>
</div>

<footer>
    Litus Admin | Code by Litus | Design by <a href="http://www.serayo.com">Robin de Bruin</a>

    <? if ('development' == getenv('APPLICATION_ENV')): ?>
        <div class="development_information">
            Execution Time: <?= round(microtime(true) - $this->startExecutionTime, 3) * 1000; ?> ms |
                Doctrine's UoW: <?= $this->doctrineUnitOfWork; ?>
        </div>
    <? endif; ?>
</footer>

<?= $this->plugin('inlineScript'); ?>

</body>
</html>
