<?= $this->plugin('doctype'); ?>
<html>
<head>
	<?= $this->plugin('headTitle')->direct('Litus CuDi', 'PREPEND'); ?>
	<?= $this->plugin('headLink'); ?>
	<?= $this->plugin('headMeta'); ?>
	<?= $this->plugin('headScript'); ?>
	<?= $this->plugin('headStyle'); ?>
</head>
<body>
	<header>
		<h1>Litus Cudi</h1>
	</header>
	<section id="content">
		<?= $this->plugin('layout')->direct()->content; ?>
	</section>
</body>
</html>