<?php
$this->headMeta()
    ->setCharset('utf-8');
$this->headTitle('24h-Run', 'PREPEND')
    ->setSeparator('-');

$this->headLink()
    ->appendStylesheet($this->baseUrl('/_bootstrap/bootstrap.min.css'))
    ->appendStylesheet($this->baseUrl('/_run/stylesheet/css/run.css'));
$this->headScript()
    ->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js')
    ->appendFile($this->baseUrl('/_bootstrap/js/bootstrap-alerts.js'));
?>

<?= $this->docType(); ?>

<html lang="en">
<head>

	<?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headLink(); ?>
	<?= $this->headScript(); ?>
	<?= $this->headStyle(); ?>

    <script>
        window.jQuery || document.write("<script src='<?= $this->baseUrl('/_run/js/jquery-1.6.2.min.js'); ?>'>\x3C/script>")
    </script>

</head>

<body id="bootstrap-js">

    <div class="topbar">
        <div class="fill">
            <div class="container">
                <h3>
                    <a href="http://www.vtk.be" class="navigation_logo"><img src="<?= $this->baseUrl('/_run/img/vtk.png'); ?>" /></a>
                </h3>

                <? if ('screen' != $this->request()->getControllerName()): ?>
                    <ul>
                        <? if ($this->hasAccess('run', 'queue', 'index')): ?>
                            <li <? if ('queue' == $this->request()->getControllerName()): ?> class="active" <? endif; ?>>
                                <a href="<?= $this->url(array('controller' => 'queue')); ?>">Queue</a>
                            </li>
                        <? endif; ?>

                        <? if ($this->hasAccess('run', 'group', 'index')): ?>
                            <li <? if ('group' == $this->request()->getControllerName()): ?> class="active" <? endif; ?>>
                                <a href="<?= $this->url(array('controller' => 'group')); ?>">Group of Friends</a>
                            </li>
                        <? endif; ?>
                    </ul>
                <? endif; ?>
            </div>
        </div>
    </div>

    <? if ('screen' != $this->request()->getControllerName()): ?>
        <header class="jumbotron subhead" id="overview">
            <div class="inner">
                <div class="container">
                    <h1>24h-Run</h1>
                </div>
            </div>
        </header>
    <? endif; ?>

    <div class="container">
        <?= $this->layout()->content; ?>
    </div>

</body>

</html>