<?= $this->docType(); ?>
<html>
<head>
	<?= $this->headTitle('Litus Sale Application', 'PREPEND'); ?>
	<?= $this->headLink()
                 ->appendStylesheet($this->baseUrl('/_saleapp/stylesheet/css/twitter-bootstrap.css'))
                 ->appendStylesheet($this->baseUrl('/_saleapp/stylesheet/css/saleapp.css')); ?>
	<?= $this->headMeta(); ?>
	<?= $this->headScript()
                 ->appendFile("/_saleapp/js/jquery.min.js"); ?>
	<?= $this->headStyle(); ?>
</head>
<body>
	<section id="content">
		<?= $this->layout()->content; ?>
	</section>
</body>
</html>
