<?= $this->docType(); ?>
<html>
<head>
	<?= $this->headTitle('Litus Sale Application', 'PREPEND'); ?>
	<?= $this->headLink()
                 ->appendStylesheet($this->baseUrl('/_saleapp/stylesheet/css/twitter-bootstrap.css')); ?>
	<?= $this->headMeta(); ?>
	<?= $this->headScript(); ?>
	<?= $this->headStyle(); ?>
</head>
<body>
	<section id="content">
		<?= $this->layout()->content; ?>
	</section>
</body>
</html>
