<?= $this->partial('partials/contract/navigation.phtml', array('currentAction' => 'download')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
    <table class="full_width">
        <thead>
            <tr>
		<th>Contract No</th>
                <th>Title</th>
                <th width="150px">Author</th>
                <th width="75px">Date</th>
		<th>Invoice No</th>
                <th width="200px">Type</th>
            </tr>
        </thead>

        <tbody>
            <? foreach ($this->paginator as $contract): ?>
                <tr>
		    <td><?= $contract->getContractNb(); ?></td>
                    <td><?= $contract->getTitle(); ?></td>
                    <td><?= $contract->getAuthor()->getFirstName(); ?> <?= $contract->getAuthor()->getLastName(); ?></td>
                    <td><?= $contract->getDate()->format('j/m/Y'); ?></td>
		    <td><? if ($contract->isSigned()): ?><?= $contract->getInvoiceNb(); ?><? endif; ?></td>
                    <td>
                        <a href="<?= $this->url(array('action' => 'download', 'id' => $contract->getId(), 'type' => 'contract')); ?>?format=pdf" class="contracts">Contract</a>
                        <a href="<?= $this->url(array('action' => 'download', 'id' => $contract->getId(), 'type' => 'letter')); ?>?format=pdf" class="letter">Letter</a>
                        <? if ($contract->isSigned()): ?><a href="<?= $this->url(array('action' => 'download', 'id' => $contract->getId(), 'type' => 'invoice')); ?>?format=pdf" class="invoice">Invoice</a><? endif ?>
                    </td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>

    <?= $this->paginationControl($this->paginator, 'all', 'partials/pagination.phtml', array('fullWidth' => true)); ?>
</div>
