<?php

namespace FormBundle\Repository\Node\Group;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * Mapping
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mapping extends EntityRepository
{
}
