<?php

namespace CudiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleSubjectMap
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleSubjectMap extends EntityRepository
{
}