<?php

namespace CudiBundle\Repository\Sale\Article\Restriction;

use CudiBundle\Entity\Sale\Article;

/**
 * Study
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Study extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @param  Article $article
     * @return \CudiBundle\Entity\Sale\Article\Restriction\Study|null
     */
    public function findOneByArticle(Article $article)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('r')
            ->from('CudiBundle\Entity\Sale\Article\Restriction\Study', 'r')
            ->where(
                $query->expr()->eq('r.article', ':article')
            )
            ->setParameter('article', $article)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
