<?php

namespace CudiBundle\Repository\Log\Sale;

use CommonBundle\Component\Util\EntityRepository;

/**
 * Assignments
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Assignments extends EntityRepository
{
}
