<?php

namespace CudiBundle\Repository\Users\People\Sale;

use Doctrine\ORM\EntityRepository;

/**
 * Acco
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Acco extends EntityRepository
{
}
