<?= $this->partial('partials/sale/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <table>
    
        <tr>
            <th>Manager</th>
            <th>Open?</th>
            <th>Start</th>
	    <th>End</th>
            <th>Register Start</th>
            <th>Register End</th>
        </tr>
        
        <? foreach ($this->sessions as $session): ?>

            <tr>
                <td><?= $session->getManager(); ?></td>
                <td><?= $session->getCloseDate() > $session->getOpenDate() ? yes : no ?></td>
                <td><?= $session->getOpenDate(); ?></td>
                <td><?= $session->getCloseDate(); ?></td>
                <td><?= $session->getRegisterStart(); ?></td>
                <td><?= $session->getRegisterEnd(); ?></td>
            </tr>
    
        <? endforeach; ?>
    </table>
</div>
