<?  echo $this->partial('partials/sale/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
		
    <h1>Sale Session</h1>

	<p>Manager: <b><?= $session->getManager() ? $session->getManager()->getUserName() : 'guest'; ?></b></p>
	<p>Date openend: <b><?= $session->getOpenDate()->format('Y-m-d H:i:s'); ?></b></p>
	<p>Date closed: <b><?= $session->isOpen() ? '(no)' : $session->getCloseDate()->format('Y-m-d H:i:s'); ?></b></p>

	<table class="half_width">
	
		<tr>
			<th>Cash register start</th>
			<th>Amount</th>
		</tr>
	
		<tr>
			<td></td>
			<td><a href="<?= $this->url(array('action' => 'editregister', 'id' => $session->getOpenAmount()->getId(), 'session' => $session->getId())); ?>">(edit)</a></td>
		</tr>
		<? foreach($this->units as $unit): ?>
			<tr>
				<td style="text-align: right">&euro; <?= number_format($unit->getUnit() / 100, 2); ?></td>
				<td><?= $session->getOpenAmount()->getAmountForUnit($unit)->getAmount(); ?></td>
			</tr>
		<? endforeach; ?>
		<? foreach($this->devices as $device): ?>
			<tr>
				<td style="text-align: right"><?= $device->getName(); ?></td>
				<td>&euro; <?= number_format($session->getOpenAmount()->getAmountForDevice($device)->getAmount() / 100, 2); ?></td>
			</tr>
		<? endforeach; ?>
		<tr>
			<td style="text-align: right">TOTAL:</td>
			<td>&euro; <?= number_format($session->getOpenAmount()->getTotalAmount() / 100, 2); ?></td>
		</tr>

	</table>
	
	<? if (!$session->isOpen()): ?>
		<table class="half_width">
			<tr>
				<th>Cash register end</th>
				<th>Amount</th>
			</tr>

			<tr>
				<td></td>
				<td><a href="<?= $this->url(array('action' => 'editregister', 'id' => $session->getCloseAmount()->getId(), 'session' => $session->getId())); ?>">(edit)</a></td>
			</tr>
			<?php foreach($this->units as $unit): ?>
				<tr>
					<td style="text-align: right">&euro; <?= number_format($unit->getUnit() / 100, 2); ?></td>
					<td><?= $session->getCloseAmount()->getAmountForUnit($unit)->getAmount(); ?></td>
				</tr>
			<?php endforeach; ?>
			<? foreach($this->devices as $device): ?>
				<tr>
					<td style="text-align: right"><?= $device->getName(); ?></td>
					<td>&euro; <?= number_format($session->getCloseAmount()->getAmountForDevice($device)->getAmount() / 100, 2); ?></td>
				</tr>
			<? endforeach; ?>
			<tr>
				<td style="text-align: right">TOTAL:</td>
				<td>&euro; <?= number_format($session->getCloseAmount()->getTotalAmount() / 100, 2); ?></td>
			</tr>

		</table>
	<? endif; ?>

	<?= $commentForm; ?>

</div>

<aside>
	<? if ($session->isOpen()): ?>
		<div class="sidebox">
        	<div class="title">Close Session</div>
        	<div class="content">
            	<p>
                	<i>Please hit the link below to close this sale session!</i>
            	</p>
            	<p>
                	<a href="<?= $this->url(array('action' => 'close', 'id' => $session->getId())); ?>">&rarr; Close</a>
            	</p>
        	</div>
    	</div>
	<? endif; ?>

	<div class="sidebox">
        <div class="title">Sale Application</div>
        <div class="content">
            <p>
                <i>Please hit the link below to open the sale application for regular users!</i>
            </p>
            <p>
                <a href="<?= $this->url(array('action' => 'index', 'controller' => 'sale', 'module' => 'application')); ?>">&rarr; Sale Application</a>
            </p>
        </div>
    </div>

	<div class="sidebox">
        <div class="title">Queue Sign-in</div>
        <div class="content">
            <p>
                <i>Please hit the link below to open queue sign-in page!</i>
            </p>
            <p>
                <a href="<?= $this->url(array('action' => 'queue', 'controller' => 'sale', 'module' => 'application')); ?>">&rarr; Queue Sign-in</a>
            </p>
        </div>
    </div>
</aside>
