<?  echo $this->partial('partials/sale/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <table>
    
        <tr>
            <th>Manager</th>
            <th>Open?</th>
            <th>Start</th>
	    <th>End</th>
            <th>Register Start</th>
            <th>Register End</th>
        </tr>
        
        <? foreach ($this->sessions as $session): ?>

            <tr>
                <td><?= $session->getManager(); ?></td>
                <td><? if( $session->getCloseDate() < $session->getOpenDate() )
			{
				echo "yes";
				$open = true;
			}
			else
			{
				echo "no";
				$open = false;
			} ?></td>
                <td><?= $session->getOpenDate()->format('Y-m-d H:i:s'); ?></td>
                <td><? if( $open == false ) echo $session->getCloseDate()->format('Y-m-d H:i:s'); ?></td>
                <td><?= ($session->getOpenAmount()->getTotalAmount() / 100); ?></td>
                <td><? if( $open == false ) echo ($session->getCloseAmount()->getTotalAmount() / 100); ?></td>
            </tr>
    
        <? endforeach; ?>
    </table>
</div>

