<?php

namespace MailBundle\Repository\Alias;

/**
 * Academic
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Academic extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
