<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ApiBundle\Module'                                                        => __DIR__ . '/Module.php',
    'ApiBundle\Component\Controller\ActionController\ApiController'           => __DIR__ . '/src/Component/Controller/ActionController/ApiController.php',
    'ApiBundle\Component\Controller\Request\Exception\InvalidKeyException'    => __DIR__ . '/src/Component/Controller/Request/Exception/InvalidKeyException.php',
    'ApiBundle\Component\Controller\Request\Exception\NoKeyException'         => __DIR__ . '/src/Component/Controller/Request/Exception/NoKeyException.php',
    'ApiBundle\Component\Controller\Request\Exception\NoPostRequestException' => __DIR__ . '/src/Component/Controller/Request/Exception/NoPostRequestException.php',
    'ApiBundle\Controller\Admin\InstallController'                            => __DIR__ . '/src/Controller/Admin/InstallController.php',
    'ApiBundle\Controller\Admin\KeyController'                                => __DIR__ . '/src/Controller/Admin/KeyController.php',
    'ApiBundle\Controller\AuthController'                                     => __DIR__ . '/src/Controller/AuthController.php',
    'ApiBundle\Controller\MailController'                                     => __DIR__ . '/src/Controller/MailController.php',
    'ApiBundle\Entity\Key'                                                    => __DIR__ . '/src/Entity/Key.php',
    'ApiBundle\Form\Admin\Key\Add'                                            => __DIR__ . '/src/Form/Admin/Key/Add.php',
    'ApiBundle\Form\Admin\Key\Edit'                                           => __DIR__ . '/src/Form/Admin/Key/Edit.php',
    'ApiBundle\Repository\Key'                                                => __DIR__ . '/src/Repository/Key.php',
);
