<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MailBundle\Module'                             => __DIR__ . '/Module.php',
    'MailBundle\Controller\Admin\InstallController' => __DIR__ . '/src/Controller/Admin/InstallController.php',
    'MailBundle\Controller\Admin\MailController'    => __DIR__ . '/src/Controller/Admin/MailController.php',
    'MailBundle\Controller\Admin\ProfController'    => __DIR__ . '/src/Controller/Admin/ProfController.php',
    'MailBundle\Form\Admin\Cudi\Mail'               => __DIR__ . '/src/Form/Admin/Cudi/Mail.php',
    'MailBundle\Form\Admin\Mail\Mail'               => __DIR__ . '/src/Form/Admin/Mail/Mail.php',
);