<?php

namespace TicketBundle\Repository;

use DateTime,
    CommonBundle\Component\Util\EntityRepository;

/**
 * Event
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Event extends EntityRepository
{
    public function findAllQuery()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('e')
            ->from('TicketBundle\Entity\Event', 'e')
            ->innerJoin('e.activity', 'a')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('e.active', 'true'),
                    $query->expr()->gt('a.startDate', ':now')
                )
            )
            ->setParameter('now', new DateTime())
            ->getQuery();

        return $resultSet;
    }

    public function findOldQuery()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('e')
            ->from('TicketBundle\Entity\Event', 'e')
            ->innerJoin('e.activity', 'a')
            ->where(
                $query->expr()->orX(
                    $query->expr()->eq('e.active', 'false'),
                    $query->expr()->lt('a.startDate', ':now')
                )
            )
            ->setParameter('now', new DateTime())
            ->getQuery();

        return $resultSet;
    }
}
