<script language=javascript>

var selected = [];

function bootstrap()
{
  if( isTimeToUpdate() )
  {
    updateDump( "signed_in" );
    updateDump( "collecting" );
    updateDump( "collected" );
    updateDump( "selling" );
    updateDump( "hold" );
    updateDump( "cancelled" );
  }
  setTimeout( bootstrap, 1000 );
}

var pollString = "rawr!"; // very unlikely to be the hash value of the timestamp of the most recent table modification

function isTimeToUpdate()
{
  var xhReq = new XMLHttpRequest();
  xhReq.open("GET", "<?= $this->url(array( 'controller' => 'queue', 'action' => 'poll', 'format' => 'html' )); ?>");
  xhReq.send(null);
  if( xhReq.responseText == pollString )
  {
    return false;
  }

  setTimeout( "pollString = xhReq.responseText;", 50 );
  return true;
}

function updateDump( status )
{
var xhReq = new XMLHttpRequest();
 xhReq.open("GET", "<?= $this->url(array( 'controller' => 'queue', 'action' => 'dump', 'session' => $sessionId, 'format' => 'html' )); ?>/status/"+status, false);
 xhReq.send(null);
 document.getElementById("dumplist_"+status).innerHTML = xhReq.responseText;
}

function itemClick( item, event )
{
  if( selected.length == 1 && selected[0] == item )
  {
    toggleSelect( -1, item );
  }
  else
  {
    if( event.ctrlKey )
    {
      toggleSelect( -1, item );
    }
    else
    {
      deselectAll();
      toggleSelect( -1, item );
    }
  }
}

function deselectAll()
{
  for( var i = 0 ; i < selected.length ; i++ )
  {
    selectOff( selected[i] );
  }
  selected = [];
}

function toggleSelect( index, item )
{
  if( selected.indexOf( item ) == -1 )
  {
    selectOn( item );
    selected.push( item );
  }
  else
  {
    selectOff( item );
    if( index == -1 )
    {
      index = selected.indexOf(item);
    }
    selected.splice( index, 1 );
  }
}

function selectOff( item )
{
  document.getElementById(item).innerHTML="<div class=\"selectable_item\">" + document.getElementById(item).innerHTML.slice(22,-6) + "</div>";
}

function selectOn( item )
{
  document.getElementById(item).innerHTML="<div class=\"selected\">" + document.getElementById(item).innerHTML.slice(29,-6) + "</div>";
}

window.onload=bootstrap;
</script>

<div class="span4">
<div id="dumplist_selling">
</div>
<div id="dumplist_collected">
</div>
<div id="dumplist_collecting">
</div>
<div id="dumplist_signed_in">
</div>
<div id="dumplist_hold">
</div>
<div id="dumplist_cancelled">
</div>
</div>

