<?php

namespace PromBundle\Repository;

/**
 * Bus
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Bus extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @param $academicYear AcademicYear
     * @return array
     */
    public function getGoBusses($academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('b')
            ->from('PromBundle\Entity\Bus', 'b')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('b.direction', ':direction'),
                    $query->expr()->eq('b.academicYear', ':year')
                )
            )
            ->setParameter('direction', 'Go')
            ->setParameter('year', $academicYear)
            ->orderBy('b.departureTime', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $academicYear AcademicYear
     * @return array
     */
    public function getReturnBusses($academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('b')
            ->from('PromBundle\Entity\Bus', 'b')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('b.direction', ':direction'),
                    $query->expr()->eq('b.academicYear', ':year')
                )
            )
            ->setParameter('direction', 'Return')
            ->setParameter('year', $academicYear)
            ->orderBy('b.departureTime', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $academicYear AcademicYear
     * @return array
     */
    public function findAllBusesByAcademicYear($academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('b')
            ->from('PromBundle\Entity\Bus', 'b')
            ->where(
                $query->expr()->eq('b.academicYear', ':year')
            )
            ->setParameter('year', $academicYear)
            ->orderBy('b.departureTime', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
