<?= $this->partial('partials/config/navigation.phtml', array('currentAction' => 'null')); ?>

<div id="controller_action">
    <? if ($this->flushResult && $this->configUpdated): ?>
        <div class="success_message full_width">
            <div class="title">Success</div>
            <div class="content">
                <p>The configuration entry was successfully updated!</p>
            </div>
        </div>
    <? else: ?>
        <? if (!$this->flushResult): ?>
            <div class="error_message">
                <div class="title">Error</div>
                <div class="content">
                    <p>An error occurred while saving the entry to the database. Please try again or contact the administrator.</p>
                </div>
            </div>
        <? endif; ?>

        <?= $this->form; ?>
    <? endif; ?>
</div>
