<header id="controller_header">
    <div class="title"><span class="groups">Groups</span></div>

    <nav id="controller_nav">
        <ul>
            <? if ($this->hasAccess('admin', 'role', 'add')): ?>
                <li><a <? if('add' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->url(array('action' => 'add')); ?>">Add</a></li>
            <? endif; ?>
            <? if ($this->hasAccess('admin', 'role', 'manage')): ?>
                <li><a <? if('manage' == $this->vars('currentAction')) echo 'class="active"'; ?> href="<?= $this->url(array('action' => 'manage')); ?>">Manage</a></li>
            <? endif; ?>
        </ul>
    </nav>
</header>