<?php

namespace PageBundle\Repository;

use PageBundle\Entity\Node\CategoryPage;

/**
 * Frame
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Frame extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @param CategoryPage $page
     */
    public function findAllByCategoryPage(CategoryPage $page){
        return $this->getEntityManager()
            ->getRepository('PageBundle\Entity\Frame')
            ->findBy(array('categoryPage' => $page));
    }

    /**
     * @param CategoryPage $page
     */
    public function findAllActiveByCategoryPage(CategoryPage $page){
        return $this->getEntityManager()
            ->getRepository('PageBundle\Entity\Frame')
            ->findBy(array('categoryPage' => $page, 'active' => true));
    }
}
