<?php

namespace PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Link
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Link extends EntityRepository
{
}
