<?php

namespace PageBundle\Repository;

use CommonBundle\Component\Util\EntityRepository;

/**
 * Link
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Link extends EntityRepository
{
}
