<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'deliveries')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<?= $this->form; ?>
	
	<table class="full_width">
    
        <tr>
            <th>Date</th>
            <th>Article</th>
            <th>Price</th>
			<th>Actions</th>
        </tr>
        
        <? foreach ($this->deliveries as $item): ?>

            <tr>
                <td><?= $item->getDate()->format('Y-m-d H:i:s'); ?></td>
                <td><?= $item->getArticle()->getTitle(); ?></td>
                <td>&euro; <?= number_format($item->getPrice()/100, 2); ?></td>
				<td>
					<a href="<?= $this->url(array('action' => 'delete', 'id' => $item->getId())); ?>" class="delete">Delete</a>
				</td>
            </tr>
    
        <? endforeach; ?>
    </table>

	<?= $this->paginationControl($this->deliveries, 'all', 'partials/pagination.phtml'); ?>
</div>