<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'deliveries')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<table>
    
        <tr>
            <th>Date</th>
            <th>Price</th>
			<th>Actions</th>
        </tr>
        
        <? foreach ($this->deliveries as $delivery): ?>

            <tr>
                <td><?= $delivery->getDate()->format('Y-m-d H:i:s'); ?></td>
                <td>&euro; <?= number_format($delivery->getPrice()/100, 2); ?></td>
				<td></td>
            </tr>
    
        <? endforeach; ?>
    </table>

	<?= $this->paginationControl($this->deliveries, 'all', 'partials/pagination.phtml'); ?>
</div>

<aside>
	<div class="sidebox">
        <div class="title">New Delivery</div>
        <div class="content">
            <p>
                <i>Please hit the link below to add a new delivery!</i>
            </p>
            <p>
                <a href="<?= $this->url(array('action' => 'add')); ?>">&rarr; Add Delivery</a>
            </p>
        </div>
    </div>
</aside>