<?php

namespace LogisticsBundle\Repository;

use CommonBundle\Component\Doctrine\ORM\EntityRepository,
    CommonBundle\Entity\General\AcademicYear;

/**
 * Driver
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Driver extends EntityRepository
{
    public function findOneById($id)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('d')
            ->from('LogisticsBundle\Entity\Driver', 'd')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('d.removed', 'false'),
                    $query->expr()->eq('d.person', ':id')
                )
            )
            ->setParameter('id', $id)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        return $resultSet;
    }

    public function findAllByYearQuery(AcademicYear $year) {

        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('d')
            ->from('LogisticsBundle\Entity\Driver', 'd')
            ->innerJoin('d.years', 'y')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('d.removed', 'false'),
                    $query->expr()->eq('y', ':year')
                )
            )
            ->setParameter('year', $year)
            ->getQuery();

        return $resultSet;
    }

    public function findAllQuery()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('d')
            ->from('LogisticsBundle\Entity\Driver', 'd')
            ->innerJoin('d.person', 'p')
            ->where(
                $query->expr()->eq('d.removed', 'false')
            )
            ->orderBy('p.lastName', 'ASC')
            ->getQuery();

        return $resultSet;
    }
}
