<?php

namespace LogisticsBundle\Repository;

use Doctrine\ORM\Query;
use LogisticsBundle\Entity\InventoryCategory as InventoryCategoryEntity;

/**
 * InventoryCategory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryCategory extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @return Query|null
     */
    public function findAllQuery(): ?Query
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('c')
            ->from(InventoryCategoryEntity::class, 'c')
            ->orderBy('c.name', 'ASC')
            ->getQuery();
    }
}
