<?php

namespace LogisticsBundle\Repository;

use CommonBundle\Entity\General\Organization\Unit;
use Doctrine\ORM\Query;
use LogisticsBundle\Entity\InventoryArticle as InventoryArticleEntity;
use LogisticsBundle\Entity\InventoryCategory;

/**
 * InventoryArticle
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryArticle extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @return Query|null
     */
    public function findAllQuery(): ?Query
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('a')
            ->from(InventoryArticleEntity::class, 'a')
            ->innerJoin('a.unit', 'u')
            ->orderBy('u.name', 'ASC')
            ->addOrderBy('a.category', 'ASC')
            ->addOrderBy('a.name', 'ASC')
            ->getQuery();
    }

    /**
     * @param  string $name
     * @return Query|null
     */
    public function findAllByName(string $name): ?Query
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('a')
            ->from(InventoryArticleEntity::class, 'a')
            ->innerJoin('a.unit', 'u')
            ->where(
                $query->expr()->like($query->expr()->lower('a.name'), ':name')
            )
            ->setParameter('name', '%' . strtolower($name) . '%')
            ->orderBy('u.name', 'ASC')
            ->addOrderBy('a.category', 'ASC')
            ->addOrderBy('a.name', 'ASC')
            ->getQuery();
    }

    /**
     * @param Unit $unit
     * @return Query|null
     */
    public function findAllByUnitQuery(Unit $unit): ?Query
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('a')
            ->from(InventoryArticleEntity::class, 'a')
            ->innerJoin('a.unit', 'u')
            ->where(
                $query->expr()->eq('a.unit', ':unit')
            )
            ->setParameter('unit', $unit)
            ->orderBy('u.name', 'ASC')
            ->addOrderBy('a.category', 'ASC')
            ->addOrderBy('a.name', 'ASC')
            ->getQuery();
    }

    /**
     * @param  string $location
     * @return Query|null
     */
    public function findAllByLocationQuery(string $location): ?Query
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('a')
            ->from(InventoryArticleEntity::class, 'a')
            ->innerJoin('a.unit', 'u')
            ->where(
                $query->expr()->like($query->expr()->lower('a.location'), ':location')
            )
            ->setParameter('location', '%' . strtolower($location) . '%')
            ->orderBy('u.name', 'ASC')
            ->addOrderBy('a.category', 'ASC')
            ->addOrderBy('a.name', 'ASC')
            ->getQuery();
    }

    /**
     * @param  string $visibility
     * @return Query|null
     */
    public function findAllByVisibilityQuery(string $visibility): ?Query
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('a')
            ->from(InventoryArticleEntity::class, 'a')
            ->innerJoin('a.unit', 'u')
            ->where(
                $query->expr()->like($query->expr()->lower('a.visibility'), ':visibility')
            )
            ->setParameter('visibility', '%' . strtolower($visibility) . '%')
            ->orderBy('u.name', 'ASC')
            ->addOrderBy('a.category', 'ASC')
            ->addOrderBy('a.name', 'ASC')            
            ->getQuery();
    }

    /**
     * @param  string $status
     * @return Query|null
     */
    public function findAllByStatusQuery(string $status): ?Query
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('a')
            ->from(InventoryArticleEntity::class, 'a')
            ->innerJoin('a.unit', 'u')
            ->where(
                $query->expr()->like($query->expr()->lower('a.status'), ':status')
            )
            ->setParameter('status', '%' . strtolower($status) . '%')
            ->orderBy('u.name', 'ASC')
            ->addOrderBy('a.category', 'ASC')
            ->addOrderBy('a.name', 'ASC')
            ->getQuery();
    }

    /**
     * @param string $visibility
     * @param string $status
     * @param InventoryCategory $category
     * @return Query|null
     */
    public function findAllByVisibilityAndStatusAndCategoryQuery(string $visibility, string $status, InventoryCategory $category): ?Query
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('a')
            ->from(InventoryArticleEntity::class, 'a')
            ->innerJoin('a.unit', 'u')
            ->where(
                $query->expr()->andX(
                    $query->expr()->like($query->expr()->lower('a.visibility'), ':visibility'),
                    $query->expr()->like($query->expr()->lower('a.status'), ':status'),
                    $query->expr()->eq('a.category', ':category'),
                )
            )
            ->setParameter('status', '%' . strtolower($status) . '%')
            ->setParameter('visibility', '%' . strtolower($visibility) . '%')
            ->setParameter('category', $category)
            ->orderBy('u.name', 'ASC')
            ->addOrderBy('a.category', 'ASC')
            ->addOrderBy('a.name', 'ASC')
            ->getQuery();
    }
}
