<?= $this->partial('partials/section/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
    <div class="error_message full_width">
        <div class="title">Warning</div>
        <div class="content">
            <? if ($this->sectionDeleted): ?>
                <p>The section was successfully deleted.</p>
            <? else: ?>
                <p>
                    You are about to delete the following section: <b><?= $this->section->getName(); ?></b>;
                    this section was created by <b><?= $this->section->getAuthor()->getFullName(); ?></b>.
                    When you delete a section, this section will also be removed from all contracts it was assigned to.
                </p>

                <p>
                    Please note that this operation cannot be undone!
                </p>

                <p>
                    Are you sure you want to continue?<br />
                    <a href="<?= $this->url(array('confirm' => '1')); ?>">Yes</a>
                    <a href="<?= $this->url(array('confirm' => '0')); ?>">No</a>
                </p>
            <? endif; ?>
        </div>
    </div>
</div>