<?php

namespace CudiBundle\Repository\User\Person\Sale;

/**
 * Acco
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Acco extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
