<?php

namespace ApiBundle\Repository\Token;

use ApiBundle\Entity\Code\Authorization as AuthorizationCode;
use DateTime;

/**
 * Access
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Access extends \ApiBundle\Repository\Token
{
    /**
     * @param  AuthorizationCode|null $authorizationCode
     * @return \ApiBundle\Entity\Token\Access|null
     */
    public function findOneActiveByCode($code)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('a')
            ->from('ApiBundle\Entity\Token\Access', 'a')
            ->where(
                $query->expr()->andX(
                    $query->expr()->gt('a.expirationTime', ':now'),
                    $query->expr()->eq('a.code', ':code')
                )
            )
            ->setParameter('now', new DateTime())
            ->setParameter('code', $code)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
