<?php

namespace BrBundle\Repository\Match\Profile;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyProfile extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
