<?php

namespace ShopBundle\Repository\Session;

/**
 * Message
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Message extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('m')
            ->from('ShopBundle\Entity\Session\Message', 'm')
            ->getQuery();
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllActiveQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('m')
            ->from('ShopBundle\Entity\Session\Message', 'm')
            ->where(
                $query->expr()->eq('m.active', 'true')
            )
            ->getQuery();
    }
}
