<?php
/**
 * Litus is a project by a group of students from the KU Leuven. The goal is to create
 * various applications to support the IT needs of student unions.
 *
 * @author Niels Avonds <niels.avonds@litus.cc>
 * @author Karsten Daemen <karsten.daemen@litus.cc>
 * @author Koen Certyn <koen.certyn@litus.cc>
 * @author Bram Gotink <bram.gotink@litus.cc>
 * @author Dario Incalza <dario.incalza@litus.cc>
 * @author Pieter Maene <pieter.maene@litus.cc>
 * @author Kristof Mariën <kristof.marien@litus.cc>
 * @author Lars Vierbergen <lars.vierbergen@litus.cc>
 * @author Daan Wendelen <daan.wendelen@litus.cc>
 * @author Mathijs Cuppens <mathijs.cuppens@litus.cc>
 * @author Floris Kint <floris.kint@vtk.be>
 *
 * @license http://litus.cc/LICENSE
 */

namespace CudiBundle\Repository\Comment;

use CudiBundle\Entity\Article;
use CudiBundle\Entity\Comment\Comment as CommentEntity;

/**
 * Mapping
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mapping extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    /**
     * @param  Article       $article
     * @param  CommentEntity $comment
     * @return \CudiBundle\Entity\Comment\Mapping|null
     */
    public function findOneByArticleAndComment(Article $article, CommentEntity $comment)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('m')
            ->from('CudiBundle\Entity\Comment\Mapping', 'm')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('m.article', ':article'),
                    $query->expr()->eq('m.comment', ':comment')
                )
            )
            ->setParameter('article', $article)
            ->setParameter('comment', $comment)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param  Article $article
     * @return \Doctrine\ORM\Query
     */
    public function findAllByArticleQuery(Article $article)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('m')
            ->from('CudiBundle\Entity\Comment\Mapping', 'm')
            ->where(
                $query->expr()->eq('m.article', ':article')
            )
            ->setParameter('article', $article)
            ->getQuery();
    }
}
