<?php

namespace CudiBundle\Repository\Comment;

use CudiBundle\Entity\Article,
    CudiBundle\Entity\Comment\Comment as CommentEntity,
    CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * Mapping
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mapping extends EntityRepository
{
    public function findOneByArticleAndComment(Article $article, CommentEntity $comment)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('m')
            ->from('CudiBundle\Entity\Comment\Mapping', 'm')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('m.article', ':article'),
                    $query->expr()->eq('m.comment', ':comment')
                )
            )
            ->setParameter('article', $article)
            ->setParameter('comment', $comment)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        return $resultSet;
    }

    public function findAllByArticleQuery(Article $article)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('m')
            ->from('CudiBundle\Entity\Comment\Mapping', 'm')
            ->where(
                $query->expr()->eq('m.article', ':article')
            )
            ->setParameter('article', $article)
            ->getQuery();

        return $resultSet;
    }
}
