<?php

namespace BrBundle\Repository\Company;

use BrBundle\Entity\Company as CompanyEntity,
    Doctrine\ORM\EntityRepository;

/**
 * Event
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Event extends EntityRepository
{
    public function findAllByCompany(CompanyEntity $company)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('e')
            ->from('BrBundle\Entity\Company\Event', 'e')
            ->where(
                $query->expr()->eq('e.company', ':company')
            )
            ->setParameter('company', $company->getId())
            ->orderBy('e.startDate', 'DESC')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }
}
