<header id="controller_header">
    <div class="title"><span class="textbooks">Textbooks</span></div>

    <nav id="controller_nav">
        <ul>
        	<li><a <? if('manage' == $this->vars('currentAction')) echo 'class="active"'; ?> href="/admin/textbook/manage">Manage</a></li>
            <li><a <? if('add' == $this->vars('currentAction')) echo 'class="active"'; ?> href="/admin/textbook/add">Add</a></li>
        </ul>
    </nav>
</header>