<?php

namespace CudiBundle\Repository\Comments;

use CudiBundle\Entity\Article,
    Doctrine\ORM\EntityRepository;

/**
 * Comment
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Comment extends EntityRepository
{
    public function findAllByArticle(Article $article)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('m')
            ->from('CudiBundle\Entity\Comments\Mapping', 'm')
            ->where(
                $query->expr()->eq('m.article', ':article')
            )
            ->setParameter('article', $article->getId())
            ->getQuery()
            ->getResult();

        $comments = array();
        foreach($resultSet as $mapping)
            $comments[] = $mapping->getComment();

        return $comments;
    }
}
