<?= $this->partial('partials/booking/navigation.phtml', array('currentAction' => 'delete')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
    <div class="error_message flashmessage">
        <div class="title">Warning</div>
        <div class="content">
			<p>
				You are about to delete the following booking of <b><?= $booking->getPerson()->getFullName(); ?></b>: <b><?= $this->booking->getArticle()->getTitle(); ?></b>!<br />
				Please note that this operation cannot be undone!
			</p>
			<p>
				Are you sure you want to continue?<br />
				<a href="<?= $this->url(array('confirm' => '1')); ?>">Yes</a>
				<a href="<?= $this->url(array('confirm' => '0')); ?>">No</a>
			</p>
        </div>
    </div>
</div>