<?= $this->partial('partials/booking/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="controller_action">
    <? foreach($this->flashMessages as $message) { echo $message; } ?>

    <table class="full_width">
    
        <tr>
            <th>Person</th>
            <th>Article</th>
            <th>Book date</th>
            <th>Status</th>
        </tr>
        
        <? foreach ($this->paginator as $booking): ?>

            <tr>
                <td><?= $booking->getPerson()->getFullName(); ?></td>
                <td><?= $booking->getArticle()->getTitle(); ?></td>
                <td><?= $booking->getBookDate()->format('d/m/Y H:i'); ?></td>
                <td><?= $booking->getStatus(); ?></td>
            </tr>
    
        <? endforeach; ?>
    </table>

	<?= $this->paginationControl($this->paginator, 'all', 'partials/pagination.phtml', array('fullWidth' => true)); ?>
</div>