<?= $this->partial('partials/booking/navigation.phtml', array('currentAction' => 'manage')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<div id="stock_search" style="display:none;">
		<div style="padding:4px;text-align:right">
			Search: 
			<select id="searchField">
				<option value="person">Person</option>
				<option value="article">Article</option>
				<option value="status">Status</option>
			</select>
			is
			<input type="text" id="searchString" size="30" />
		</div>
		
		<table>
	
	    	<tr>
	        	<th>Person</th>
	        	<th>Article</th>
	        	<th>Number</th>
	        	<th>Book date</th>
	        	<th>Status</th>
	        	<th>Actions</th>
			</tr>
			
		</table>
	</div>
	
	<div id="default_page">
		<table>
	    
	        <tr>
	            <th>Person</th>
	            <th>Article</th>
	            <th>Number</th>
	            <th>Book date</th>
	            <th>Status</th>
				<th>Actions</th>
	        </tr>
	        
	        <? foreach ($this->paginator as $booking): ?>
	
	            <tr>
	                <td><?= $booking->getPerson()->getFullName(); ?></td>
	                <td><?= $booking->getArticle()->getTitle(); ?></td>
	                <td><?= $booking->getNumber(); ?></td>
	                <td><?= $booking->getBookDate()->format('d/m/Y H:i'); ?></td>
	                <td><?= $booking->getStatus(); ?></td>
	                <td>
						<? if ('assigned' == $booking->getStatus()): ?>
							<a href="<?= $this->url(array('action' => 'unassign', 'id' => $booking->getId())); ?>" class="edit">Unassign</a>
						<? elseif ('booked' == $booking->getStatus()): ?>
							<a href="<?= $this->url(array('action' => 'delete', 'id' => $booking->getId())); ?>" class="delete">Delete</a>
						<? endif; ?>
					</td>
	            </tr>
	    
	        <? endforeach; ?>
	    </table>
	
		<?= $this->paginationControl($this->paginator, 'all', 'partials/pagination.phtml'); ?>	
	</div>
</div>

<aside>
	<div class="sidebox">
        <div class="title">Assign bookings</div>
       	<div class="content">
	    	<p>
	        	<i>Please hit the link below to assign bookings!</i>
	        </p>
	        <p>
	           	<a href="<?= $this->url(array('action' => 'assign')); ?>">&rarr; Assign bookings</a>
	        </p>
	    </div>
	</div>
</aside>

<script language="javascript">
	$(document).ready(function () {
		$.SearchDatabase({
			defaultPage: $('#default_page'),
			searchDiv: $('#stock_search'),
			searchString: $('#searchString'),
			searchField: $('#searchField'),
			url: '<?= $this->url(array('action' => 'search')); ?>',
			display: function (data) {
				$('#stock_search table').find('tr.item').remove();
				$(data).each(function () {
					$('#stock_search table').append(row = $('<tr>', {class: 'item'}));
					row.append('<td>' + this.person + '</td>')
						.append('<td>' + this.article + '</td>')
						.append('<td>' + this.number + '</td>')
						.append('<td>' + this.bookDate + '</td>')
						.append('<td>' + this.status + '</td>')
						.append(actions = $('<td>'));
					if ('assigned' == this.status)
						actions.append('<a href="<?= $this->url(array('action' => 'unassign')); ?>/id/' + this.id + '" class="edit">Unassign</a>');
					else if ('booked' == this.status)
						actions.append('<a href="<?= $this->url(array('action' => 'delete')); ?>/id/' + this.id + '" class="delete">Delete</a>');
				});
			},
			clear: function () {
				$('#stock_search table').find('tr.item').remove();
			}
		});
	});
</script>