<?php

namespace SecretaryBundle\Repository\Syllabus\Enrollment;

use CommonBundle\Entity\General\AcademicYear;
use CommonBundle\Entity\User\Person\Academic;
use SyllabusBundle\Entity\Subject as SubjectEntity;

/**
 * Subject
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Subject extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    public function findAllByAcademicAndAcademicYearQuery(Academic $academic, AcademicYear $academicYear)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s')
            ->from('SecretaryBundle\Entity\Syllabus\Enrollment\Subject', 's')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('s.academic', ':academic'),
                    $query->expr()->eq('s.academicYear', ':academicYear')
                )
            )
            ->setParameter('academic', $academic)
            ->setParameter('academicYear', $academicYear)
            ->getQuery();
    }

    public function findOneByAcademicAndAcademicYearAndSubject(Academic $academic, AcademicYear $academicYear, SubjectEntity $subject)
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('s')
            ->from('SecretaryBundle\Entity\Syllabus\Enrollment\Subject', 's')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('s.academic', ':academic'),
                    $query->expr()->eq('s.academicYear', ':academicYear'),
                    $query->expr()->eq('s.subject', ':subject')
                )
            )
            ->setParameter('academic', $academic)
            ->setParameter('academicYear', $academicYear)
            ->setParameter('subject', $subject)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
