parameters:
  phpVersion: ''

steps:
  - script: |
      PKG_VERSION=$(sudo apt list --installed | sed -n 's/php${{ parameters.phpVersion }}-fpm\/.* \(.*\) .* .*/\1/p')

      sudo apt update
      sudo apt install php-imagick php-mailparse php-redis php${{ parameters.phpVersion }}-intl=$PKG_VERSION php${{ parameters.phpVersion }}-curl=$PKG_VERSION php${{ parameters.phpVersion }}-pgsql=$PKG_VERSION php${{ parameters.phpVersion }}-soap=$PKG_VERSION php${{ parameters.phpVersion }}-xml=$PKG_VERSION php${{ parameters.phpVersion }}-zip=$PKG_VERSION
    displayName: 'Install PHP Modules'
