parameters:
  phpVersion: ''

steps:
  - script: |
      sudo update-alternatives --set php /usr/bin/php${{ parameters.phpVersion }}
      sudo update-alternatives --set phar /usr/bin/phar${{ parameters.phpVersion }}
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg${{ parameters.phpVersion }}
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi${{ parameters.phpVersion }}
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar${{ parameters.phpVersion }}
      php -version
    displayName: 'Use PHP ${{ parameters.phpVersion }}'
