<?php

namespace NotificationBundle\Repository\Node;

use DateTime;

/**
 * Notification
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Notification extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
    public function findAllQuery()
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('n')
            ->from('NotificationBundle\Entity\Node\Notification', 'n')
            ->orderBy('n.creationTime', 'DESC')
            ->getQuery();
    }

    public function findAllActiveQuery()
    {
        $now = new DateTime();

        $query = $this->getEntityManager()->createQueryBuilder();
        return $query->select('n')
            ->from('NotificationBundle\Entity\Node\Notification', 'n')
            ->where(
                $query->expr()->andx(
                    $query->expr()->lte('n.startDate', ':now'),
                    $query->expr()->gte('n.endDate', ':now'),
                    $query->expr()->eq('n.active', 'true')
                )
            )
            ->setParameter('now', $now)
            ->orderBy('n.creationTime', 'DESC')
            ->getQuery();
    }
}
