<?php
/**
 * Litus is a project by a group of students from the KU Leuven. The goal is to create
 * various applications to support the IT needs of student unions.
 *
 * @author Niels Avonds <niels.avonds@litus.cc>
 * @author Karsten Daemen <karsten.daemen@litus.cc>
 * @author Koen Certyn <koen.certyn@litus.cc>
 * @author Bram Gotink <bram.gotink@litus.cc>
 * @author Dario Incalza <dario.incalza@litus.cc>
 * @author Pieter Maene <pieter.maene@litus.cc>
 * @author Kristof Mariën <kristof.marien@litus.cc>
 * @author Lars Vierbergen <lars.vierbergen@litus.cc>
 * @author Daan Wendelen <daan.wendelen@litus.cc>
 *
 * @license http://litus.cc/LICENSE
 */

namespace CommonBundle\Repository\User\Person\Organization;

use CommonBundle\Entity\General\AcademicYear,
    CommonBundle\Entity\General\Organization\Unit,
    CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * UnitMap
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitMap extends EntityRepository
{
    public function findAllByUnitAndAcademicYearQuery(Unit $unit, AcademicYear $academicYear)
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('u, a')
            ->from('CommonBundle\Entity\User\Person\Organization\UnitMap', 'u')
            ->innerJoin('u.academic', 'a')
            ->where(
                $query->expr()->andX(
                    $query->expr()->eq('u.unit', ':unit'),
                    $query->expr()->eq('u.academicYear', ':academicYear')
                )
            )
            ->setParameter('unit', $unit)
            ->setParameter('academicYear', $academicYear)
            ->orderBy('a.lastName', 'ASC')
            ->addOrderBy('a.firstName', 'ASC')
            ->getQuery();

        return $resultSet;
    }
}
