<?php

namespace CudiBundle\Repository\Article\Option;

use Doctrine\ORM\EntityRepository;

/**
 * Binding
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Binding extends EntityRepository
{
}
