<?php

namespace CudiBundle\Repository\Article\Option;

use CommonBundle\Component\Doctrine\ORM\EntityRepository;

/**
 * Color
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Color extends EntityRepository
{
}
