<?php

namespace CudiBundle\Repository\Article\Option;

/**
 * Color
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Color extends \CommonBundle\Component\Doctrine\ORM\EntityRepository
{
}
