<?php

namespace CudiBundle\Repository\Sales;

use Doctrine\ORM\EntityRepository;

/**
 * SaleItem
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleItem extends EntityRepository
{
}