<?php

namespace CudiBundle\Repository\Sales;

use Doctrine\ORM\EntityRepository;

/**
 * ServingQueueStatus
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServingQueueStatus extends EntityRepository
{

	public function findOneByName($name)
	{
		$query = $this->_em->createQueryBuilder();
		$resultSet = $query->select('s')
			->from('CudiBundle\Entity\Sales\ServingQueueStatus', 's')
			->where($query->expr()->eq('s.name', ':name'))
			->setParameter('name', $name)
			->setMaxResults(1)
			->getQuery()
			->getResult();
		
		if (isset($resultSet[0]))
			return $resultSet[0];
		
		return null;
	}
}