name: PHP

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install Composer dependencies
        uses: litusproject/composer-install-action@main

      - name: Run PHP_CodeSniffer
        if: ${{ always() }}
        uses: litusproject/php-codesniffer-action@main

      - name: Run PHPStan
        if: ${{ always() }}
        uses: litusproject/phpstan-action@main

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Bring up containers
        run: docker-compose up -d

      - name: Initialise Litus
        run: docker-compose run --rm php-cli init

      - name: Test response
        run: curl -fsSL -I --retry 5 --retry-delay 0 --retry-max-time 30 http://localhost:8080
