name: PHP

on:
  - pull_request
  - push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Restore PHP_CodeSniffer cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/phpcs
          key: ${{ runner.os }}-phpcs-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-phpcs-

      - name: Restore PHPStan cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/phpcs
          key: ${{ runner.os }}-phpstan-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-phpstan-

      - name: Install Composer dependencies
        run: >
          composer install \
            --no-interaction \
            --no-progress \
            --prefer-dist

      - name: Run PHP_CodeSniffer
        if: always()
        run: >
          ./vendor/bin/phpcs \
            -q \
            --cache=${{ runner.temp }}/phpcs \
            --report=checkstyle \
            | cs2pr --graceful-warnings

      - name: Save PHP_CodeSniffer cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ runner.temp }}/phpcs
          key: ${{ runner.os }}-phpcs-${{ hashFiles('**/composer.lock') }}

      - name: Run PHPStan
        if: always()
        env:
          PHPSTAN_TMP_DIR: ${{ runner.temp }}/phpstan
        run: ./vendor/bin/phpstan analyse --error-format=github --no-progress

      - name: Save PHPStan cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ runner.temp }}/phpstan
          key: ${{ runner.os }}-phpstan-${{ hashFiles('**/composer.lock') }}
