name: PHP

on:
  - pull_request
  - push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: cs2pr

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: >
          composer install \
            --no-interaction \
            --no-progress \
            --prefer-dist

      - name: Run PHP_CodeSniffer
        if: always()
        run: ./vendor/bin/phpcs -q --report=checkstyle | cs2pr --graceful-warnings

      - name: Run PHPStan
        if: always()
        run: ./vendor/bin/phpstan analyse --error-format=github --no-progress

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bring up containers
        run: docker-compose up -d

      - name: Initialise Litus
        run: docker-compose run --rm php-cli init

      - name: Test response
        run: curl -fsSL -I --retry 5 --retry-delay 0 --retry-max-time 30 http://localhost:8080
