<?php

namespace CudiBundle\Repository\Article;

use CommonBundle\Component\Util\EntityRepository;

/**
 * External
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class External extends EntityRepository
{
}
