<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'orders')); ?>

<div id="controller_action">
    <div class="error_message full_width">
        <div class="title">Warning</div>
        <div class="content">
			<p>
				You are about to delete the following order item: <b><?= $this->item->getArticle()->getTitle(); ?></b> (x <?= $item->getNumber(); ?>)!<br />
				Please note that this operation cannot be undone!
			</p>
			<p>
				Are you sure you want to continue?<br />
				<a href="<?= $this->url(array('confirm' => '1')); ?>">Yes</a>
				<a href="<?= $this->url(array('confirm' => '0')); ?>">No</a>
			</p>
        </div>
    </div>
</div>