<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'orders')); ?>

<div id="controller_action">
    <? foreach($this->flashMessages as $message) { echo $message; } ?>

	<?= $this->form; ?>
	
	<table>
		
		<tr>
			<th>Article</th>
			<th>Number</th>
			<th>Actions</th>
		</tr>
		
		<? foreach($this->order->getOrderItems() as $item): ?>
			<tr>
				<td><?= $item->getArticle()->getTitle(); ?></td>
				<td><?= $item->getNumber(); ?></td>
				<td>
					<a href="<?= $this->url(array('action' => 'deleteitem', 'id' => $item->getId())); ?>" class="delete">Delete</a>
				</td>
			</tr>
		<? endforeach; ?>
		
	</table>
</div>

<aside>
	<div class="sidebox">
        <div class="title">New Order Item</div>
        <div class="content">
            <p>
                <i>Please hit the link below to add a new order item!</i>
            </p>
            <p>
                <a href="<?= $this->url(array('action' => 'additem')); ?>">&rarr; Add order item</a>
            </p>
        </div>
    </div>
</aside>