<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'orders')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<table>
		
		<tr>
			<th>Article</th>
			<th>Number</th>
			<th>Actions</th>
		</tr>
		
		<? foreach($this->order->getOrderItems() as $item): ?>
			<tr>
				<td><?= $item->getArticle()->getTitle(); ?></td>
				<td><?= $item->getNumber(); ?></td>
				<td>
					<? if (!$this->order->isPlaced()): ?>
						<a href="<?= $this->url(array('action' => 'deleteitem', 'id' => $item->getId())); ?>" class="delete">Delete</a>
					<? endif; ?>
				</td>
			</tr>
		<? endforeach; ?>
		
	</table>
</div>

<aside>
	<? if (!$this->order->isPlaced()): ?>
		<div class="sidebox">
	        <div class="title">Place Order</div>
	        <div class="content">
	            <p>
	                <i>Please hit the link below to place this order!</i>
	            </p>
	            <p>
	                <a href="<?= $this->url(array('action' => 'place')); ?>">&rarr; Place order</a>
	            </p>
	        </div>
	    </div>
		<div class="sidebox">
	        <div class="title">New Order Item</div>
	        <div class="content">
	            <p>
	                <i>Please hit the link below to add a new order item!</i>
	            </p>
	            <p>
	                <a href="<?= $this->url(array('action' => 'additem')); ?>">&rarr; Add order item</a>
	            </p>
	        </div>
	    </div>
	<? else: ?>
		<div class="sidebox">
	        <div class="title">Print Order</div>
	        <div class="content">
	            <p>
	                <i>Please hit the link below to print the order for the supplier!</i>
	            </p>
	            <p>
	                <a href="<?= $this->url(array('action' => 'print')); ?>" target="_blank">&rarr; Print order</a>
	            </p>
	        </div>
	    </div>
	<? endif; ?>
</aside>