<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'orders')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<table>
    
        <tr>
            <th>Name</th>
			<th>Actions</th>
        </tr>
        
        <? foreach ($this->suppliers as $supplier): ?>
            <tr>
                <td><?= $supplier->getName(); ?></td>
				<td>
					<a href="<?= $this->url(array('action' => 'supplier', 'id' => $supplier->getId())); ?>" class="edit">Edit</a>
				</td>
            </tr>
        <? endforeach; ?>
    </table>
</div>