<?= $this->partial('partials/stock/navigation.phtml', array('currentAction' => 'orders')); ?>

<div id="flashmessenger">
	<? foreach($this->flashMessages as $message) { echo $message; } ?>
</div>

<div id="controller_action">
	<table>
    
        <tr>
            <th>Supplier</th>
            <th>Date</th>
            <th>Price</th>
			<th>Actions</th>
        </tr>
        
        <? foreach ($this->orders as $order): ?>

            <tr>
                <td><?= $order->getSupplier()->getName(); ?></td>
                <td><?= $order->getDate()->format('Y-m-d H:i:s'); ?></td>
                <td>&euro; <?= number_format($order->getPrice()/100, 2); ?></td>
				<td>
					<a href="<?= $this->url(array('action' => 'edit', 'id' => $order->getId())); ?>" class="edit">Edit</a>
				</td>
            </tr>
    
        <? endforeach; ?>
    </table>

	<?= $this->paginationControl($this->orders, 'all', 'partials/pagination.phtml'); ?>
</div>

<aside>
	<div class="sidebox">
        <div class="title">New Order</div>
        <div class="content">
            <p>
                <i>Please hit the link below to add a new order!</i>
            </p>
            <p>
                <a href="<?= $this->url(array('action' => 'add')); ?>">&rarr; Add order</a>
            </p>
        </div>
    </div>
</aside>